### ISSUE TITLE
[persistence] Checkpoint 기능을 위한 틀 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#192]
Persistence의 checkpoint 기능 수행을 위한 틀을 개발 한다.

checkpoint thread가 구동되어 snapshot 기능을 수행하도록 한다.

Snapshot 기능은 file path를 argument로 받아서 수행할 수 있도록 한다.
이후 진행 예정인 일시적인 snapshot 기능 개발을 위함이다.

**Comment by SuhwanJang** [comment]
- engine 구동 시 checkpoint thread를 생성
- checkpoint thread는 snapshot 기능을 직접 수행
- checkpoint 수행주기는 60초로 설정(임시)
- snapshot 동작 전 file set 생성, 완료 후 제거.
- snapshot file에 대해서만 작동(향후 command log file 포함)
- backup file create, snapshot 에러 발생 시 syslog 출력 -> 5초 주기로 checkpoint retry
- backup file remove 실패 -> 5초 주기로 remove retry. (checkpoint 수행과 별도로 진행.)
- 계속된 remove fail로 disk space 부족한 경우 checkpoint 수행 일시중단.

향후 작업 :
- disk i/o 작업 실패시 오류 핸들링 필요.
- 추후 file create/remove 시 발생하는 에러 중 retry가 의미없는 에러 assert
- command log size 기반 수행
- 파일 set는 remove 실패 시 2개 이상 존재할 수 있으며 snapshot 파일 끝에 구분자를 넣어서 최신 파일을 구분하도록 함.

**Comment by SuhwanJang** [comment]
@MinWooJin
본 이슈 PR이 merge 되었습니다. https://github.com/naver/arcus-memcached/commit/84c2773780a3df2053bb1099d4fea4a661f30146
close 요청드립니다.
