### ISSUE TITLE
[persistence] Hash bucket 단위의 snapshot 기능 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#193]
Hash bucket 단위로 hash table을 scan하여,
Cache item을 snapshot 하는 기능을 개발 한다.

실제 item을 파일에 기록하는 기능은 별도의 issue에서 진행한다.

**Comment by MinWooJin** [comment]
Hash bucket 단위의 snapshot은 collection item의 snapshot을 고려하면
cache lock을 오랫동안 점유하게 되는 문제가 발생하게 된다.
n개 hash item 단위로 snapshot 하도록 변경 할 필요가 있다.

@jhpark816 
검토해 주시면 좋을 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin 
현재 hash bucket 단위가 아닌
N개 hash item 단위로 snapshot하도록 구현한 상태입니다.
N 값의 조절을 통해 cache lock 잡는 기간을 조절할 수 있으며,
reference count 증가를 통해 hash item pointer만 얻어오도록 한 상태입니다.

따라서, 본 이슈는 close하여도 된다고 생각합니다.

**Comment by MinWooJin** [comment]
@SuhwanJang
초기 설계에서 변경되는 부분입니다.
변경되는 이유와 어떤 방식으로 변경이 되었는지 알고 있어야 합니다.
확인하고 close 해주세요.

**Comment by SuhwanJang** [comment]
@MinWooJin
> 초기 설계에서 변경되는 부분입니다.
> 변경되는 이유와 어떤 방식으로 변경이 되었는지 알고 있어야 합니다.
> 확인하고 close 해주세요.

확인하였습니다. close 요청 드립니다.
