### ISSUE TITLE
[persistence] Collection item snapshot 기능 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#195]
Collection item을 파일에 기록하는 snapshot 기능을 개발한다.
Collection(liset, set, map, b+tree) log record format을 정의하고 기록한다.

**Comment by MinWooJin** [comment]
Collection item은 hash item - n collection element 로 구성되어 있다.
bucket 단위 snapshot 기능을 수행할 때, collection item 의 element가 많으면
cache lock을 오랫동안 점유하게 되는 문제가 있다.

snapshot 수행 도중 normal operation 처리에 지연을 최소화 하는 목적과 맞지 않게 되며
n 개 단위의 collection item snapshot과 그 동안 item 변경이 일어나지 않음을
모든 element의 reference count를 증가시키는 방법이나, 다른 방법을 통해 보장해야 한다.

**Comment by MinWooJin** [comment]
현재 snapshot 에서 사용하고 있는 assoc_scan_next 는
함수 내부에서 array_size만큼 cache item의 주소를 담고 return 하는 형태로 동작하며,
collection snapshot을 생각하면 위의 형태는 맞지 않다고 생각됨.

하나의 cache item 단위로 scan하고 cost 계산을 통해,
collection item일 경우 element scan하는 cost를 반영하도록 해야 함.

**Comment by jhpark816** [comment]
element 조회를 위한 assoc_scan_next() interface 변경한 commit은 아래와 같습니다.
- commit link: https://github.com/naver/arcus-memcached/commit/3ef479be3f351cbdf39b115711e9202cb37aad6c

**Comment by MinWooJin** [comment]
반영 완료 되었습니다.
issue close 합니다.
