### ISSUE TITLE
[persistence] command log buffer, flush thread 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#199]
command logging 에서 사용 될
원형 큐 형태의 log buffer와 log record를 disk에 flush 하는 flush thread를 개발한다.

**Comment by MinWooJin** [comment]
필요한 구조 정리.

LSN 개념 필요
- cmdlog record 마다 fsync 상태를 알고, log buffer의 write 위치, flush 위치, fsync 위치 를 알아야 함
- async mode만 지원 할 경우 buffer 내의 위치 값을 통해 구현이 가능하지만
- sync mode 지원을 위해서는 위치값으로 계산이 복잡해짐(간단하게 생각만 한 상태)
- LSN 을 도입해서 동작하는게 sync mode 처리에 유리할 듯 함.
- LSN 형태 : checkpoint count + file offset

transaction 개념의 구조체 필요
- sync 의 대기 overhead를 줄이기 위한 waiter 관리 필요(waiters, group_commit)
- cmdlog 대상의 현재 상태를 알 필요가 있음(state)
- last_lsn 개념만 있으면 될 듯(lsn).
  - 복구에는 사용 될 필요 없음

log manager 개념의 구조체 필요
- log path
- log buffer 관리
- write 위치
- flush 위치
- fsync 위치
- log lock
  - write, flush, fsync 마다 각각 lock을 가지는 건 필요에 따라

@jhpark816 
LSN 개념이 들어가는게 sync mode 구현이 더 편할 거라고 생각되는데,
검토해 주시면 좋을 것 같습니다.

**Comment by jhpark816** [comment]
예. 어떤 로그까지 flush 된 것을 알아야 하니, LSN 같은 개념이 필요할 것 같네요.
하지만, LSN이 아래중 어떤 것이어야 하는 지는 검토해 봐야 합니다.
- persistent vs. temporary
  - persistent LSN : log disk에 기록되는 LSN
  - temporary LSN: 처리 과정에서 memory에만 두고 활용하는 LSN
- LSN vs. offset
  - offset 만 있어도 되는 지
  - 아니면, filenum과 offset 모두가 있는 LSN 구조이어야 하는 지

**Comment by MinWooJin** [comment]
저는 temporary LSN 이어야 한다고 생각 했습니다.

- persistent vs. **temporary**
  - log disk에 기록하는 이유는 복구에 활용되어야 하기 때문임.
  - ARCUS persistence는 operation 순서대로 log disk에 기록되기 때문에 LSN 으로 비교해서 복구할 필요가 없음.
  - 순차적으로 replay 만 하면 됨.
- **LSN** vs. offset
  - checkpoint 도중 dual logging 에서 log buffer는 하나만 두고 log buffer에 dual logging 해야하는 record의 위치를 모아두는 queue를 두고 구분 할 예정.
  - old + new 동시 쓰기가 진행되어야 할 경우, old의 sequence number를 따라갈 예정임.
  - checkpoint 가 완료되고, new log file에만 쓰여지는 log record와 old 에 쓰여졌던 log record의 fsync 순서 구분이 필요함.

log buffer에 dual logging하는 위치 queue를 두는 방법의 구현이 불가능 할 경우, log buffer를 두 세트 두어야 하기 때문에 offset 만으로 충분할 것 같습니다.

**Comment by MinWooJin** [comment]
처리 완료된 상태로, issue close 합니다.
