### ISSUE TITLE
[persistence] engine config 옵션을 이용한 on/off 기능 구현

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#219]
아래 명령으로 persistence on/off 구현 (default는 off)

```
config persistence [on|off]\r\n
```
- on 또는 off가 주어지면, persistence 기능을 on 또는 off 설정
- on 또는 off가 주어지지 않으면, 현재 persistence 기능의 on/off 여부를 조회

그리고, memcached 구동 옵션을 추가하여 persistence on 시키는 기능 추가
어떤 옵션이 적당한 지는 검토 필요.

**Comment by MinWooJin** [comment]
@computerphilosopher

현재 memcached 에서 사용되는 구동 옵션 목록과 그 의미를 정리해보면 좋겠습니다.

**Comment by computerphilosopher** [comment]
@MinWooJin 

https://jam2in.atlassian.net/wiki/spaces/~102616233/pages/700121096

컨플루언스에 구동옵션을 정리했습니다.

현재 남아있는 옵션은

```
소문자: e, g, o, w, x, y, z

대문자: A, E, F, G, H, K, N, S, T
```

입니다.

**Comment by MinWooJin** [comment]
@computerphilosopher 
현재 남아있는 옵션이 잘못되었습니다.
다시 확인 해주세요.

**Comment by computerphilosopher** [comment]
@MinWooJin 

다시 확인하였습니다.

소문자: i, j, w, y 

대문자: A, F, G, H, J, K, N, O, Q, T, V, W, Y, Z

**Comment by MinWooJin** [comment]
@computerphilosopher 
w 옵션으로 진행하면 좋겠습니다.

**Comment by jhpark816** [comment]
@MinWooJin @minkikim89 
민우 전임.
현재 구동 옵션의 사용에 한계가 있어,
engine config 파일의 적용도 검토해 보았으면 해요.
이 경우, 어떤 모양이 되는가요 ?

참고로, 기존 memcached 옵션은 backward compatibility를 위해 그대로 두고,
engine specific options만을 engine config 파일로 관리해야 할 것 같아요.

**Comment by MinWooJin** [comment]
@jhpark816 
그렇게 하면 더 많은 옵션을 넣을 수 있습니다.
구동은 -e 옵션을 통해 구동하면서, config file 경로를 지정하면 됩니다.
```
-e "config_file=default.config;replication_config_file=replication.config"
```

default.config 파일 안에서, 설정할 옵션을 key=value 형태로 정의해서
initialize_configuration() 안에 추가하면 됩니다.
```
            { .key = "use_persistence",
              .datatype = DT_BOOL,
              .value.dt_size = &se->config.use_persistence },
            { .key = "user_persistnece_mode_async",
              .datatype = DT_BOOL,
              .value.dt_bool = &se->config.use_persistence_async },
```
defualt.config
```
use_persistence=true
use_persistence_mode_async=true
...
```

**Comment by jhpark816** [comment]
@MinWooJin 
default_engine.conf 파일을 만들어 봅시다.

**Comment by jhpark816** [comment]
"config persistence" 명령은 동적으로 on/off 하는 명령이라, 이번 작업에서는 제외시켜 둡시다.

engine config 파일이 존재하면, 거기에 persistence 설정을 추가합시다. 
default는 off로 합시다.

**Comment by MinWooJin** [comment]
engine config 파일에 use_persistence 설정을 추가 했습니다. PR : https://github.com/naver/arcus-memcached/pull/227

현재 issue는 close 하고,
"config persistence" 명령을 이용한 동적 on/off 기능추가 작업이 필요할 때
새로운 issue로 생성 하겠습니다.
