### ISSUE TITLE
[persistence] recovery module 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#221]
recovery 에 필요한 기본적인 사항을 확인하는 recovery module을 개발한다.
실제 recovery 동작은 다른 issue에서 다루고,
해당 issue 에서는 file path 확인 및 설정, file 상태 확인 및 처리 동작을 개발한다.

**Comment by MinWooJin** [comment]
#####recovery 방법#####
- LogRecord header를 read 하면서 commit type 확인(begin/commit)
- commit type이 아니면 log record keep
- commit type을 만나면 begin ~ commit 까지 replay
- begin type을 만나면 failed(cache lock으로 순서가 보장되고 operation 성공 판단이 되면 로깅하기 때문에 발생하지 않아야 함)

**Comment by SuhwanJang** [comment]
file path 확인 및 설정, file 상태 확인 같은 file 준비 작업은 
recovery module 이 아닌 다른 모듈에서 작동하도록 구현하겠습니다.

**Comment by SuhwanJang** [comment]
본 이슈 내용이 반영되었습니다. commit : https://github.com/naver/arcus-memcached/commit/ee6047b0985b02ca31dc9ec29b9ec1b1d777cb37
close 요청드립니다.
