### ISSUE TITLE
[persistence] CAS value 처리 검토

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#229]
CAS 변수의 logging 필요성을 검토한다.

- logging
  - snapshot 완료 시점의 system cas 값 logging 필요하거나
  - 복구 과정에서 마지막 cas값을 system cas 값으로 설정
    - 즉시 operation 처리 기능에서는 사용할 수 없는 방법.
- not logging
  - 재구동 하면, 0부터 다시 시작.

**Comment by jhpark816** [comment]
@MinWooJin 
cas 값은 항상 단조 증가해야 할 이유가 없는 것 같아요.
그래서, 재구동 시에 0 부터 다시 시작해도 될 것 같아요.
어떻게 생각해요 ?

**Comment by MinWooJin** [comment]
@jhpark816 
같은 의견입니다.
cas 값은 logging 대상에 포함시키지 않아도 될 것 같습니다.

**Comment by jhpark816** [comment]
추가 작업이 없으므로, 본 이슈는 close 합니다.

**Comment by MinWooJin** [comment]
@jhpark816 
log record에서 cas value 제거하는 작업을
reopen 해서 처리하는게 좋을 것 같습니다.

**Comment by MinWooJin** [comment]
log record를 이용한 item_apply 모듈을 공통으로 사용하기 위해,
item_apply_kv_link의 cas value는 제거할 수 없음.

persistence log record 생성 시 cas 값을 '0'으로 세팅해서 기록하거나
log record에서 제거하고 item_apply 동작에서 cas argument를 '0'으로 전달하는 방법으로 처리가 가능.

**Comment by jhpark816** [comment]
persistent log record 생성 시에 cas 값을 0으로 재설정할 필요가 있나요 ?
해당 item이 가지고 있던 cas 값을 그대로 하여 생성하면 되지 않나요 ?

**Comment by MinWooJin** [comment]
재구동 시에 0부터 다시 시작할 때 cas 값을 겹치지 않게 하려고 했었는데
다시 생각해보니 그럴 필요가 없네요.
CAS value 부분에서 추가 작업 할 건 없겠습니다. issue close 합니다.
