### ISSUE TITLE
[persistence] recovery log record 재수행 기능 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#243]
recovery를 위한 log record 재수행 기능을 개발한다.

#### recovery 방법 ####
- 방법 1 : log record header에 commit type을 표시하는 방법
  - LogRecord header를 read 하면서 commit type 확인(begin/commit)
  - commit type이 아니면 log record keep
  - commit type을 만나면 begin ~ commit 까지 replay
  - begin type을 만나면 failed(cache lock으로 순서가 보장되고 operation 성공 판단이 되면 로깅하기 때문에 발생하지 않아야 함)
- 방법 2 : n개 log record 마지막에 operation end log record를 생성해서 끼워넣는 방법
  - LogRecord header를 read 하면서 operation end log type을 확인
  - OPERATION_END가 아니면 keep
  - OPERATION_END를 만나면 keep 했던 loc record replay

#### 비교. ####
  - 방법 1은 방법 2에 비해서 operation 마다 log record 수가 1개 적게 생성된다.
  - 방법 2는 방법 1에 비해서 코드 변경이 최소화 되고 깔끔해진다.
  - 방법 1은 commit 시점 설정이 애매하다는 단점이 있다.(명확하게 하지 못할 수 있음 - collection get 도중 delete가 옵션으로 인해 delete 될 경우 어느 시점이 마지막인지 알 수 없을 수 있음)

**Comment by MinWooJin** [comment]
방법 2에 대한 고민이 필요하다.
방법 2의 경우 즉시 재시작 기능에 의해 새로운 log file set가 계속해서 생겨날 수 있다.
(recovery가 완료되기 전 shutdown)
위와같은 현상이 발생하는 원인은 방법 2의 가정이 "OPERATION_END로 operation 단위를 구분하고
재구동 시 같은 cmdlog file에 더 이상 쓰여지지 않는다"로 마지막을 확인하기 때문이다.

END log record에 firstLsn, lastLsn을 추가해서 해결할 수 있지만 모든 log record에 LSN 값이 포함되어야 한다.

**Comment by SuhwanJang** [comment]
본 이슈 내용이 반영되었습니다.
cmdlog_apply commit : https://github.com/naver/arcus-memcached/commit/b1ea2320ebc10ebda91293ea388e3ca79c271673, snapshot_apply commit : https://github.com/naver/arcus-memcached/commit/ee1be79385f8a6963b799be4cf8055837c013787
close 요청드립니다.

**Comment by MinWooJin** [comment]
multiple operation에 대한 logging은 #259 에서 진행 합니다.
기본적으로 recovery는 log record 단위로 재수행 하며,
log file 끝까지 scan하면서 순차적으로 수행합니다.

issue close 합니다.
