### ISSUE TITLE
[persistence] 정상/비정상 종료 후 재시작 복구 기능 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#244]
정상/비정상 종료 상태에서 재시작 복구 기능을 개발 한다.

아래 개발 방법 중 적절한 방법을 확인하여 개발한다.
- 방법 1
  - 정상 종료 일 경우 checkpoint 수행하여 snapshot log file로만 복구
  - 장점 : 복구 시 정상종료에 의해 생성된 snapshot log 만을 이용해 복구 가능
  - 단점 : 종료가 완료되는 데 까지 delay 가 발생
- 방법 2
  - 정상/비정상 종료 복구를 하나의 로직으로 구현
  - 장점 : 종료에 delay가 적음
  - 단점 : 항상 snapshot log + cmdlog 를 이용한 복구로 방법 1에 비해 복구에 걸리는 시간이 증가

**Comment by MinWooJin** [comment]
정상/비정상 종료 복구를 하나의 로직으로 구현하고,
항상 snapshot_log + cmdlog file로 복구하도록 하는게 더 나은 방법으로 생각됨.

정상/비정상 종료가 발생하는 여러 이유 중 log file을 이동시켜야 하는 상황이 발생할 수 있음.
이 때, 정상 종료일 때는 snapshot_log file만 이동시키고, 비정상 종료가 발생했을 땐 snapshot_log + cmdlog file 둘 다 이동시키는 가이드는 일관성이 없다고 생각 됨.

**Comment by MinWooJin** [comment]
@jhpark816 
정산/비정상 종료를 나눠서 처리할 필요가 없다고 생각됩니다.

의견 주시면 정리하고, issue close 하려고 합니다.

**Comment by jhpark816** [comment]
@MinWooJin 
정상 종료 시에, checkpoint 수행하지 않아도 되므로,
정상/비정상 종료를 구분하지 않도록 합시다.

**Comment by MinWooJin** [comment]
정상/비정상 종료 구분을 할 필요가 없다고 판단되어, 기능 개발을 하지 않습니다.

issue close 합니다.
