### ISSUE TITLE
[persistence] 재시작 회복 완료 후 정리 기능 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#245]
재시작 회복이 완료 된 뒤 정리 기능을 개발 필요성을 검토하여 필요 할 경우 기능을 개발한다.

정리 기능이란, 재시작 회복이 완료 된 현재 상태를 checkpoint 하는 기능으로
정리 기능이 없을 경우 복구에 사용된 log file에 새롭게 추가되는 cmdlog를 기록해야 한다.

**Comment by MinWooJin** [comment]
재시작 회복 완료 후 정리 기능은 필요 없다고 판단된다.

회복 중 정상적으로 기록되지 못한 log record가 마지막에 존재 할 경우,
next cmdlog record의 file 기록 위치를
정상적인 log record 기록 위치 다음으로 설정하는 방법으로 제거하도록 되어있다.

즉시 재시작으로 인한 cmdlog record는 recovery file set의
linked cmdlog file로 새로운 파일에 쓰여지기 때문에 문제가 되지 않는다.

재시작 회복 도중 snapshot file size, cmdlog file size를 계산해 checkpoint module에 전달하고
checkpoint module에서 size 비교를 통해 next checkpoint를 결정하도록 한다.

**Comment by MinWooJin** [comment]
@jhpark816 
위와같은 이유로 회복 완료 후 정리 기능은 필요 없다고 판단됩니다.
의견 주시면 좋을 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin
여기서, 정리 기능이라는 것이 cmdlog file 마지막 위치에 존재하는 
incomplete log record를 제거하는 기능을 의미했던 것인가요 ?
이 기능을 의미했다면, 이미 구현되었으므로 본 이슈는 close 할 수 있습니다.

**Comment by MinWooJin** [comment]
@jhpark816 
다른 정리 기능이 있을까요?
체크포인트는 의미가 없기 때문에 언급하지 않았습니다.

**Comment by jhpark816** [comment]
여기 이슈를 민우 전임이 올렸기 때문에, 물어보는 거예요 ?
다른 정리 기능이 필요 없다면, 본 이슈는 close하시죠.

**Comment by MinWooJin** [comment]
issue close 합니다.
