### ISSUE TITLE
[persistence] command logging의 최적화 필요여부 검토.

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#255]
command logging의 구현 형태는 operation의 요청 자체가 아닌
처리 과정에서 로깅이 필요한 부분을 각각 로깅하는 형태이다.

**Comment by MinWooJin** [comment]
최적화 가능한 operation
- KV
  - prepend
  - append
  - incr
  - decr
- Collection
  - insert with create
  - range get with delete [drop]
  - range delete [drop]
  - btree incr/decr

incr/decr는 큰 차이가 없을 것으로 보임.
- prepend, append
  - 추가되는 value만 logging할 수 있어서, log data를 줄일 수 있음
- range get with delete, range delete
  - n개의 element delete log record를 1개의 log record로 표현해 log record 수를 줄일 수 있음.
- 주로 쓰이는 요청이 아니므로, 효과에 대한 검토가 필요.

**Comment by MinWooJin** [comment]
@jhpark816 
위 언급한 operation이 최적화 대상이 될 수 있습니다.
저는 현재 item change log module에서, 저부분 최적화가
코드 변경 대비 큰 의미가 없다고 생각해서 할 필요가 없다고 생각 됩니다.

의견 주시면 좋을 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin 
현재는 중요도가 낮은 최적화 주제로 생각합니다.
향후 여유 있을 시에 최적화 효과를 간단 시험으로 확인하고 나서 판단하는 것이 좋겠습니다.

**Comment by MinWooJin** [comment]
collection range delete or range get with delete operation 수행에서
log record 생성의 최적화를 검토한다.

현재는 range delete 연산이 수행되면서 element 단위로 제거가 될 때 마다
관련 log record를 하나씩 생성해서 기록한다.
예를들어 element 1000개 범위를 delete 할 때 그 범위에 있는 실제 element 수 만큼
log record가 생성된다. 이러한 부분은 최적화 대상이 되고,
range delete 요청을 그대로 기록하는 방식으로 변경하면 많은 양의 log record 수를 줄일 수 있고
복구에서 그만큼 disk IO 횟수를 줄일 수 있다.
(추가로, multiple redo only recovery 구현에서 multiple log record를 메모리에 keep 해놓는데 사용되는
메모리 공간을 fixed size로 운영이 가능하다.)

다른 operation은 효과가 크지 않다고 보인다.

**Comment by MinWooJin** [comment]
command logging의 lrec 생성 최적화를 위해 아래와 같은 작업을 수행하였습니다.
- btree range delete 동작에서 여러 lrec 생성을 단일 lrec로 생성하는 logical delete를 추가
- drop_if_empty 일 때 element delete + item unlink lrec 생성에서 drop flag를 elemet delete lrec에 추가하여 단일 lrec로 생성하도록 수정

PR link : #401 #403 #418 
issue close 합니다.
