### ISSUE TITLE
[persistence] checkpoint disk i/o 에러 처리

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-memcached#256]
checkpoint 모듈에서 disk i/o나 file open 이 실패했을 때 처리 방식 등 에러 처러가 필요

**Comment by SuhwanJang** [comment]
현재 do_chkpt_sweep_files() 에서는 command log file 제거는 되지 않음. 
이 이슈 해결 때 같이 처리 예정.

**Comment by MinWooJin** [comment]
https://github.com/naver/arcus-memcached/pull/280 https://github.com/naver/arcus-memcached/pull/282 https://github.com/naver/arcus-memcached/pull/285 에서 관련 내용이 처리되었습니다.
issue close 합니다.
