### ISSUE TITLE
[persistence] persistence file manager module 개발

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-memcached#258]
persistence 기능 동작에 필요한 file 관련 처리(file path 확인 및 설정, file 상태 확인)를 한다.
engine initialize 때 persistence module 중 가장 먼저 실행되는 모듈이며 다른 모듈(log manager, checkpoint, recovery)에서 정상작동을 위해 파일 관련 사전 준비한다. 

엔진 구동 시에 마지막 파일이 없어졌는 지에 대한 메세지 출력은 복구가 가능한 파일들이 있는 지 상황 판단 후 출력.
ex) 첫번째 일련번호를 가지지 않은 로그 파일만 있는 경우는 어차피 엔진 구동 불가하므로 마지막 파일이 없어졌는지 확인 작업이 불필요함.

**파일 확인 작업**
 - engine failed
    - checkpoint set 중 snapshot이나 log 파일이 없어진 경우 
        - 로그를 출력하고 복구가 가능한 경우라면 로그 출력 후 복구 
           - snapshot 없어진 경우 : 첫번째 일련번호를 가진 로그파일과 이 후의 로그파일들로 복구
           - log 없어진 경우 : snapshot 만 이용해서 복구
    - 중간 로그 파일이 사라진 경우(ex. checkpoint set - cmdlog_1 - cmdlog_3, cmdlog_2 없음).  
 - 로그 파일의 끝에 다음 파일을 가리키는 레코드를 통해 마지막으로 생성된 백업파일이 없어진 것을 판별하고,
   없어진 경우라면 로그만 출력 후 있는 셋트만을 이용해서 복구시킨다.

**파일 생성 작업**
 - 즉시 재시작 모드인 경우 로그 파일 생성. 아닌 경우 이전 로그 파일에 append하여 기록.
   - 명령어가 완전히 기록이 안된 경우 해당 바이트 삭제 후 append.
 - 생성한 로그 파일명에 일련번호를 추가로 붙여준다.
   - single log file name = cmdlog_time_seqnum. ( time 은 last checkpoint time 그대로 사용).
   - checkpoint log file name = cmdlog_time.
   - 일련번호를 통해 중간 로그 파일이 사라지더라도 구분이 가능하다.
 - 이전 로그 파일에 새로 만든 파일을 가리키는 로그 레코드를 append.
 - 파일이 한 개도 없는 경우라면 empty snapshot 을 생성한다.(snapshot_time, cmdlog_time_1)

**파일 제거 작업**
 - 필요한 파일들을 제외하고 제거한다. 

**향후 작업**
 - 파일명만 같은 파일로 바꿔치기 한 경우를 대비해 arcus engine 이 만든 파일인지 확인.
 - 백업 파일이 없어진 경우 구동되지 않도록 하는 구동 옵션 추가
 - 스냅샷 파일 구분 필요(checkpoint or 일반 요청)
    - 현재 스냅샷 파일은 checkpoint 에 의해서만 생성됐다고 가정하고 스냅샷 파일만 있는 경우는 무조건 마지막 파일이 사라졌으므로 메세지 출력.
    - 향후에 일반 요청에 의해 생성된 스냅샷 파일만 여러 개가 있을 수 있고 이에 대해 마지막 파일이 사라졌는 지 탐지가 필요.
 - 사라진 마지막 파일들을 탐지를 못하는 경우
     - 마지막 파일 정보를 이전 파일에 기록하기 전에 엔진이 다운되거나 파일에 abnormal 한 행위(기록 삭제 등)가 있는 경우

**Comment by SuhwanJang** [comment]
persistence file manager algorithm 
![image](https://user-images.githubusercontent.com/28725891/63492904-5f839000-c4f5-11e9-94d7-713fa0de389e.png)

**Comment by SuhwanJang** [comment]
각 기능별 보충설명
make file **set.**
- 항상 파일 셋트를 만들어서 새로 들어오는 커맨드는 cmdlog_nowtime 에 기록됨.
- 이전에 존재하는 log file에 새로 들어오는 커맨드를 append 시킬 경우 다음과 같은 문제가 생김.
  - 즉시 재시작인 경우는 이전 log file 을 복구해야함과 동시에 명령이 쓰여짐.
  - 이전 log file이 명령이 쓰여지다가 engine fail 난 경우 
- snapshot_nowtime 은 사용되지 않는 파일. cmdlog_nowtime 과 짝을 맞춰주기 위해 생성.
- (snapshot head log).logtype 에 스냅샷으로 생성된 파일이 아님을 나타내는 나타내어 복원시에는 
   이전 파일 셋트와 cmdlog_nowtime으로 복구할 수 있도록 함.

find mintime, maxtime
- 체크포인트가 일어나기 전에 엔진이 다운되면 상황이 반복되면 명령이 기록된 여러 cmdlog 파일들이 남게 된다. 이런 여러 개의 cmdlog 파일들과 정상적으로 스냅샷된 파일 셋트를 복구해야되기 때문에 복구에 필요한 파일 범위를 지정해야 해서 두 개의 time 값을 찾는다.

**Comment by SuhwanJang** [comment]
@jhpark816 @MinWooJin 
오전에 논의된 내용을 정리하였습니다. 위 설계내용을 토대로 개발 진행하겠습니다.
보충이 필요한 사항은 코멘트 부탁드립니다.

**Comment by jhpark816** [comment]
@SuhwanJang 

아래 경우에 대한 comment 입니다.
- checkpoint set 중 스냅샷이나 로그 파일이 없어진 경우
   - 현재 스냅샷이 없더라도 이전 스냅샷과 그 이후의 로그 파일들이 있다면, 복구하여 구동해도 됩니다.
- checkpoint set 이 한 개도 없는데 로그 파일들만 있는 경우
   - 첫번째 snapshot인 경우는 empty snapshot이므로, message 출력하고 로그 파일을 바탕으로 복구하여 구동해도 됩니다.
   
즉시 재시작 관련한 comment는 아래와 같습니다.
- 즉시 재시작 기능은 설정에 의해 동작하도록 합시다.
- 내부 flag를 두고, default로 on 으로 설정하고, on인 경우만 동작하도록 합시다.
- 향후, 설정 파일에서 설정할 수 있도록 합시다.
- 여러 로그 파일들이 생기면, 현재 sanpshot 이후에 로그 파일에 쌓인 로그 크기는 로그 파일들의 크기를 합하여 계산하여야 합니다. (이 정보는 체크포인트 수행 조건 검사를 위해 필요)
- 즉시 재시작 기능이 off이면, 기존 로그 파일에 append하여 기록하도록 합시다.

**Comment by SuhwanJang** [comment]
@jhpark816 
- checkpoint set 이 한 개도 없는데 로그 파일들만 있는 경우
  - 첫번째 snapshot인 경우는 empty snapshot이므로, message 출력하고 로그 파일을 바탕으로 복구하여 구동해도 됩니다.

이 경우 없어진 snapshot 이 empty snapshot 였는지 checkpoint snapshot 였는지 구분이 필요하게 되는데, 일관적으로 snapshot 이 없어져서 로그 파일들만 있는 경우 구동을 안 시키도록 하는게 낫지 않을까요?

**Comment by jhpark816** [comment]
@SuhwanJang 

- 일련번호가 첫번째 번호이면, empty snapshot으로 알 수 있을 것입니다.
- Empty snapshot만 없는 경우는 정확히 복구가 가능하므로, 구동하는 것이 맞다고 생각합니다.
  - 구동을 시키지 않게 처리하여도 되긴 하지만,
  - 결국은 운영자가 현재 명령 로그 파일들로 복구하도록 요청하는 것 밖에는 다른 방안이 없을 것입니다.
  - 백업본이 있다하더라도 이는 현재 로그 파일들만 재수행하여 복구하는 것 보다 이전의 시간으로 복구하게 되므로, 백업본을 가지고 복구할 수가 없습니다.

다른 의경이 있으면 언제라도 주세요.

**Comment by SuhwanJang** [comment]
@jhpark816 
향후에 커맨드 로그 기능은 off 이고 명령어로 data snapshot 만 수행이 가능하도록 확장을 고려했을 때
checkpoint set 의 log file 이 없어진 snapshot 만 있는 경우라도 message 출력 후 snapshot file 바탕으로 복구를 해줘도 괜찮다고 생각하는데, 어떻게 생각하시나요?
단, 이 경우에는 다른 로그 파일들은 복구에 사용하지 않음.

**Comment by jhpark816** [comment]
@SuhwanJang 
예. 설명한 대로 복구해야 한다고 생각해요.
조금 더 설명하면,
- snapshot file의 the first record로 snapshot features(or attributes)를 기록해 두면 좋아요.
- checkpoint에 의한 snapshot or 일반 요청에 의한 snapshot을 구분
- 복구 시에 snapshot feature 값에 따라서 명령로그 사용 여부를 결정하면 됩니다.
- 일반 명령에 의한 요청인 경우, file path와 name을 받을 것인데,
   별도 디렉토리 위치이면 아마 snapshot file만 존재하게 될 거예요.
- 이러한 작업도 향후에 고려하면 되고, 이번에는 복구 관점의 snapshot 만을 고려하면 됩니다.

**Comment by SuhwanJang** [comment]
@jhpark816 
예.
- 현재 스냅샷 파일은 checkpoint 에 의해서만 생성됐다고 가정하고 스냅샷 파일만 있는 경우는 무조건 마지막 파일(로그파일)이 사라졌으므로 메세지 출력 후 snapshot 바탕으로 복구 후 구동.

향후에
 - 스냅샷 파일 구분 필요(checkpoint or 일반 요청)
 - 일반 요청에 의해 생성된 스냅샷 파일만 여러 개가 있을 수 있고 이 경우에도 마지막 파일이 사라졌는 지 탐지가 필요.(스냅샷 파일에도 다음 파일을 가리키는 정보 기록이 필요하겠네요.)

**Comment by jhpark816** [comment]
@SuhwanJang 완료된 작업이면, close해 주세요.

**Comment by SuhwanJang** [comment]
본 이슈는 https://github.com/naver/arcus-memcached/pull/294 PR에서 merge 되었으므로 close 합니다.
commit : https://github.com/naver/arcus-memcached/commit/ee6047b0985b02ca31dc9ec29b9ec1b1d777cb37
