### ISSUE TITLE
[persistence] multiple log records의 redo atomicity 보장

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#259]
multiple operation 시작 과 끝에 OPERATION_BEGIN, OPERATION_END log record를 추가한다.

OPERATION_BEGIN, OPERATION_END는 복구 모듈에서 redo하는 범위 결정을 위해 사용되며,
persistence 기능은 모든 log record가 redo only로 동작한다.

log record는 CACHE LOCK에 의해 동시성이 보장되며
log buffer 및 log file에 operation 처리 순서대로 기록이 보장된다.

**Comment by MinWooJin** [comment]
waiter free 직전 이나, waiter_free 내부에서 OPERATION_END log record를 생성 및 기록.
snapshot이 수행중 일 경우 생성된 log record가 n개 일 수 있고 이중 일부만 dual_write 일 수 있다.
따라서 END log record는 항상 dual write 한다.

waiter 관련 조건, 코드가 변경되면 영향받게 됨.

**Comment by MinWooJin** [comment]
item unlink의 logging 조건에 해당하는 연산의 수행 검토 필요.

logging 조건 (unlink cause)
  - NORMAL
  - EVICT
  - STALE

아래 부분 검토 필요.
- do_item_evict : cause EVICT로 item_unlink 호출
- do_item_repair : cause EVICT로 item unlink 호출
- collection_delete_thread 에서 do_item_evict()를 호출하고 있으며, OPERATION_END 가 추가되어야 함.
- do item repair의 경우 ```do_item_mem_alloc()```에서 호출하고 있으며, 사용 함수들을 확인해야 함.

**Comment by MinWooJin** [comment]
do_item_evict
  - waiter alloc
  - item_unlink(EVICT) log record 생성
  - OPERATION_END log record 생성
  - waiter free

do_item_repair
  - waiter alloc
  - do_item_unlink(EVICT) log record 생성
  - OPERATION_ED log record 생성
  - waiter free

coll_delete_thread
  - 내부에서 do_item_evict 호출.
  - item 당 waiter 생성 item_unlink(EVICT) + OPERATION_END 가 write 되는 방식으로 기록됨.

do_item_mem_alloc()
  - 이미 waiter가 생성된 다음 호출될 수 있으며
  - 이 경우 evict 만을 위한 waiter + log record write 가 수행되기 때문에 이전 operation 수행에 문제 없음.

**Comment by MinWooJin** [comment]
@jhpark816 
설계 관련 논의를 현재 issue에서 하는게 좋을 것 같습니다.

multiple operation list
- collection elem insert with create
	- ITEM_LINK log record
	- ELEM_INSERT log record
	- **ITEM_LINK log record만 기록되도 허용 가능**
- collection range get with delete
	- ELEM_DELETE log record * N개 (Set, Map, Btree collection)
	- ITEM_UNLINK log record (drop 설정일 때)
- collection range delete
	- ELEM_DELETE log record * N개 (Map, Btree collection)
	- ITEM_UNLINK log record (drop 설정일 때)

**Comment by MinWooJin** [comment]
@jhpark816 
제 의견은 multiple 연산 중 일부 roecvery가 허용되지 않는 연산은
```sop get <delete>, mop get <delete>, bop get <delete>, mop delete, bop delete```로 총 5개 연산에 대해서만 begin, end logging을 하는게 가장 나은 방법이 될 것 같습니다.

BEGIN, END log record는 persistence 기능만을 위한 추가 로깅으로,
CACHE LOCK 획득 이후 waiter allocate를 위한 code tag와, waiter free를 위한 code tag 안에  넣으면
persistence 를 사용하지 않는 EE version 에서 추가적인 확인 등의 작업은 없을 것 같습니다.
(대신 위 5가지 연산에 대해서 delete 일 때는 항상 begin, end가 들어가야 합니다.)

오프라인에서 논의했던
- range 연산이 모두 수행될 때 까지 별도의 공간에 keep 해 놓고 연산이 완료되면 log buffer에 기록
- 연산이 모두 수행된 뒤 element array를 scan 하면서 log record를 생성

방법들은 CACHE LOCK으로 동작하는 현재 로직에서는 필요 없을 것으로 보이고, 향후에 CACHE LOCK bottleneck 으로 multiple cache lock이 필요 할 때 고민해도 될 것 같습니다.

**Comment by MinWooJin** [comment]
#255 처리로 recovery 시 keep memory 운영 방식이 확정되면 그에 맞춰서 설계한다.

기본적인 동작 방식은, multiple log record의 경우 `[begin, operation1, operation2, end]` 처럼
begin, end log record 사이에 실제 log record를 끼워넣고
복구 시에 begin log record를 만나면 end log record를 만날 때 까지 memory에 keep 해두고
end log record를 만나면 하나의 log record redo 처럼 동작한다.

**Comment by MinWooJin** [comment]
collection delete 에서 drop if empty의 설계에 대한 검토.
방법 1.
  - drop_if_empty 이면, `[begin, operation..., [ccnt == 0 ? unlink operation], end]`로 처리.
  - redo에서 unlink operation이 있으면 expired 가 아닌 상황에서는, item이 없으면 오류로 처리

방법 2.
  - drop_if_empty 이면, operation lrec에 drop flag를 포함해서 생성 및 기록(실제 unlink가 되지 않았더라도)
  - redo에서 `ccnt == 0 && drop` 이면 unlink 하도록 처리
  - 실제 unlink 동작과 일치하지 않음.

위에 대한 검토가 필요한 이유는, element가 delete 된 이후 unlink 하는 순서로 동작하기 때문에 elem delete lrec를 생성하는 시점에서는 unlink 를 알 수 없기 때문임.
log 생성 관점에서 방법 2가 더 나은 방법으로 보임. range elem delete 일 경우에만 begin, end lrec를 생성하면 됨.

**Comment by jhpark816** [comment]
@MinWooJin 
- single elem delete 구분이 되나요 ? 
   - 그러면, ccnt == 1 && single elem delete이면, drop flag 설정
- 그 외의 경우는 방법 1이 나을 것 같다고 의견 전달합니다.
   - range elem delete 경우는 방법 1 사용해야 하므로,
   - 통일된 하나의 방식으로 처리하는 것이 낫지 않나 생각됩니다.

**Comment by MinWooJin** [comment]
@jhpark816 
통일된 하나의 방식으로 처리하는게 애매합니다. btree range delete를 하나의 lrec로 최적화를 고려하면
- list, btree는 single, range delete 구분 없이 하나의 delete lrec만 생성합니다.
- set은 get with delete의 count 옵션 때문에 element 단위로 lrec를 생성합니다.
- map은 numfields 에 따라서 element 단위로 lrec를 생성합니다.

set, map은 방법 1로 처리하는게 더 낫지만, list, btree까지 고려해보면 방법 1의 begin, end가 필요 없어서
방법 2가 더 낫다고 생각했었습니다.
redo 관점에서 실제 unlink 될 때 drop flag를 설정하거나, unlink lrec를 생성하는게 더 맞다고 보시는 건가요?

**Comment by jhpark816** [comment]
single log record만 생성한다면, 방법 2가 가능하겠네요.
그 외의 경우인 set,map만 방법 1로 하고요.

**Comment by MinWooJin** [comment]
set, map도 방법 2로 하는건 어떤가요?

set, map에서 single elem delete일 때는 drop이어도 begin, end를 생성하지 않을 수 있고,
range elem delete 를 호출하는 범위만 begin, end로 감싸면 되서 readability에 더 좋을 것 같다고 생각됩니다.

**Comment by jhpark816** [comment]
예. 그렇게 하시죠.
single elem delete 도 single log record만 생성하는 경우니, 같은 경우로 봐도 됩니다.

**Comment by jhpark816** [comment]
@MinWooJin 
이슈 제목이 정확한 의미를 가지도록 변경하였습니다.

**Comment by jhpark816** [comment]
@MinWooJin @minkikim89 @SuhwanJang 
현재 PR 구현이 items 모듈과 밀겹합되어 있어,
느슨한 결합을 구현하는 방안을 모색하고 있습니다.
이에 대해, 좋은 아이디어 있으면 주세요.

**Comment by jhpark816** [comment]
@MinWooJin 
multiple log records의 read atomicity 보장하는 다른 방안을 제안하니, 검토 바랍니다.

현재 방법은
- 명시적으로 아래 macro 사용하여 begin/end log record 생성하는 방법입니다.
   - CLOG_OPERATION_BEGIN()
   - CLOG_OPERATION_END()
- 개선점
   - CLOG_OPERATON_END()는 성공할 경우에만 호출되도록 그 위치가 수정되어야 합니다.
- 단점은
   - CLOG_OPERATION_BEGIN() 호출 조건을 나타내는 코드가 필요하다.
     코드 관리 측면에서 이러한 호출 조건을 관리하는 것이 부담이다.
   - btree와 map 경우엔, 실제 1개 log record 생성하는 경우이더라도
     begin/end log record가 생성될 수 있다.
     물론, log record 생성이나 redo 부담은 무시할 만큼 작다고 볼 수 있다.
     
제안 방법은
- CLOG_OPERATION_END() 만 수행합시다.
  - log waiter의 lsn != NULL_LSN인 경우만 end log record 생성하여 기록
  - redo 과정에서 log record의 upd type이 multiple log record 생성 타입이면,
    end log record 기록 여부 확인
- 장점은
   - begin 로그 생성 부담과 호출 조건 코드의 관리가 필요 없음.
- 단점은
   - 여전히 1개 log record 생성하더라도 end log record가 기록되어야 함.
   - redo에서 multiple log record 기록하는 upd type인지를 확인해야 하는 부담.

위의 제안은 다른 가능한 방안을 검토 및 논의하기 위하여 제시한 것이며,
그 외에도 좋은 아이디어가 있다면 알려주기 바랍니다.

**Comment by MinWooJin** [comment]
@jhpark816 
먼저 BEGIN/END를 이용하는 이유는 redo failure 판단을 명확하게 하기 위함입니다.
정상적인 multiple lrec는 항상 BEGIN ~ END 사이에 있고,
나머지는 모두 fail 상태라고 보고 처리하는 상태입니다.

제안 방법에서 마지막에 기록된 lrec가 END lrec가 아닌 multiple log record 생성 타입 lrec이라면 (set delete, map delete, bt delete-no logical) 성공인지 실패인지 판단은 어떻게 할 수 있나요?
END log record만 있다면 시작 시점을 알 수 없다고 생각되어서 코멘트 합니다.

**Comment by jhpark816** [comment]
multiple log record 생성 타입이면, 무조건 end log record가 있어야 합니다.
- btree/map elem delete 연산

**Comment by jhpark816** [comment]
@MinWooJin 
begin과 end log record 방식이 log record의 upd type과 무관하게 동작하므로,
더욱 일반화된 구현이라는 장점은 있습니다.
향후, replication/migration도 하나의 고려 사항이 될 수 있습니다.
여기서 충분한 논의를 이끌어내기 위하여, 1차 방안을 제안한 것입니다.

**Comment by MinWooJin** [comment]
@jhpark816 
set elem get with delete, btree elem get, delete, map elem get, delete 이면 항상 생성해야 하는 부분이 걸리네요.

BEGIN/END 방식은 생성 조건 코드 관리 비용과 begin lrec 생성 비용이 요구되지만 multiple lrec를 생성할 가능성이 있는 경우에만 생성할 수 있다는 장점이 있습니다.
두 방식 장단점이 명확한 것 같고, 제 생각에는 BEGIN/END 방식으로 진행하는게 더 낫지 않나 싶습니다.

- 호출조건 관리 비용이 문제가 되는데, 조건 자체는 명확하다고 생각되며 한번 결정되면 바뀌진 않을 것 같아서 macro로 관리하면, 관리 비용이 크다고 보이지 않아서
- 방법을 변경할 필요가 있을 만큼 단점이라고 생각되지 않는 상태입니다.

**Comment by jhpark816** [comment]
위의 2 방법보다 나은 방법은 없을까요 ?

**Comment by jhpark816** [comment]
@minkikim89 검토 바랍니다.

**Comment by minkikim89** [comment]
@jhpark816 
고민해보았는데 언급된 두 가지 방법외에 다른 방법이 떠오르진 않네요.

**Comment by jhpark816** [comment]
@MinWooJin @minkikim89 
2 방법을 다시 정리하므로, 코멘트 있으면 주세요.

- BEGIN/END log record 기록 방법일 경우, 아래 수정 필요
   - MACRO 위치 조정
     예를 들어, do_btree_elem_delete() 안에 둡시다.
      - single bkey 조회인 경우는 필요 없고,
      - bkey range 조회인 경우에 두는 것이 명확할 것 같습니다.
      - 그러면, BEGIN 생성 조건이 모두 같아집니다.
   - logical bt log 관련 수정
      -  현재는 모듈 간의 cross 호출이 있어, 이를 제거하면 좋겠습니다.
      - 2가지 방안이 있습니다.
      - 하나는 BEGIN macro에 인자 추가하여 btree 연산에 대한 begin 임을 구분하여 처리.
         - item_clog 모듈에서 BEGIN log record 생성 여부를 결정
     - 다른 하나는 logical bt log 여부를 items 모듈의 btree 코드에서 관리.
     - 후자가 나은 것 같습니다.
- END만 기록하는 방법
   - 향후 cache tag 기능이 들어가면, N개 연산이 atomic하게 처리되어야 합니다.
      - 문제는 N개 연산이 한번의 cache locking으로 모두 수행되는 것이 아니라
        각 연산을 수행할 때마다 cache locking을 수행할 수 있습니다.
      - 결국, atomicity를 보장해야 할 연산에서 생성한 log record들이
        연속적으로 기록되지 않을 수 있습니다.
      - 이에 대한 recovery 방안도 검토 바랍니다.
   - DB 에서도 보통 마지막에 commit log record를 기록합니다.
      - 하나의 log record만 기록할 경우는 log record header에 flag를 두어
         1개 log record로 commit한다고 표시하여 commit log record 생성을 피할 수 있음.
   - 이 방식에서 flag 설정이 자연스러운 구현인지 검토 필요하고,
      나도 고민해야 할 듯..

**Comment by jhpark816** [comment]
@MinWooJin
우선 BEGIN/END 모두 기록하는 방식으로 가시죠.
단, 위에 수정 사항만 깔끔하게 정리하여 반영하죠.

**Comment by MinWooJin** [comment]
@jhpark816 
BEGIN/END 기록하는 방식으로 리뷰 반영 했습니다.

N개 연산이 atomic하게 처리되어야 하는 부분은
EE의 transaction table을 두고 처리하는 로직을 검토해볼 수 있을것같은데
같은 key에 대해 다른 transaction이 동작중일 때 어디까지 제공을 할것인지에 따라
난이도가 달라질 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin 
아래가 의미하는 바를 좀 더 구체적으로 알려주면 좋겠어요.

----------
range log 생성 여부는 BEGIN 에 조건을 argument로 넘기면 될 것 같습니다.

gen_logical_btree_delete_log flag는 items 모듈에 남겨두는게 나을 것 같고,
waiter에 gen_logical_btree_delete_log flag를 추가해서 bt delete에서 waiter allocate 
하고 설정하고 cmdlogmgr 모듈에서 사용하는게 좋을 것 같습니다.

아래 세가지 정도를 검토고, waiter에 flag 추가를 선택 했습니다.
- cmdlogmgr init에 gen_logical_btree_delete_log 를 넘겨 설정하여 사용
- waiter에 flag 추가하여 구분
- waiter에 upd type을 추가하여 updtype으로 LOGICAL DELETE를 구분

**Comment by MinWooJin** [comment]
@jhpark816 
아래와 같이 하려고 합니다.
- range log 생성 여부
  - 현재 : 조건 검사 후 BEGIN log record 생성 macro 호출
  - 변경 : BEGIN log record 생성 macro에 (rcnt, ccnt) 를 넘겨주고, cmdlogmgr module에서 조건 검사
- logical log 생성 여부
  - 현재 : items module에 gen_logical_btree_delete_log flag를 두고 items module 코드에서 검사 후 생성
  - 변경 : items module에 gen_logical_btree_delete_log flag는 그대로 두고, waiter alloc 할 때 설정값을 전달해서 waiter에 flag를 추가하고, BT_DELETE, BT_LOGICAL_DELETE, BEGIN log record 생성 할 때 참고하여 생성 여부 결정

**Comment by jhpark816** [comment]
@MinWooJin 
"range log"라는 말에 혼돈이 왔네요.
코드를 보지 않은 상태로, 의견을 남깁니다.

- begin, end 로그 레코드는 현재 PR 대로 두는 것이 좋을 것 같습니다.
   - 여러 로그 레코드가 생성될 수 있다는 조건을 확인 후에 begin 로그 레코드를 생성하는 것이므로,
      그 의미를 나타내는 조건 코드가 같이 있는 것이 좋을 것 같습니다.
- logical log는
   - persistence에만 사용하고 replication 등에서는 아직 사용하지 않습니다.
     그래서, persistence에 직접 연관된 cmdlogmgr 모듈에 두는 것의 검토를 요청 했던 것입니다.
   - gen_logical_btree_delete_log는 global flag이므로 현재로는 상수로 설정해 두면 됩니다.
      - waiter 마다 개별 설정하지 않아도 될 것 같습니다.
   - cmdlogmgr에서 gen_logical_btree_delete_log에 따라
      - begin/end/elem_delete 로그를 생성할 지와 elem_delete_logical 로그를 생성할 지를 구분
      - 문제는 single elem delete는 gen_logical_btree_delete_log 무관하게 생성해야 하는 데
         single elem delete 경우를 구분할 수 있어야 가능할 것 같습니다.

**Comment by MinWooJin** [comment]
https://github.com/naver/arcus-memcached/pull/419 PR 반영 완료 되었습니다.
issue close 합니다.
