### ISSUE TITLE
[persistence] persistence configuration 반영.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#268]
아래의 persistence configuration 반영

- data_path
   - 반드시 지정 필요
- logs_path
   - 반드시 지정 필요
- async_logging
   - default는 false (sync_logging)
   - true로 설정하면 async logging 수행
   - 구현 코드에서는 sync_logging 플래그를 구도 구분

**Comment by SuhwanJang** [comment]
본 이슈 내용은 반영되었습니다. commit : https://github.com/naver/arcus-memcached/commit/4e3fcc8c6b82088bf95281d249907a30f267d09b
close 요청드립니다.

**Comment by MinWooJin** [comment]
persistence configuration
- data_path
  - 지정을 필요로 하며,
  - 지정 하지 않을 경우 구동된 direcotry에서 "ARCUS-DB" directory 확인 및 생성
- logs_path
  - 지정을 필요로 하며,
  - 지정 하지 않을 경우 구동된 direcotry에서 "ARCUS-DB" directory 확인 및 생성
- async_logging
  - 설정하지 않을 경우 sync logging
  - 필요시에만 true로 설정

PR links : #273 #277 #280 

issue close 합니다.
