### ISSUE TITLE
[persistence] flush queue 개선.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#269]
현재 고정 개수의 flsuh queue 사용 중인 상태입니다.

dual write 기능이 추가됨에 따라 아래 이슈가 있습니다.
- 어떤 고정 크기로 정해야 하는 지 ?
- 어떤 고정 크기로 정하더라도 그 크기가 상당히 클 것 같습니다.

이 이슈를 검토해 주세요.

다른 대안으로는
- 동적 할당된 flush request 를 사용
- 동적 할당하더라도 4K 단위로 memory allocate하고 
- free 상태의 flush request list 유지하여 사용

**Comment by MinWooJin** [comment]
이부분은 향후 검토하기로 하고 넘어갔던 부분은데, 해당 issue에서 처리하면 될 것 같습니다.
고정크기는 맞지 않을것으로 생각했고, 동적 할당된 flush request list를 두고
모자라면 더 할당하는 식으로 하려고 계획만 하고 있는 상태입니다.

**Comment by MinWooJin** [comment]
- flush reqeust는 동적할당 하여 사용
- 동적할당 할 경우 used_list를 별도로 유지해야 하며, 순서에 대한 handling이 필수적임.
  - flush reqeust 가 생성된 순서로 file write를 해야 함.
- 고정 크기는 클라이언트가 요청하는 key의 bucket 접근을 예측할 수 없어 사용이 불가할 듯
  - 최악의 경우에는 snapshot bucket 증가에 맞춰서 prev, next bucket을 번갈아가며 요청하면 요청된 명령 수 만큼 flush request가 필요하게됨.

**Comment by MinWooJin** [comment]
#271 의 처리 결과에 따라 flush queue 개선 작업이 필요 없을 수 있으므로 현재 상태에서 대기하고,
결과 분석 후 필요 시 처리하도록 한다.

**Comment by MinWooJin** [comment]
flush request queue 에 link 유지하는 필드 추가 없이, flush queue가 가득 찼을 때 handling을 검토

방법 1.
  - buff_write 에서, flush request queue가 부족하면 flush 후 write 하도록 handling
  - 고정 크기 flush queue를 사용할 수 있고, dual write에서 부족할 때만 worker thread가 직접 flush 하도록 하는 방법(log buffer handling과 동일)

**Comment by MinWooJin** [comment]
flush request queue를 grow 하는 방식은,
flush request queue의 역할에 비해 많은 복잡성을 가지게 되므로, 고정크기 를 사용하도록 변경

flush queue size = log buffer size / sizeof(LogHdr)*2 - 최소 log record size
flush queue 는 내부에 uint32 size의 data만 가지고,
MSB는 dual_write를 나타내는 bit로 사용, 나머지 31 bit는 flush 할 양(max 16MB로 문제 없음)으로 사용.

**Comment by MinWooJin** [comment]
반영 완료 되었습니다.
issue close 합니다.
