### ISSUE TITLE
[persistence] cmdlog buf write 성능 비교.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#271]
현재의 설계는 아래와 같다.
- buffer 공간을 따로 둔다.
- memcpy로 buffer 공간에 기록해 둔다.
- flush thread에 의해 해당 파일로 write() 작업을 수행한다.

아래와 같이 구현할 경우 성능은 어떻게 될까요 ?
- log record 생성한 worker thread가 직접 log file로 write 한다.
- 이 경우, memcpy 작업은 생략할 수 있다.
- value 크기가 큰 경우에 이득이 있을 수 있다.

**Comment by MinWooJin** [comment]
@jhpark816 
log record를 생성한 worker thread가 직접 log file로 wirte하는 방식으로 변경되면
logbuf module은 제거할 수 있고, log_flush_lsn 와 log_fsync_lsn만을 유지하면 됩니다.
logbuf의 lock도 모두 제거할 수 있고, CACHE LOCK으로 동작 가능합니다.

대신 기존에 buffer에 n번 memcpy하고, 한번 file wirte를 수행했던 로직이
n번 file write로 변경되게 됩니다.

성능은 1번의 n번 memcpy + 1번 large buffer file wirte와
n번 file write 의 성능을 비교해야 할 것 같은데 쉽게 감이 오진 않는 상태입니다.
실제 수정을 통해 비교해 봐야 감이 올 것 같습니다. 진행 할까요?

**Comment by jhpark816** [comment]
@MinWooJin 
나도 검토해 보고 나서, 의견 줄께요.

**Comment by jhpark816** [comment]
@MinWooJin 
참고로, 직접 file write한다면
cache lock 잡은 상태에서 수행해야 하는 부담이 있긴 해요.

아래 부분에 관련하여 정확하게 구현할 지 있는 지와 
code tag로 두 방식의 구분이 쉽게 가능한 지를 검토해 주세요.
- checkpoint 도중의 log record write 동작
- sync logging 구현
- 그 외 관련된 사항.

그래서, 문제가 없다고 한다면, code tag 또는 config 설정으로 
두 방식 중 하나를 선택하는 형태로 구현해야 할 것 같습니다.

현재로는 어떤 방식이 더 유리할 지를 판단하기가 어려운 상태인 데,
구현해서 테스트해 보는 방법 밖에는 없겠죠 ?

**Comment by MinWooJin** [comment]
@jhpark816 
cache lock 잡은 상태에서 write 수행으로, 직접 file write가 성능이 안좋습니다.

- 직접 file wirte 로직
  - item_clog module에서 log record 생성
  - cmdlogbuf module 에서 log record module 호출
  - writev 로 link log write
- buffer wirte 로직
  - item_clog module에서 log record 생성
  - cmdlogbuf module에서 log record module 호출
  - buffer에 link log memcpy
  - flush thread가 이후 write

처리량은 아래와 같은 차이가 발생합니다.
  - 직접 file write
    - 약 50,000 rps (set operation) [hubble link](http://1.255.51.181:8088/d/iwHczXvWz/03-arcus-operations?from=1571200442587&to=1571202272485&var-ensemble=jam2in-m001:7289&var-service_code=test&var-node=jam2in-m001:11911&var-node_host=jam2in-m001&var-node_port=11911&orgId=1)
    - cpu 사용량 220%  정도 [hubble link](http://1.255.51.181:8088/d/AaYRbERmk/02-arcus-stats?from=1571200442587&to=1571202272485&var-ensemble=jam2in-m001:7289&var-service_code=test&var-node=jam2in-m001:11911&var-node_host=jam2in-m001&var-node_port=11911&orgId=1)
  - buffer write
    - 약 75,000 rps (set operation) [hubble link](http://1.255.51.181:8088/d/iwHczXvWz/03-arcus-operations?var-ensemble=jam2in-m001:7289&var-service_code=test&var-node_all=%7Bjam2in-m001:11911%7D&var-node_host_all=jam2in-m001&var-node_port_all=11911&var-exclude_slave=None&orgId=1&from=1571193441162&to=1571194732547)
    - cpu 사용량 250% 정도 [hubble link](http://1.255.51.181:8088/d/AaYRbERmk/02-arcus-stats?from=1571193465422&to=1571194720627&var-ensemble=jam2in-m001:7289&var-service_code=test&var-node=jam2in-m001:11911&var-node_host=jam2in-m001&var-node_port=11911&orgId=1)

검토 요청 드립니다.

**Comment by jhpark816** [comment]
@MinWooJin 
OK. 수고했어요.

구현 코드를 code tag로 구분하고 disabled 상태로 PR 보내주면,
구현 리뷰를 간단히 진행할게요.

**Comment by MinWooJin** [comment]
@jhpark816 
정확하게 모든 모듈을 수정하지 않았고, log record write 동작에 영향을 주지 않도록만 수정 한 상태입니다.

link log record에 한정해서 테스트를 위해서 아래와 같이 수정 후 진행 했습니다.
https://github.com/MinWooJin/arcus-memcached/commit/af7c139b8b9f84df6276608f435bf50ccc18259a disabled 상태로 persistence branch에 추가 할 필요가 있나요?
추가가 필요하다면 전체 log record write를 수정 해야 합니다.

**Comment by jhpark816** [comment]
주어진 아래 코드로 충분히 리뷰 가능해요.
- https://github.com/MinWooJin/arcus-memcached/commit/af7c139b8b9f84df6276608f435bf50ccc18259a

**Comment by jhpark816** [comment]
@MinWooJin @SuhwanJang 
buffer write 방식이 direct write 방식보다 성능이 좋으므로, 현재 방식을 그대로 유지하겠습니다.
@MinWooJin 테스트하느라 수고했습니다.
