### ISSUE TITLE
[persistence] cmdlogbuf module의 lsn 검토

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#279]
persistence의 lsn은 filenum + offset 으로 구성되어 있으며,
cmdlogbuf module에서 유지하는 lsn은 아래와 같다.
- nxt_write_lsn
  - log record가 log buffer에 기록되는 순서에 따라 부여되는 lsn으로, log record 생성 시 부여되며 log size 만큼 offset을 증가
  - checkpoint에 의한 snapshot이 완료되면 filenum 증가.
- nxt_flush_lsn
  - log record를 log file에 write 하는 순서에 따라 증가하는 lsn으로, log record wirte 시 log size 만큼 offset 증가
  - checkpoint에 의해 snapshot 완료 지점까지 write 되면 filenum 증가.
- nxt_fsync_lsn
  - log file의 fsync 상태를 알려주는 lsn
  - fsync() 를 수행하면, nxt_fsync_lsn = flush_lsn(fsync 호출 당시 nxt_flush_lsn)으로 설정

위 설정 중 checkpoint에 의한 snapshot 완료 시점의 filenum 증가로
정확하게 log record가 log file에 쓰여진 위치를 나타내지 않는 상태이다.
현재 persistence 동작에서는 단조증가와 snapshot 완료 구분 조건만 만족하면 되기 때문에
정확한 lsn 유지를 위한 추가적인 작업 보다는, 간단한 작업으로 위 조건만 만족하도록 한 상태이다.

향후 정확한 lsn 유지 필요성을 검토하고, 필요하다면 수정하도록 한다.

**Comment by jhpark816** [comment]
현재의 persistence 동작에서는 단조증가와 snapshot 완료 구분만 하면 되지만,
정확한 lsn을 유지하는 것이 코드 이해와 향후에도 필요할 것 같아 수정하였습니다.
- commit link: https://github.com/naver/arcus-memcached/commit/f269d80aab12c3532e967f9066935ad8b26a8bfb
