### ISSUE TITLE
[persistence] expire time 관련 검토 및 처리

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#286]
arcus-memcached(server)의 time은 process가 생성 된 시점부터 증가하도록 되어있고,
hash item의 expire time은 server 시간 + expire time으로 기록된다.
이 시간을 그대로 사용 할 경우 재시작 시 server 시간이 ```0```으로 설정되어
expire time 기준 persistence recovery가 정확하게 수행될 수 없는 상태이다.

recovery를 고려해 server 시간 관리 및 log record에 기록될 expire time을 검토 및 처리한다.

**Comment by MinWooJin** [comment]
recovery 동작에서 expired 된 item을 즉시 unlink 시키지 않도록 해야 한다.
cmdlog replay 시, insert/update 성격의 redo 동작에서 item not found 상태이면
expired 된 상태와 실패 상태에 따라 처리를 다르게 해야 한다.

동작 방법
  - expired 된 item을 unlink 시키지 않고
  - expired 상태인 상태로 hash table에 남겨둔다
  - recovery
    - item link 성격의 log record의 경우 exp time비교를 통해 skip 한다.
    - collection update 성격의 log record의 경우 expired 되었으면 skip 한다.
  - recovery 완료
    - hash table full scan을 통해 expired 된 item을 unlink 하거나
    - 그대로 두고, 다음 접근에서 delete 되도록 한다

**Comment by jhpark816** [comment]
위 설명을 좀 더 상세화시켜 주면 좋겠어요.
- expired item을 unllink 시키는 것은 언제하는 가 ?
   - 복구에서 apply한 item이 expired 된 경우로 한정된 얘기인가 ?
- "exp time 비교를 통해 skip한다." 의미는 ?
   - exp time 비교해서 어떤 상황은 skip이고 다른 상황은 어떻게 하는 지 ?
- 기타 등등

그리고, redis persistence에서 expire 처리는 어떻게 하나요 ?

**Comment by SuhwanJang** [comment]
@jhpark816 
redis 의 time 은 absolute unix time 방식을 사용하고, expiretime 역시 absolute unix time 으로 기록합니다.
아이템의 TTL 을 한 시간으로 설정하면, 아이템의 expiretime 은 X(current unix time) + 1H 로 기록되고, 엔진 재시작이 X + 1H 이후에 구동이 된다면, 해당 아이템을 expire 처리합니다.

**Comment by MinWooJin** [comment]
- redis persistence 에서 expire 관련 다른 처리를 할 필요가 없습니다.
  - redis는 collection도 create insert 성격으로 처리됩니다.
  - 예를들어, list collection 에서 element 5개 있는 상태로 TTL이 지났다면
  - 다음 RPUSH operation에 의해 element 1개 TTL -1 (no ttl 상태)로 create & insert 됩니다.
- expired item을 unlink 관련 부분
  - 복구 동작 중에 apply 한 item이 expired 된 경우 unlink 시키지 않는다.
  - set / create 명령은 expire time을 비교해서 지나지 않았으면

**Comment by SuhwanJang** [comment]
https://github.com/naver/arcus-memcached/commit/f74e278bcd2f732282583025252996de3ad15f7d 에서 해결되었습니다.
- exptime 을 기록 시에는 절대시간으로 변환하고, 복구 시에는 상대시간으로 변환합니다.
- exptime 을 절대시간으로 기록하기 때문에 엔진 구동 시점이 exptime 보다 뒤면, 이미 expired 되었기 때문에 해당 로그 레코드는 복구하지 않습니다.
