### ISSUE TITLE
[persistence] getnowtime() 오류

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#295]
checkpoint time을 checkpoint 식별자로 사용하는 상황에서
현재 사용하는 checkpoint time은 아래 코드와 같이 적합하지 않다.
시간, 분, 초의 값만 사용하고 있어, 동일한 값이 만들어 질 수 있다.
단조증가하는 unique한 값이 만들어져야 한다.

```
static int getnowtime(void)
{
    int ltime;
    time_t clock;
    struct tm *date;

    clock = time(0);
    date = localtime(&clock);
    ltime = date->tm_hour * 10000;
    ltime += date->tm_min * 100;
    ltime += date->tm_sec;
    return(ltime);
}
```

**Comment by SuhwanJang** [comment]
Merged(PR : https://github.com/naver/arcus-memcached/pull/301 / commit : https://github.com/naver/arcus-memcached/commit/3759a49d8fb0e9388e9150364235c4a7ad881a97)
년, 일, 월 값을 checkpoint time 에 추가로 더하여 unique 하도록 변경.

**Comment by SuhwanJang** [comment]
issue 가 해결되었으므로 close 요청드립니다.
