### ISSUE TITLE
[persistence] wait 없는 next checkpoint 수행 검토

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#303]
checkpoint를 수행하기 위한 cmdlog file size 확인 로직을 검토한다.

현재 cmdlog file size 확인 로직은 아래와 같다.
  - log_gl.log_buffer.dw_end == -1 확인
  - dw_end == -1 이면 file size = cmdlog file size
  - dw_end != -1 이면 file size = 0
    - dw_end != -1 로 file size가 0 이면 checkpoint min logsize 조건에 만족하지 못해 checkpoint 수행하지 않음

dw_end는 이전 checkpoint가 snapshot 완료된 시점의 flush request queue index로, log flush thread는 dw_end까지 log buffer를 flush 하면서 dual_write가 설정되어 있으면 write하고 설정되어 있지 않으면 skip하기 위해 사용한다.

- dw_end 설정되어 있는 상태에서 checkpoint가 수행되면 dual write logic이 수행되면서
- 이전 checkpoint에 의해 dual_write 설정되어 있는 flush request queue index(dw_end) 까지 flush 되면
  - dual write logic이 종료되거나
  - 잘못된 dual write가 수행되는 문제가 발생한다.

dw_end가 설정되어 있는 상태에서 next checkpoint가 수행되어도 문제가 발생하지 않도록 수정이 가능한지 검토 및 수정한다.

**Comment by jhpark816** [comment]
@MinWooJin 
본 이슈가 문제되는 이슈인지를 재 확인해 주세요.

**Comment by MinWooJin** [comment]
@jhpark816 
현재 이슈는 문제가 있어서 수정하려는 이슈는 아닙니다.

이슈를 생성했던 이유는, checkpoint 마무리 작업을 기다리지 않고
다음 checkpoint를 수행할 수 있도록 하자는 의견 때문이었습니다.

현재 코드를 기반으로 설명하면, checkpoint thread가 아래처럼 dual write finished를 기다리는 로직이 있습니다.
```
            /* check previous checkpoint is completed. */
            if (cs->prevtime != -1) {
                if (cmdlog_file_dual_write_finished()) {
                    /* remove previous checkpoint files. */
                    if (do_chkpt_remove_files(cs, cs->prevtime) < 0) {
                        need_remove = true;
                    }
                    cs->prevtime = -1;
                }
            }
            if (cs->prevtime == -1 && do_checkpoint_needed(cs)) {
                logger->log(EXTENSION_LOG_INFO, NULL, "Checkpoint started.\n");
                ret = do_checkpoint(cs);
                if (ret == CHKPT_SUCCESS) {
                    logger->log(EXTENSION_LOG_INFO, NULL, "Checkpoint has been done.\n");
                } else {
                    logger->log(EXTENSION_LOG_WARNING, NULL, "Failed in checkpoint. "
                                "Retry checkpoint in 5 seconds.\n");
                    if (ret == CHKPT_ERROR_FILE_REMOVE) need_remove = true;
                }
            }
            elapsed_time = 0;
        }
```

위 로직에서 이전 checkpoint 완료를 기다리지 않고,
checkpoint 조건(파일 크기)을 만족하면 즉시 checkpoint를 할 수 있도록 하는게 가능하고,
필요한지를 검토하기 위함 입니다.

**Comment by jhpark816** [comment]
@MinWooJin 

- prev file이 close 되기까지 긴 시간이 필요하지 않습니다.
   따라서, next checkpoint 수행 조건이 된 시점에서 prev checkpoint가 완료되지 않을 확률은 지극히 낮습니다.
- prev file이 close된 이후에 next checkpoint 수행하는 것이
  관련 모듈의 구조체 관리와 수행 로직의 복잡성을 낮출 수 있습니다.

위의 이유로 본 이슈는 처리하지 않도록 하겠습니다.
