### ISSUE TITLE
[persistence] snapshot head log record 정의

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-memcached#308]
스냅샷 파일에 기록될 snapshot head log record 를 정의한다.

- 스냅샷 파일이 생성되자 마자 기록되는 로그 레코드.
- 스냅샷 파일은 head, tail 로그 레코드를 둘 다 가지고 있어야 valid.
- persistence 모듈이 스냅샷 파일을 이용하여 동작시에 필요한 메타 데이터를 정의
   - engine_name(ARCUS-default_engine)
   - persistence version(compatibility)
   - checkpoint time(최신 파일 선택 및 파일 유형 구분)
        - -1 : normal file, > 0 : checkpoint file.

**Comment by SuhwanJang** [comment]
```
 /* Snapshot File Head Record */
 typedef struct _Snapshot_head_data {
     uint8_t host_eglen;
     uint8_t persistence_version;
     bool    checkpoint_file;
     char    reserved[15];
     int64_t created_time;
     char    data[1];
 } SnapshotHeadData;

 typedef struct _snapshot_head_log {
     LogHdr           header;
     SnapshotHeadData body;
     char             *host_engine;
 } SnapshotHeadLog;

```

**Comment by jhpark816** [comment]
@SuhwanJang 
head log 구조를 아래와 같이 합시다.

```
 /* Snapshot File Head Record */
 typedef struct _Snapshot_head_data {
     char  engine_name[32];
     int64_t checkpoint_time;
     uint32_t persistent_version;
     uint32_t dummy;
 } SnapshotHeadData;
```

그리고, snapshot file link를 유지할 생각인가요 ?

**Comment by SuhwanJang** [comment]
@jhpark816 
snapshot file link (dummy field)는 우선 메인 개발 완성 후에 검토 후 추가하도록 하겠습니다.

**Comment by SuhwanJang** [comment]
본 이슈는 다음과 같은 이유로 close 합니다.
테일 로그 레코드에 필요한 정보를 담을 수 있음에도 불구하고 추가로 헤더 로그 레코드를 정의하는 것은
불필요하며 복잡성만 증가시킨다.
engine_name, persistence_version 정보를 테일 로그 레코드에 넣도록 하고,
checkpoint_time 은 로그 레코드에 기록을 하지 않고 기존대로 파일명에서 parsing 해서 얻어온다.
