### ISSUE TITLE
[persistence] 최적화 대상 분석을 위한 성능 시험

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#312]
현재 persistence 동작 중 최적화 대상이 되는 부분을 분석하기 위한
성능 시험을 진행하고, 성능 결과 및 대상을 분석한다.

대표적으로 확인 할 성능은 아래와 같다.
- 캐시 아이템 수에 따른 스냅샷 성능 확인
- 데이터 사이즈에 따른 스냅샷 성능 확인
- 스냅샷과 명령로깅 작업이 일반 요청 처리에 미치는 영향도 확인
- disk type(HDD, SSD)에 따른 스냅샷과 명령로깅 성능 차이 확인

**Comment by jhpark816** [comment]
담당자: @SuhwanJang @computerphilosopher

**Comment by MinWooJin** [comment]
@computerphilosopher @SuhwanJang
시험했던 내용을 정리 해주세요.

**Comment by computerphilosopher** [comment]
# 테스트 개요

## 사전 테스트 

- 최대 부하를 줄 수 있는 테스트 옵션 찾기 - thread 10, clients 40일 때 평균적인 부하가 제일 높은 것으로 판명.
- 메모리 사용량이 2gb 내외일 때 스냅샷이 발생하는 아이템 갯수 찾기 - 1300만개를 삽입하면 스냅샷이 발생하는 것으로 판명  

## 본 테스트

- no persistence: persistence 기능을 켜지 않은 상태의 성능 측정
- no snapshot (command logging only): persistence 기능을 켠 상태에서, snapshot 최소 파일 크기를 매우 크게 잡아  snapshot이 발생하지 않도록 한 테스트. 
- snapshot: snapshot이 발생하도록 한 테스트. 

테스트 진행 순서는 다음과 같다. 

1. 사전 테스트에서 찾은 스냅샷이 일어나는 아이템 갯수를 사전 삽입
2. 약 8gb 만큼 아이템 삽입
3. getset 연산에서 스냅샷이 발생하도록 유도하고 성능 측정 

# 테스트 사양

## 장비

- 클라이언트: m002 (8vCPU, 16GB mem, 50GB HDD) 
- 서버 1: m001 (8vCPU, 16GB mem, 50GB HDD)
- 서버 2: m003 (8vCPU, 16GB mem, 50GB SDD)

## memcached 설정 

/home/persistence/arcus/server/memcached -E /home/persistence/arcus/server/.libs/default_engine.so -X /home/persistence/arcus/server/.libs/syslog_logger.so -X /home/persistence/arcus/server/.libs/ascii_scrub.so -e config_file=/home/persistence/arcus/server/engines/default/default_engine.conf -d -v -r -R5 -U 0 -D: -b 8192 -m8192 -p 11911 -c 2000 -t 6 -z 10.33.19.248:7291 

# 테스트 결과 요약

처리량과 레이턴시 모두  no persistence > no snapshot > snapshot 순으로 성능이 하락한다. 성능의 하락은 HDD를 사용하는 장비에서 더욱 크고, 연산에서 set의 비중이 높을 수록 크다. 

스냅샷 중 최저점의 성능은 스냅샷 직전에서 30퍼센트 정도 감소한다. 

## throughput 비교

### 1차 테스트 

#### m001

|                | preset             | Set                | getset              |
| -------------- | ------------------ | ------------------ | ------------------- |
| no persistence | 91116.14           | 84893.64           | 87904.97            |
| no snapshot    | 80819.79 (-11.3 %) | 78417.78 (-7.62 %) | 85774.20 (-2.42 %)  |
| snapshot       | 74861.26 (-7.62 %) | 71606.82 (-9.51 %) | 84727.695 (-1.22 %) |



#### m003

|                | ** preset**        | **set**            | **getset**          |
| -------------- | ------------------ | ------------------ | ------------------- |
| no persistence | 99042.02           | 94328.6            | 97820.585           |
| no snapshot    | 97940.51 (-1.11 %) | 88004.44 (-6.7 %)  | 97252.995 (-0.58 %) |
| snapshot       | 90307.56 (-7.79 %) | 79851.04 (-9.26 %) | 97176.26 (-0.07 %)  |



### 2차 테스트



#### m001

|                | ** preset**         | **set**            | **getset(avg)**     |
| -------------- | ------------------- | ------------------ | ------------------- |
| no persistence | 91362.14            | 82051.35           | 87985.485           |
| no snapshot    | 81648.58 (-10.63 %) | 77261.87 (-5.83 %) | 84798.995 (-3.62 %) |
| snapshot       | 74377.94 (-8.9 %)   | 72421.37 (-6.26 %) | 85224.195 (+0.5 %)  |



#### m003

|                | ** preset**        | **set**            | **getset(avg)**     |
| -------------- | ------------------ | ------------------ | ------------------- |
| no persistence | 100213.34          | 90862.85           | 97703.905           |
| no snapshot    | 97709.21 (-2.49 %) | 86847.93 (-4.41 %) | 97417.465 (0.29 %)  |
| snapshot       | 90526.73 (-7.35 %) | 80691.8 (-7.08 %)  | 95796.875 (-1.66 %) |



### 3차 테스트

#### m001

|                | ** preset**       | **set**            | **getset(avg)**    |
| -------------- | ----------------- | ------------------ | ------------------ |
| no persistence | 89053.22          | 82665.87           | 88368.145          |
| no snapshot    | 80775.7 (-9.29 %) | 76614.14 (-7.32 %) | 85200.96 (-3.58 %) |
| snapshot       | 75381.06 (-6.67%) | 72157.6 (-5.81 %)  | 85088.79 (-0.13 %) |



#### m003

|                | ** preset**        | **set**            | **getset(avg)**     |
| -------------- | ------------------ | ------------------ | ------------------- |
| no persistence | 104453.9           | 91471.92           | 101057.405          |
| no snapshot    | 101578.2 (-2.75 %) | 87202.6 (-4.66 %)  | 98288.19 (-2.74 %)  |
| snapshot       | 89991.03 (-11.4 %) | 80256.09 (-7.96 %) | 96729.735 (-1.58 %) |



# 스냅샷 전후 성능 비교

- getset 연산 도중에 발생한 스냅샷 기준

- snapshot 발생 횟수는 총 5회로 모든 테스트에서 같다. preset 에서 두 번, set에서 2번, getset에서 마지막으로 한 번 발생 



### 1차 테스트 

#### m001

|                   | ** 직전** | **snapshot 도중 최저점** | **직후** |
| :---------------- | :-------- | :----------------------- | -------- |
| ops/sec (get)     | 67.1 K    | 44.4 K (-33.83%)         | 67.8 K   |
| ops/sec (set)     | 16.8 K    | 11.1 K (-33.92%)         | 16.9 K   |
| CPU usage         | 194       | 166 (-14.43%)            | 224      |
| RX bytes(eth 0)   | 5.64 Mil  | 4.4 Mil (-21.98%)        | 6.66 Mil |
| TX bytes(eth 0)   | 7.81 Mil  | 6.09 Mil (-22.02%)       | 9.22 Mil |
| heartbeat latency | 2.17 ms   | 11.76 (+441%)            | 6.23 ms  |
| utils             | 0         | 100                      | 23       |

- 5번째 스냅샷 
- item count: 70 M
- memory stack: 7.3 G
- 소요 시간: 2분 34초.

#### m003

|                   | **직전**  | **snapshot 도중 연산량 최저점** | **직후**  |
| :---------------- | :-------- | :------------------------------ | :-------- |
| ops/sec (get)     | 76.7 K    | 56.2 K (-26.72%)                | 78.9 K    |
| ops/sec (set)     | 19.2 K    | 14.1 K (-26.56%)                | 19.7 K    |
| CPU usage         | 160       | 136 (-15%)                      | 177       |
| RX bytes(eth 0)   | 7.35 Mil  | 5.54 ms (-24.62%)               | 7.77 Mil  |
| TX bytes(eth 0)   | 10.17 Mil | 7.67 ms (-24.58%)               | 10.75 Mil |
| heartbeat latency | 1.6 ms    | 9.63 ms (+501.87%)              | 3.21 ms   |
| util              | 0         | 100                             | 0         |

- 5번째 스냅샷
- item count: 70 M
- memory stack: 7.3 G
- 소요 시간: 2분 32초.



### 2차 테스트

#### m001  

|                   | **직전** | **snapshot 도중 최저점** | **직후** |
| :---------------- | :------- | :----------------------- | :------- |
| ops/sec (get)     | 63.7 K   | 44.2 K (-30.61%)         | 72.5 K   |
| ops/sec (set)     | 15.9 K   | 11.0 K (-30.81%)         | 18.1 K   |
| CPU usage         | 189      | 160 (-15.34%)            | 235      |
| RX bytes(eth 0)   | 6.28 Mil | 4.35 Mil (-30.73%)       | 7.14 Mil |
| TX bytes(eth 0)   | 8.7 Mil  | 6.03 Mil (-30.68%)       | 9.88 Mil |
| heartbeat latency | 3.59 ms  | 12.35 ms (+244.02%)      | 2.6 ms   |
| utils             | 0        | 100                      | 0        |

- 5번째 스냅샷

- item count: 70 M

- memory stack: 7.3 G

- 소요 시간: 2분 39초

  

#### m003

|                   | **직전** | **snapshot 도중 최저점** | **직후**  |
| :---------------- | :------- | :----------------------- | :-------- |
| ops/sec (get)     | 80.1 K   | 55.5 K (-30.71%)         | 78.2 K    |
| ops/sec (set)     | 20 K     | 13.9 K (-30.5%)          | 19.6 K    |
| CPU usage         | 153      | 129 (-15.68%)            | 168       |
| RX bytes(eth 0)   | 7.92 Mil | 5.46 Mil (-31.06%)       | 7.3 Mil   |
| TX bytes(eth 0)   | 10.96 Ml | 7.56 Mil (-31.02%)       | 10.12 Mil |
| heartbeat latency | 2.19 ms  | 10.81 ms (+393.6%)       | 3.26ms    |
| utils             | 0        | 100                      | 23        |

- 5번째 스냅샷
- item count: 70 M
- memory stack: 7.3 G
- 소요 시간: 2분 30초



### 3차 테스트

#### m001  

|                   | **직전** | **snapshot 도중 최저점** | **직후** |
| :---------------- | :------- | :----------------------- | :------- |
| ops/sec (get)     | 65.4 K   | 40.3 K (-38.37%)         | 63.2 K   |
| ops/sec (set)     | 16.4 K   | 10.1 K (-38.41%)         | 15.8 K   |
| CPU usage         | 219      | 151 (-31.05%)            | 219      |
| RX bytes(eth 0)   | 6.48 Mil | 4.04 Mil (-37.65%)       | 6.05 Mil |
| TX bytes(eth 0)   | 8.97 Mil | 5.62 Mil (-37.34%)       | 8.38 Mil |
| heartbeat latency | 5.57 ms  | 13.64 ms (+144.88%)      | 7.19 ms  |
| utils             | 0        | 100                      | 0        |

- 5번째 스냅샷 
- item count: 70 M
- memory stack: 7.3 G
- 소요 시간: 2분 39초

#### m003

|                   | **직전**  | **snapshot 도중 최저점** | **직후** |
| :---------------- | :-------- | :----------------------- | :------- |
| ops/sec (get)     | 76.8 K    | 57.2 K (-25.52%)         | 72.1 K   |
| ops/sec (set)     | 19.2 K    | 14.3 K (-22.02%)         | 18.0 K   |
| CPU usage         | 145       | 142 (-2.06%)             | 165      |
| RX bytes(eth 0)   | 7.53 Mil  | 5.63 Mil (-25.23%)       | 7.03 ms  |
| TX bytes(eth 0)   | 10.42 Mil | 7.8 Mil (-25.14%)        | 9.73 ms  |
| heartbeat latency | 2.62 ms   | 9.67 ms (+269.08%)       | 0.81 ms  |
| utils             | 0         | 88                       | 0        |

- 5번째 스냅샷
- item count: 70 M
- memory stack: 7.3 G
- 소요 시간: 2분 28초
