### ISSUE TITLE
[persistence] 용어 변경: Snapshot Tail Log => Snapshot Done Log

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#318]
기존의 snapshot head와 tail log 방식에서 head log 필요성이 없어진 상태이므로,
snapshot tail log를 snapshot done log로 용어 변경하는 것이 좋겠습니다.

**Comment by SuhwanJang** [comment]
Merged commit : https://github.com/naver/arcus-memcached/commit/9569af79d11605c9f586ec680fc9e0510d42efc4
용어 변경하였습니다. (Snapshot tail -> Snapshot done)
