### ISSUE TITLE
[persistence] setattr log record 내의 정보 기록 순서 검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#322]
setattr log record에 기재할 variable data는 2가지가 있다.
- key string
- max bkey range.

key string 이후에 max bkey range 기록하는 것이 자연스러운 순서로 보인다.
순서 조정에 대해 검토하고, 필요하면 수정해 주세요.

**Comment by SuhwanJang** [comment]
@jhpark816 
setattr 에서 data 기록 순서를 바꾼다면,
item link 시에도 같은 순서로 기록하는 것이 일관성이 있어보입니다.

```
 /* Item Link Log Record */
 /* KV :         header | lrec_item_common | cas            | key + value
  * Collection : header | lrec_item_common | lrec_coll_meta | key + value(\r\n)
  * BTree :      header | lrec_item_common | lrec_coll_meta | maxbkeyrange | key + value(\r\n)
  */
```

두 log record 모두 key string 을 먼저 기록하도록 변경하겠습니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
수환 사원은 어떤 순서가 맞다고 생각하나요 ?

**Comment by jhpark816** [comment]
@SuhwanJang 
기존 순서를 그대로 유지합시다.

**Comment by SuhwanJang** [comment]
@jhpark816 
key 를 먼저 기록하면 아이템 타입 구분없이 같은 위치에 key 가 존재하므로 redo 와 print 쪽에서 구현상의 이점을 가져올 수 있지만, key 를 기록하기 전에 메타 데이터들을 먼저 기록하는 게 자연스러워 보입니다.

**Comment by SuhwanJang** [comment]
@jhpark816 
구현상의 이점이 미미하므로 기존 순서를 유지하는 것이 맞는 것 같습니다.
issue close 해주세요.
