### ISSUE TITLE
[persistence] 일시적인 스냅샷 기능 개발

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#324]
일시적인 스냅샷 기능을 제공하기 위한 개발이 필요하다.
EE snapshot과의 merge 를 검토하여 설계한다.

**Comment by MinWooJin** [comment]
현재 snapshot command 정리.
```
snapshot start <mode> [<prefix>] <filepath>\r\n
snapshot stop\r\n

*mode : rcount
```

**Comment by jhpark816** [comment]
아래와 같은 snapshot command를 추가하였습니다.

```
snapshot start <mode> [<prefix>] <filepath>\r\n
snapshot stop\r\n

*mode : key, data
```

commit link: https://github.com/naver/arcus-memcached/commit/445a47d4133a70f06305284542a1da251e087f06

**Comment by jhpark816** [comment]
@SuhwanJang 정상 동작하는 지를 확인 바랍니다.

**Comment by SuhwanJang** [comment]
정상 동작을 확인하였으므로 이슈 close 하겠습니다.
