### ISSUE TITLE
[persistence] do_log_buff_flush()에서 last_flush_flag 제거.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#333]
do_log_buff_flush()에서 flush_all = true인 경우,
- fend가 가리키는 flush request에서 nflush가 0보다 크면, 즉, flush해야 할 데이터가 있다면,
- fend 포인터를 이동시킨 후에 flush 작업을 수행하도록 하여 last_flush_flag를 제거합시다.

코드가 간결해 질 것으로 예상합니다.

**Comment by MinWooJin** [comment]
@jhpark816 
flush request queue enhance 작업 #269 에서
같이 수정 될 예정입니다.
해당 issue 반영이 완료되면 같이 close 하겠습니다.

**Comment by MinWooJin** [comment]
반영 완료 되었습니다.
issue close 합니다.
