### ISSUE TITLE
[persistence] log record file write 실패에 대한 handling

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#339]
현재 log file wirte 실패 확인 및 handling 아래와 같이 assertion fail down 으로 처리되는 상태이다.
```
    /* The log data is appended */
    ssize_t nwrite = disk_byte_write(logfile->fd, log_ptr, log_size);
    if (nwrite != log_size) {
        logger->log(EXTENSION_LOG_WARNING, NULL,
                    "log file(%d) write - write(%ld!=%ld) error=(%d:%s)\n",
                    logfile->fd, nwrite, (ssize_t)log_size,
                    errno, strerror(errno));
    }
    assert(nwrite == log_size);
```

file write 실패 가능성에 대해 정리하고, 보다 명확한 error handling이 필요하다.

**Comment by MinWooJin** [comment]
기본적인 방향은 재시도 + 최종적으로 persistence 종료로 진행 예정

재시도는 일시적으로 그 순간에만 write 실패가 발생할 가능성을 고려하여 3 ~ 5번 이내로 시도하고,
persistence 를 정리하는 작업을 수행한다.

persistence 정리 작업은 flush thread와 worker thread & 다른 thread 간의 locking과 밀접하게 관련이 있으며, dead lock이 발생하지 않도록 고려하여 설계한다.
예를들어 worker thread가 cache lock 상태로 log flush lock을 wait하고 flush tread는 flush lock 상태로 item clog module의 logging 종료를 위해 cache lock을 wait 하는 상황을 발생시킬 수 있다.

persistence 정리 작업은 worker thread와 log flush thread 모두 수행할 가능성이 있다.
worker thread가 수행 할 경우 cache lock + log flush lock 상태에서 정리 작업 필요를 확인하게 되고,
flush trhead가 수행 할 경우 log flush lock 상태에서 정리 작업 필요를 확인하게 된다.

**Comment by jhpark816** [comment]
아래 사항을 확인 바랍니다.
- squall 엔진에서의 처리 방식
- 다른 DBMS 엔진은 어떻게 하는 지를 2 관점에서 조사
   - 구글링 (정보가 있을 지는 모름)
   - 다른 오픈소스 코드 확인

**Comment by MinWooJin** [comment]
@jhpark816 
- squall 엔진에서의 처리 방식
  - squall 엔진도 persistence와 마찬가지로 assert(nwrite == size) 로 assertion fail 되도록 되어있는 상태입니다.
- 다른 DBMS 엔진
  - 구글링 및 오픈소스 코드 확인 중이고 현재 issue에 정리 하겠습니다.

**Comment by MinWooJin** [comment]
@jhpark816 
다른 제품과 squall 엔진의 처리 방식을 살펴보았고, 최종적으로 아래와 같이 했으면 합니다.
- disk failure policy 설정 가능하도록 제공
  - default : stop
  - persistence_stop : cache 용도 설정으로, read/write 연산 모두 처리하고 persistence 제공만 stop
  - read_only : persistence_stop + write 성격의 operation은 처리 불가로 전달하고, read만 가능하도록

단계별로 진행하는게 좋을 것 같고 출시 전에 어디까지 정리할지는 잘 판단되지 않네요.
- 현재는 실패 처리를 하나의 함수에서 하도록 refactoring, stop 제공
- persistence_stop 제공
- read_only 제공

의견 주시면 좋을 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin 

- 현재로는 shutdown 처리합시다.
- Shutdown 처리하더라도 아래와 같이 보다 정교하게 처리합시다.
   - write() 실패하면 그 즉시 shutdown하는 것은 좋은 구현이 아닙니다.
   - write() 요청을 요구한 상위 작업이 있을 건데, 그 작업의 semantic에 따라 오류 처리합시다.
      - 예를 들어, backup 파일을 생성하는 거라면, 실패 처리하고 오류 리턴하면 됩니다.
      - 요청 처리에서 더 이상 오류 처리가 불가하여 더 이상 서비스 제공하는 것이
         의미 없다고 판단되면, 그 시점에 오류 메세지를 남기고 assert()로 종료시킵시다.
- persistence stop, read only, switchover 등은 다음 단계에서 고민합시다.

**Comment by MinWooJin** [comment]
@jhpark816 
- backup 파일을 생성하는 도중 write 실패될 경우 실패처리 후 오류를 리턴 하도록 되어 있습니다.(checkpoint 실패 처리)
- cmdlog 파일로 write는 persistence 제공 관점에서 더 이상 서비스 제공하는것이 의미 없다고 판단됩니다.

현재 단계에서 cmdlog file write 실패의 경우에서만 shutdown 하게 되어있으므로, 현재대로 두고
다음 단계에서 추가적인 처리방안을 고민하면 될 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin 
OK.
- backup 파일 생성 시의 실패는 오류 처리하도록 되어 있네요.
- 그 외는 cmdlog file에 flush하는 경우인데, 현재로는 shutdown 처리하는 걸로 하겠습니다.
