### ISSUE TITLE
[persistence] recovery 정상 동작을 위해 engine time 설정 필요.

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-memcached#342]
복구 동작은 engine time 설정 전에 수행되기 때문에 
log apply 시에 engine current time 을 참조하는 곳에서 문제가 발생한다. 

코어 모듈 호출 순서는  engine_load & init() -> stats_init() -> clock_handler() 이므로,
복구 동작을 수행하는 engine_init() 에서는 engine current time 이 초기화가 안된 상태이므로 값이 0 이다.
이로 인해 log apply 시에 문제가 생기는데,
대표적으로 flush_all redo 에서
config->oldest_live(=unsigned) = svcore->get_current_time() - 1 로 설정하는 곳에서 
underflow 가 발생하여 실질적인 flush 작업이 동작하지 않는다.
뿐만 아니라 item redo 시에 current time 을 참조하는 items 모듈에서 문제가 생길 수 있다.

해결방안으로 stats_init() -> clock_handler() -> engine_load & init() 순서로 변경하면 
복구 동작에 문제가 없고, 다른 모듈에서도 문제는 없어 보인다.

```
 static void stats_init(void)
 {
     mc_stats.daemon_conns = 0;
     mc_stats.rejected_conns = 0;
     mc_stats.quit_conns = 0;
     mc_stats.curr_conns = mc_stats.total_conns = mc_stats.conn_structs = 0;

     /* make the time we started always be 2 seconds before we really
        did, so time(0) - time.started is never zero.  if so, things
        like 'settings.oldest_live' which act as booleans as well as
        values are now false in boolean context... */
     process_started = time(0) - 2;
     stats_prefix_init(settings.prefix_delimiter, disable_stats_detail);
 }
 static void clock_handler(const int fd, const short which, void *arg)
 {
....
     set_current_time();
 }

 static void set_current_time(void)
 {
     struct timeval timer;

     gettimeofday(&timer, NULL);
     current_time = (rel_time_t) (timer.tv_sec - process_started);
 }
```

```

**Comment by jhpark816** [comment]
@SuhwanJang 
`develop` 브랜치로 수행 순서 변경 PR을 올려주세요.

**Comment by SuhwanJang** [comment]
merged commit : https://github.com/naver/arcus-memcached/commit/a0299903d0580e5020016d878e98242f13ef1a3d
코어 모듈 수행 순서를  engine_load & init() -> stats_init() -> clock_handler()  에서
stats_init() -> clock_handler() -> engine_load & init() 순서로 변경.

**Comment by jhpark816** [comment]
@SuhwanJang 
`persistence` 브랜치에 반영하였습니다.
