### ISSUE TITLE
[persistence] 가이드 문서 제작 및 정리

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#346]
Persistence 가이드 문서 제공을 위해 제작 및 정리한다.

**Comment by SuhwanJang** [comment]
Persistence 가이드 문서를 Medium 에 작성하였고 ( https://medium.com/jam2in/arcus%EC%97%90%EC%84%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%98%81%EA%B5%AC-%EB%B3%B4%EC%A1%B4%EC%9D%84-%EC%9C%84%ED%95%9C-persistence-%EA%B8%B0%EB%8A%A5%EC%9D%98-%EA%B0%9C%EC%9A%94%EC%99%80-%EC%82%AC%EC%9A%A9%EB%B2%95-61468e4cf546 )
위 글을 https://github.com/naver/arcus-memcached/wiki 에 링크해두었습니다.
