### ISSUE TITLE
[persistence] 메모리 부족 시 eviction 기능 disable 필요성 검토

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#348]
메모리가 부족 할 경우 가장 오래전에 접근했던 아이템 부터 evict 시키는 방식으로
공간을 확보해 현재 요청된 변경 연산을 수행하고 있다.

항상 데이터를 보관하기 위한 목적으로
persistence를 사용 할 경우 위와같은 evict 정책이 맞지 않을 수 있다. 
eviction 기능의 disable 필요성을 검토하고, 필요하다면 적용 방법에 대한 설계를 진행한다.

**Comment by MinWooJin** [comment]
eviction enable/disable은 설정에 따라 동작할 수 있도록 한다.
각 설정에 따라서 추가적인 동작은 아래와 같다.

- enable
  - memory 부족 시 LRU 에 따라 eviction
  - LRU_UPDATE log record 생성
- disable
  - memory 부족 시 요청 실패 & 에러 return

**Comment by jhpark816** [comment]
ARCUS persistence인 경우는 eviction 기능을 disable하는 것이 좋다고 생각합니다.
REDIS persistence에서는 어떤가요 ?

**Comment by SuhwanJang** [comment]
redis persistence 는 eviction 기능과 무관하게 동작합니다.
아이템 eviction 시에 아이템을 지우는 명령으로 로깅됩니다.

**Comment by jhpark816** [comment]
@MinWooJin @SuhwanJang 
REDIS와 같은 방식으로 한다면, eviction 기능이 있어야 하겠네요.
Redis는 random eviction이지만,
ARCUS는 LRU 기반 eviction이기 때문에, LRU_UPDATE log record 생성하여 반영할 필요도 있구요.

**Comment by SuhwanJang** [comment]
@jhpark816 
참고로, redis 는 eviction policy 설정에 따라 LRU 기반 eviction 도 지원합니다.
LRU 기반 eviction 이어도, LRU_UPDATE 와 같이 변경 연산 외에 로그 기록은 하지 않습니다.

**Comment by MinWooJin** [comment]
@jhpark816 
결국엔 선택할 수 있도록 제공하고, 사용자가 선택하는게 좋겠습니다.

redis는 collection을 포함해 기본적으로 정책이 item이 없으면 만들어서 처리합니다.
ARCUS의 collection 처리와 동일하게 갈 수는 없겠습니다.

- ARCUS Persistence disable eviction
- ARCUS Persistence enable eviction + LRU_UPDATE log record 생성

**Comment by jhpark816** [comment]
@MinWooJin @SuhwanJang 
여러 facts들을 들어보니, 현재는 아래 1개 방안이 좋은 것 같습니다.
- enable eviction
- no LRU_UPDATE log record 생성

memlimit 설정이 동일하다면,
recovery 후에 evict되는 item이 달라질 수 있어도 큰 차이는 없을 것으로 보입니다.
memlimit 설정이 기존보다 작다면,
당연히 추가의 items이 evict되어야 하고요.

**Comment by jhpark816** [comment]
@SuhwanJang @MinWooJin  
정리합니다.
- `-M` 구동 옵션으로 eviction 기능을 on/off할 수 있습니다.
- 동적으로 eviction 설정을 변경하는 것은 제공하지 않겠습니다.

질문이 있습니다.
- persistence에서 현재 LRU update를 logging 하나요 ?

**Comment by SuhwanJang** [comment]
@jhpark816 
LRU update logging 안하고 있습니다.

**Comment by jhpark816** [comment]
@SuhwanJang @MinWooJin 
아래와 같이 현재 상태를 정리하고, 본 이슈는 close 합니다.

- `-M` 구동 옵션으로 eviction 기능을 on/off할 수 있습니다.
- 동적으로 eviction 설정을 변경하는 기능은 현재로선 제공하지 않겠습니다.
   - 향후 요구가 있을 시에 제공하도록 하겠습니다.
- persistence에서 현재 LRU update에 대해 logging하지 않습니다.
   - 참고로, replication에서는 logging 합니다.
