### ISSUE TITLE
[persistence] log_waiter 리스트 관리 개선.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#354]
log_waiter 엔트리들의 최대 수는 memcached 구동 옵션인 connection 수에 의존하며,
connection 수는 운영자가 설정하며, 매번 달라질 수 있습니다.

현재 log_waiter 엔트리의 최대 수는 대략 4000개 정도로 고정되어 있으며,
connection 수가 많은 경우 log_waiter 엔트리 부족으로 오류가 발생할 수 있습니다.
아래와 같이 변경이 필요합니다.
- 최대 수의 초기 값은 1000 정도로 적당한 크기여야 하고,
- log_waiter 엔트리가 부족하면 grow 기능으로 log_waiter 엔트리를 추가 확보해야 합니다.

그리고, 이를 위한 자료 구조 변경은
 - log_waiter 엔트리를 일정 크기(예, 100 or 1000)개 확장해야 하고,
 - 이러한 메모리 공간을 chunk라 하면, 이러한 chunk list를 유지하여 향후에 free할 수 있어야 하며,
- log_waiter 엔트리들의 used_list와 free_list는 포인트(메모리 주소)로 연결하여야 합니다.

**Comment by jhpark816** [comment]
참고로, 이 작업은 sync logging 코드가 merge된 이후에 진행해 주세요.

**Comment by SuhwanJang** [comment]
merged commit : https://github.com/naver/arcus-memcached/commit/90b41078d85f650d11115bdbcc7e3d0e8ea1e17a
-log_waiter 엔트리는 4KB 크기로(127개) 확장
-log_waiter 엔트리들의 free_list는 포인트(메모리 주소)로 연결
