### ISSUE TITLE
[persistence] 초기화되지 않은 persistence 모듈을 final 시키는 문제

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-memcached#356]
현재 persistence 모듈들이 초기화되지 않은 상태에서 final 하는 경우가 있어서 logger 를 사용할 때 abort() 가 납니다. (default_engine.conf 에 등록된 백업 디렉토리가 없는 경우, 엔진 종료)
각 모듈에서 final 시에 initialized 여부 확인이 필요합니다.

현재 구현
```
destroy_engine() {
  if (persistence) cmdlog_mgr_final();
}
cmdlog_mgr_final()
{
    chkpt_thread_stop()
    cmdlog_buf_flush_thread_stop()
    chkpt_final()
    cmdlog_buf_final()
    cmdlog_waiter_final()
}
chkpt_thread_stop(void)
 {
    // stop thread
     logger->log(EXTENSION_LOG_INFO, NULL, "[FINAL] checkpoint thread stopped.\n"); //abort
 }
chkpt_final()
{
    pthread_mutex_destroy(&chkpt_anch.lock);
    pthread_cond_destroy(&chkpt_anch.cond);
    logger->log(EXTENSION_LOG_INFO, NULL, "CHECKPOINT module destroyed\n"); //abort
}
```
변경한다면,
```
chkpt_final()
{
  if (!chkpt_anch.initialized) {
     return
  }
  do_chkpt_thread_stop();
  pthread_mutex_destroy(&chkpt_anch.lock);
  pthread_cond_destroy(&chkpt_anch.cond);
  logger->log(EXTENSION_LOG_INFO, NULL, "CHECKPOINT module destroyed\n"); 
}
```
thread_stop 을 final() 내부로 넣는 것이 좋아보입니다. (cmdlog_buf_flush_thread 도 마찬가지.)

**Comment by jhpark816** [comment]
각 모듈별로 initalized(or 유사한 변수)를 두어 초기화 여부를 표시하고,
초기화한 경우만 final 작업을 수행하면 됩니다.

- items.c, assoc.c slabs.c 파일 참고하세요.
- 극단적으로 logger != NULL이면 초기화된 상태로 봐도 될 것인데,
   가능하면 의미있는 변수(initialized or 다른 변수)를 사용하세요.

**Comment by SuhwanJang** [comment]
commit : https://github.com/naver/arcus-memcached/commit/be0f048b56dde7da01d9b03bbdc22f3dbfcb7abc
각 모듈별로 initialized 를 두어 초기화 여부를 확인하고, final 작업을 수행합니다.
