### ISSUE TITLE
[persistence] snapshot stop 명령으로 인한 체크포인트 동작 중단

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-memcached#362]
사용자 요청으로 수행되고 있는 스냅샷 동작을 중단시키기 위한 stop 명령이 
체크포인트 스냅샷 동작을 중단시킬 수 있다.

stop 명령으로 인해 체크포인트 스냅샷 동작이 중단되지 않도록 해야 한다.

**Comment by jhpark816** [comment]
@SuhwanJang Good observation..

**Comment by SuhwanJang** [comment]
commit : https://github.com/naver/arcus-memcached/commit/6bae2d05c0f50dd1b67cc42b97e7114860eaea7f
stop 요청이 들어왔을 때 스냅샷 모드가 체크포인트 스냅샷 모드라면 stop 되지 않도록 합니다.
