### ISSUE TITLE
[persistence] log_file 구조체에서 prev_fd 제거.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#366]
Persistence 구현을 위한 log_file 구조체에서 prev_fd 필요성이 없어 보인다.
prev_fd의 필요성을 검토하고, 필요 없다면 제거합니다.

**Comment by jhpark816** [comment]
cmdlog_complete_dual_write() 함수에서 prev_fd가 유효해 질 수 있는 데,
prev_fd 대신에 local 변수로, close해야 할 fd를 보관해 두고,
cmdlog_complete_dual_write() 함수의 마지막에서
log_flush_lock 해제한 직후에  해당 fd를 바로 close하면 될 것입니다.

**Comment by minkikim89** [comment]
https://github.com/naver/arcus-memcached/pull/396에서
merge 되었으므로 close 합니다.
