### ISSUE TITLE
[persistence] Log record의 redo 실패 처리 변경 필요

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#369]
현재 persistence의Log record의 redo 실패(해당 key를 가진 item이 없음)는
log출력 후 실패를 return 해서, recovery가 종료되도록 처리되고 있다.

log record가 생성되는 많은 이유 중 eviction에 의해 생성 될 경우
복구 과정에서 해당 item 이 이미 eviction 동작에 의해 delete되었을 수 있다.
(get 연산이 없으므로, unlink log record 생성 당시 LRU와 같지 않은 상태임)

log record redo 동작에서 key를 가진 item이 없을 경우 log만 출력하고,
성공을 return하여 recovery 가 동작할 수 있도록 변경이 필요하다.

**Comment by SuhwanJang** [comment]
@MinWooJin 
위 이슈는 https://github.com/naver/arcus-memcached/commit/a55d34bcc04337502b9d06acf98e4982f4eb915c 에서 해결되었습니다. 
- 재수행이 OOM 으로 인해 실패된 경우가 아니라면, 복구 동작을 중단시키지 않고 에러 메세지만 출력해준 후 다음 로그 레코드를 복구.

close하겠습니다.
