### ISSUE TITLE
[persistence] sync logging에서 동시성 제어 최적화.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#370]
현재 구현은 fsync 동안에 fd 변경을 방지하기 위하여, fd 변경 시에 log_fsync_lock을 획득한다.
이 방식의 설계에서 miss한 부분이 하나 있다.
- log file의 fd 변경은 시스템의 정상 종료 외에 checkpoint 작업에서 이루어진다.
- 이러한 fd 변경 작업은 log_flush_lock 잡은 후에 log_fsync_lock을 잡으며, 
  두 lock을 획득한 상태에서 수행된다.
- checkpoint thread에 의한 fd 변경이 fsync locking에 의해 지연되더라도
  checkpoint 작업만 지연되는 거라 생각하여 문제 없다고 생각하였다.
- 하지만, 문제는 log_flush_lock을 잡은 상태에서 지연되기 때문에 
   log flush thread의 flush 작업  또한 지연될 수 있다는 것이다.

결국, 최대 성능을 얻기 위하여, log write 작업과 log flush 작업이 lock waiting에 의해 지연되는 것을 방지하여야 한다.

**Comment by jhpark816** [comment]
새로 제안하는 동시성 제어 방법은 아래와 같고, 검토 바랍니다.

- log_file 구조체에서 각 fd에 대한 2가지 상태 플래그(bool 타입)를 둔다.
   - fsync_ongoing : fsync 진행 중인 상태
   - close_request : close 요청된 상태
- log_file_sync() 작업은 아래와 같다.
   - log_flush_lock 잡은 상태에서
      - nxt_flush_lsn을 local 변수로 얻고
      - fsync 대상 fd의 fsync_ongoing = true 설정 후 그 fd를 local 변수로 얻는다.
   - log_fsync_lock 잡은 상태에서
      - local 변수로 얻은 fd에 대해 실제 fsync 작업을 수행하고,
      - local 변수로 얻은 nxt_flush_lsn을 nxt_fsync_lsn에 설정한다.
   -  다시 log_flush_lock을 잡고
      - 해당 fd의 fsync_ongoing = false로 설정한다.
      - 만약 fd의 close_request == true이면, close 작업을 수행한다.
- cmdlog_complete_dual_write() 작업은 아래와 같다.
   참고로, prev_fd 필드를 사용하지 않는다고 가정한다.
   - 성공이면
      - fd와 next_fd를 교체한다. (size, fsync_ongoing, close_request 모두 교체한다.)
      - next_fd를 close한다.
      - 만약, fsync_ongoing이면 close_request = true로 설정하여 close를 위임한다.
   - 실패이면,
      - next_fd를 close한다.
      - 만약, fsync_ongoing이면 close_request = true로 설정하여 close를 위임한다.
- cmdlog_file_open() 작업은 무관하다.
   - open한 file의 fsync_ongoing과 close_request를 모두 false로 초기화한다.
- cmdlog_file_close() 작업은
   - close 시에 fsync_ongoing이면 close_request = true로 설정한다.

**Comment by minkikim89** [comment]
@jhpark816 
말씀하신대로 작업하면 되겠습니다.
작업하여 PR하겠습니다.

**Comment by jhpark816** [comment]
@minkikim89 
현재의 성능을 먼저 확인하고, 본 이슈는 그 이후에 처리하죠.

**Comment by jhpark816** [comment]
@minkikim89
동시성 제어 최적화에 대해 질문이 있어요.
- 장점은 어느 정도 된다고 생각하나요 ?
- 단점은 어떤 것이 있나요 ?

**Comment by MinWooJin** [comment]
@minkikim89 
동시성 제어 로직 자체는 좀 더 복잡해진 것 같습니다.
최적화 효과가 어느정도 있을지는 감이 잘 오지 않는데요,
이슈에서 언급한 `checkpoint thread에 의한 fd 변경이 fsync locking에 의해 지연`은
그대로 남아있는 부분 아닌가요?

- fsync thread가 log_file_sync()에서 log_fsync_lock을 획득 한 상태에서 do_log_file_sync()를 호출해 fsync를 수행하는 도중에
- checkpoint thread가 cmdlog_complete_dual_write()나 cmdlog_file_close() 동작에서 log_flush_lock을 획득하고 log_fsync_lock을 획득하려고 기다리면
- 동일하게 log flush thread가 log_flush_lock을 획득하지 못해 flush 작업에 지연이 생기는 것 아닌가요?

위 문제가 어떤 방식으로 해결되는지 정리해주면 장,단점 파악이 쉬울 것 같습니다.

**Comment by minkikim89** [comment]
@MinWooJin @jhpark816 
코드 수정을 조금 잘못해서 불필요하게 lock을 사용하는 형태로 PR을 했네요.
다시 정리해서 코드 올려두었습니다.
다시 정리한 코드에서는 아에 log_fsync_lock을 삭제한 상태입니다.
log_flush_lock을 잡은 상태에서 fsync_ongoing 플래그를  true 상태로 변경하여 fsync상태를 나타나기 때문에
다른 스레드들은 log_flush_lock을 잡은 상태에서 해당 플래그를 확인하면, fsync 진행 동안 해당 fd에 대해서 close를 진행하지 않습니다. 따라서 log_fsync_lock도 필요하지 않아졌습니다.

이렇게 변경할 때의
장점은 lock을 하나 제거하기 때문에 성능상에서 이점을 얻을 수 있을 것으로 생각합니다.(어느정도일지는 측정해봐야 알 수 있을 것 같습니다.
단점은 fsync_ongoing과 close_request 개념이 생기며 코드가 조금 복잡해졌다는 사실입니다. 하지만 이러한 개념이 생기며 log_fsync_lock이 사라졌기 때문에 결국 코드 복잡성은 크게 변하지 않았다고 생각합니다. 결국 큰 단점은 없지 않나 생각이 듭니다.

**Comment by jhpark816** [comment]
#430 이슈 처리에서,
log_flush_lock을 잡은 상태에서 log_fsync_lock 잡으려는 요청을 제거하였습니다.
결국, 본 이슈가 해결된 상태이므로, 본 이슈는 close 합니다.

참고 사항으로, checkpoint thread는 
log_fsync_lock을 잡은 상태에서 log_flush_lock 잡으려는 요청이 있을 수 있지만,
log flush 작업을 방해하지 않습니다.
