### ISSUE TITLE
Invalid exptime(과거 시점의 exptime)을 주는 경우 set, setattr 동작의 재검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#376]
현재 arcus-memcached는 invalid exptime을 주더라도 정상적으로 설정하여 item을 생성하고 있다.
invalid exptime은 30일 이상의 exptime을 절대 시간 값으로 주는 경우에 발생할 수 있다.
예를 들어, 2600000 이란 exptime 값을 주면,
- 30일 초과 exptime이므로 절대 시간으로 해석하고
- 해석한 절대 시간이 현재 시간보다 과거이므로 내부적으로 expired 상태가 된다.

첫째, Invalid exptime으로 set 연산을 수행하는 경우,
해당 item을 정상적으로 생성하지만, 바로 expired 상태가 되어 그 이후에 조회가 되지 않는다.
아래는 telnet 이용하여 직접 수행해 본 결과이다.

```
set test-key 0 2600000 9
test-data
STORED
get test-key
END
```

둘째, Invalid exptime으로 setattr 연산을 수행하는 경우,
해당 item의 exptime을 정상적으로 변경하지만, 바로 expired 상태가 되어 그 이후에 조회가 되지 않는다.
아래는 telnet 이용하여 직접 수행해 본 결과이다.

```
set test-key 0 0 9
test-data
STORED
get test-key
VALUE test-key 0 9
test-data
END
getattr test-key
ATTR type=kv
ATTR flags=0
ATTR expiretime=0
END
setattr test-key expiretime=2600000
OK
get test-key
END
getattr test-key
NOT_FOUND
```

여기서, 재검토할 사항은 
invalid exptime을 줄 경우, 정상 처리하지 않고 오류 리턴하는 것인 나은 방안이 아닌 지 ?

재검토 근거는 아래와 같다. 
- set 연산으로 item을 정상 생성하고 나서 조회가 되지 않을 경우,
   set 연산에서 invalid exptime을 주었는 지를 확인하여야 한다.
- 사전에 invalid exptime 여부를 확인하고 오류를 리턴한다면
   응용에게 명확한 이유를 전달해 줄 수 있다.
- 만약, 응용이 어떤 item을 invalidate 시켜 제거하고자 한다면, delete 연산을 사용하면 된다.

**Comment by SuhwanJang** [comment]
exptime 을 받는 flush 연산도 같이 재검토가 필요합니다.
<img width="312" alt="Screen Shot 2019-11-17 at 4 20 55 PM" src="https://user-images.githubusercontent.com/28725891/69004424-494f6980-0956-11ea-9267-b761dd706fe4.png">

invalid exptime 을 주는 경우 oldest_live 가 1로 설정되어 실질적으론 flush 작업이 이루어지지 않는다.
```
 static bool do_item_isvalid(hash_item *it, rel_time_t current_time)
 {
...
     /* check flushed items as well as expired items */
     if (config->oldest_live != 0) {
         if (config->oldest_live <= current_time && it->time <= config->oldest_live)
             return false; /* flushed by flush_all */
     }
...
     return true; /* Yes, it's a valid item */
 }

```
사전에 invalid exptime 여부를 확인하고 오류를 리턴한다면
응용에게 명확한 이유를 전달해 줄 수 있다.

**Comment by jhpark816** [comment]
@JJungwoo 
최신 memcached 확인하여 어떻게 처리하는 지를 알려주세요.
그리고 나서, 이 문제의 처리 방안을 결정하도록 합시다.

**Comment by JJungwoo** [comment]
@jhpark816

현재 최신 memcached 에서는 사용자로부터 exptime 값을 입력 받는 set, flush, collection 관련 명령에 대한 처리 과정에서 default engine 의 콜백 함수를 호출하는 순간 혹은 전에 realtime 함수를 통해 exptime 값에 대한 변환 과정이 있습니다.

```
#define REALTIME_MAXDELTA 60*60*24*30
...
static rel_time_t realtime(const time_t exptime)
{
    if (exptime == 0) return 0; /* 0 means never expire */
#ifdef ENABLE_STICKY_ITEM
    if (exptime == -1) return (rel_time_t)(-1);
#endif
    /* no. of seconds in 30 days - largest possible delta exptime */
    if (exptime > REALTIME_MAXDELTA) {
...
        if (exptime <= process_started)
            return (rel_time_t)1;
        return (rel_time_t)(exptime - process_started);
    } else {
        return (rel_time_t)(exptime + current_time);
    }
}
```

realtime 함수에서는 사용자로부터 입력 받은 exptime 값이 30일 초과로 주어졌을 때 절대 시간으로 계산되어 process_started 값 보다 작거나 같으면 1을 반환하여 사실상 expired item으로 할당이 됩니다. 따라서 get 명령을 통해 item을 조회할 경우 해당 item은 삭제되고 사용자는 item을 조회할 수 없습니다.

> process_started : time(0)의 반환 값으로 UTC 표준 시간 기준 1970년 1월 1일 0시 0분 0초부터 경과된 시간 값을 반환

위의 exptime 값에 대한 정보를 [arcus-memcached ch03 문서](https://github.com/naver/arcus-memcached/blob/master/doc/ch03-item-attributes.md#expiretime-%EC%86%8D%EC%84%B1)를 통해 알 수 있지만 사용자의 편리성과 잘못된 접근을 방지하는 명목하에 invalid exptime 응답을 리턴하면 좋을 것 같습니다.

다만 해당 작업을 하게된다면 위에서 언급했던 set, flush, collection 관련 명령이 처리되는 과정인 engine의 콜백 함수 각각에 exptime 값에 대한 유효성 검사 코드와 invalid exptime을 표현하는 engine의 error code 타입 그리고 engine의 콜백함수 결과로 발생한 invalid exptime 에러 응답에 대한 처리 동작도 명령 마다 추가되어야 합니다.

**Comment by jhpark816** [comment]
@JJungwoo 
최신 open source memcached 처리 방식을 확인하여 알려주시죠.
그 방식을 참조하여, 기존 그대로 둘지 아니면 오류 응답으로 처리할 지를 판단하도록 하죠.

**Comment by JJungwoo** [comment]
@jhpark816 

현재 최신 open source memcached 에서 invalid exptime 테스트를 진행한 결과 exptime 값이 30일 초과로 주어졌을 때 오류 응답을 처리해주지 않습니다. 

```
set test-key 0 2600000 9
test-data
STORED
get test-key
END
```

이에 따라 memcached 코드 분석 결과 현재 arcus-memcached의 처리 방식과 동일하게 명령에 대한 item 처리를 진행하는 함수 호출 직전 또는 호출 전에 realtime 함수를 호출하여 exptime 값에 대한 변환 과정을 진행합니다.

```
rel_time_t realtime(const time_t exptime) {
 ...
    if (exptime == 0) return 0; /* 0 means never expire */

    if (exptime > REALTIME_MAXDELTA) {
...
        if (exptime <= process_started)
            return (rel_time_t)1;
        return (rel_time_t)(exptime - process_started);
    } else {
        return (rel_time_t)(exptime + current_time);
    }
}
```

arcus-memcached 동작과 차이가 있다면 arcus-memcached 에서는 exptime 값이 -1 은 sticky item으로 설정되지만 memcached 에서는 telnet을 통해 사용자로부터 set, touch 명령 관련 처리를 할  때 exptime 값이 음수이면 아래의 매크로 함수를 통해 REALTIME_MAXDELTA + 1 값을 할당하여 realtime 함수에서 expired item으로 처리되도록 설계되어 있습니다.

```
#define EXPTIME_TO_POSITIVE_TIME(exptime) (exptime < 0) ? \
         REALTIME_MAXDELTA + 1 : exptime
```

set 명령 처리 과정에서 다음과 같이 매크로 함수가 사용됩니다.

```
exptime = realtime(EXPTIME_TO_POSITIVE_TIME(exptime_int));
```

위의 내용들을 바탕으로 음수에 대한 테스트를 진행하였을 때 arcus-memcached에서 exptime 값이 -1 보다 더 작은 음수이면 아래와 같이 expiretime 값에 문제가 발생할 수 있습니다.

```
set test-key 0 -2600000 9
test-data
STORED
get test-key
VALUE test-key 0 9
test-data
END
getattr test-key
ATTR type=kv
ATTR flags=0
ATTR expiretime=-2600015
END
```

아래 내용은 동일한 명령을 memcached에서 처리한 결과 입니다.

```
set test-key 0 -2600000 9
test-data
STORED
get test-key
END
getattr test-key
ERROR
```

**Comment by jhpark816** [comment]
@JJungwoo @SuhwanJang 

첫째, 과거 시점의 expiretime이 주어지면, 오류 처리하지 않고 즉각 expire 되게 하죠.
즉, 현재의 처리 방식을 그대로 유지하죠.

둘째, 음수의 expiretime이 주어지면, 즉각 expire되게 수정 합니다.
`-1`은 sticky item의미로 사용되므로, `-1`을 제외한 음수를 의미합니다.
EXPTIME_TO_POSITIVE_TIME() macro를 두지 말고, realtime() 함수를 수정하도록 하시죠.
아래 코드를 확인 바랍니다.
```
static rel_time_t realtime(const time_t exptime)
{
    if (exptime == 0) return 0; /* 0 means never expire */
    if (realtime < 0) {
#ifdef ENABLE_STICKY_ITEM
        if (exptime == -1) return (rel_time_t)(-1);
#endif
        return (rel_time_t)1;
    }
    /* no. of seconds in 30 days - largest possible delta exptime */
    if (exptime > REALTIME_MAXDELTA) {
        . . .
    } else {
        return (rel_time_t)(exptime + current_time);
    }
}
```

**Comment by JJungwoo** [comment]
코멘트 해주신 내용 반영하여 작업 진행 완료하였습니다.
commit link: b633d84
