### ISSUE TITLE
[persistence] 체크포인트 수행 조건 및 비동기 로깅(async logging) 모드의 동적 변경 기능 개발

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-memcached#384]
체크포인트 수행 조건 및 명령 로깅 모드를 동적으로 설정하는 기능을 개발한다.
- 체크포인트 수행 조건
  - 스냅샷 파일 대비 명령 로그 파일 크기 증가율(%)
  - 최소 명령 로그 파일 크기(MB)
- 명령 로깅 모드 : 동기 / 비동기

#345

**Comment by SuhwanJang** [comment]
#https://github.com/naver/arcus-memcached/issues/345

**Comment by Johyeyoung** [comment]
test

**Comment by SuhwanJang** [comment]
`config` 명령에 체크포인트 수행 조건과 명령 로깅 모드 설정 가능하도록 추가해주시면 됩니다.
사용 및 출력 결과는 아래와 같습니다.

// 사용법 조회
```
help admin 
    ...
    config zkfailstop [on|off]\r\n
    config chkpt_interval_pct_snapshot [<percentage(%)>]\r\n
    config chkpt_interval_min_logsize [<minsize(MB)>]\r\n
    config async_logging [on|off]\r\n
```

// 스냅샷 파일 대비 명령 로그 파일 크기 증가율 조회
```
config chkpt_interval_pct_snapshot
chkpt_interval_pct_snapshot 100
END
```

// 스냅샷 파일 대비 명령 로그 파일 크기 증가율 변경
```
config chkpt_interval_pct_snapshot 80
END
```

다른 설정도 위와 같이 처리하고, 위 설정 변경과 사용법 조회 결과에는  --enable-persistence configure 옵션 컴파일한 경우에만 정상 동작합니다.

**Comment by SuhwanJang** [comment]
체크포인트 수행 조건 및 명령 로깅 모드를 동적으로 설정하는 기능이 추가되었습니다.
commit : https://github.com/naver/arcus-memcached/commit/e80ed624802970ca17631d974f98d90efa694476
