### ISSUE TITLE
[persistence] evict 동작에서 waiter 관련 동작 확인

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#387]
arcus 서버 동작 중 메모리가 부족하여
background eviction에 의한 item unlink가 수행될 수 있다.
현재는 persistence 를 사용 하더라도 waiter alloc/free에 대한 로직이 고려되지 않은 상태이고
item_unlink clog에서도 이러한 부분으로 인해 waiter == NULL인 경우가 있게 된다.

관련 동작을 확인하고, waiter 필요 여부 및 alloc/free에 대한 정확한 handling이 필요하다.

**Comment by MinWooJin** [comment]
eviction 동작은 engine 내부에서 cache lock을 획득 한 뒤
evict 대상이 되는 여러 item을 제거하면서 log record를 생성하도록 되어있다.
이러한 동작에서 일부 lrec만 기록되고 엔진 실패 할 경우 기록된 lrec를 undo 할 필요가 없다.

따라서 cmdlogmgr module의 ` void cmdlog_generate_unlink_item(hash_item *it)`의 waiter는
`NULL`일 수 있는 상태이다.

**Comment by jhpark816** [comment]
@MinWooJin 
OK. 동의합니다.
해당 주석만 변경해 주시죠.

**Comment by MinWooJin** [comment]
https://github.com/naver/arcus-memcached/pull/432 반영 완료 되었습니다.

issue close 합니다.
