### ISSUE TITLE
[persistence] item clog 모듈에서 log record 생성 및 기록 코드의 함수화

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#400]
item clog 모듈에서 log record 생성 및 기록하는 코드의 현재 구현은 다음과 같습니다.

```C
void CLOG_GE_ITEM_LINK(hash_item *it)
{
    if ((it->iflag & ITEM_INTERNAL) == 0)
    {
#ifdef ENABLE_PERSISTENCE
        if (config->use_persistence) {
            log_waiter_t *waiter = cmdlog_get_cur_waiter();
            if (waiter->elem_clog_with_collection == false) {
                ITLinkLog log;
                (void)lrec_construct_link_item((LogRec*)&log, it);
                log_record_write((LogRec*)&log, waiter, NEED_DUAL_WRITE(it));
            }
        }
#endif
    }
}
```

아래의 간결한 구현으로 변경하는 것을 먼저 검토해 주세요.
- ITEM CLOG 모듈은 다른 모듈과 연결하는 성격의 모듈로 간단한 호출로만 구현되게 하려는 목적

```C
void CLOG_GE_ITEM_LINK(hash_item *it)
{
    if ((it->iflag & ITEM_INTERNAL) == 0)
    {
#ifdef ENABLE_PERSISTENCE
        if (config->use_persistence) {
            lrec_generate_link_item(it);
        }
#endif
    }
}
```

충분히 가능한 구현이고 서스테이닝에 유리하다고 판단되면, 구현을 변경합시다.

**Comment by jhpark816** [comment]
@MinWooJin @SuhwanJang 
검토하고 의견 바랍니다.

**Comment by SuhwanJang** [comment]
@jhpark816 
구현부는 별도로 두고 ITEM_CLOG 는 인터페이스 역할만 하도록 변경하는 것이 좋겠네요. 동의합니다. 구현도 기존 로직을 함수화하는 것 뿐이니 가능합니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
wrapper 함수를 더 두는 형태입니다.
- wrapper 함수는 cmd log 모듈 쪽의 코드 파일에 구현하고,
   header 파일에 명시하여 외부에서 사용할 수 있게 하고,
 - item clog 모듈은 header 파일만 include하여 그 함수를 호출하면 됩니다.

**Comment by SuhwanJang** [comment]
@jhpark816 @MinWooJin
네. 그러한 형태가 될거라고 생각하며 코멘트하였습니다. 전 추가 의견이 없어 @MinWooJin 의견주세요.

**Comment by MinWooJin** [comment]
@jhpark816 @SuhwanJang 
구현 가능 하고, 변경하는게 더 괜찮을 것 같습니다.

**Comment by SuhwanJang** [comment]
@MinWooJin 
위 이슈는 제가 진행하겠습니다.

**Comment by SuhwanJang** [comment]
Merged commit : https://github.com/naver/arcus-memcached/commit/534821a6abbf99c5479a73ba3d3864cf1ac20e78
log record 생성 및 기록을 함수화하여 체크포인트 스캔포인터 관련 코드와 함께 cmdlogmgr 모듈에 위치시켰음.
