### ISSUE TITLE
[persistence] cmdlog_file_close 필요성 검토

### ISSUE THREAD

**Issue by minkikim89** [naver/arcus-memcached#406]
최근, log_file 구조체에서 prev_fd 변수를 삭제하는 작업이 merge 되었다.
이 작업이 merge되기 이전에 checkpoint에서 호출하는 cmdlog 함수들과 그 함수들의 동작을 살펴보면 아래와 같다.
1. cmdlog_file_open
   - snapshot 진행 시 dual_write할 next_fd를 open
2. cmdlog_complete_dual_write
   - snapshot이 모두 종료된 이후에 호출.
   - snapshot 성공 시, next_fd를 현재 사용하는 fd로 설정하고 prev_fd에 기존 fd를 설정.
   - snapshot 실패 시, next_fd를 prev_fd에 설정한다.
3. cmdlog_file_close
   - 더 이상 사용하지 않는 prev_fd를 close 한다.

cmdlog_file_close 코드를 보면 prev_fd와 next_fd에 대해서 사용 여부(!= -1)를 확인한 이후에 file을 close 하도록 되어있다. 하지만 위에 정리한 로직을 보면 next_fd에 대해서 검사할 필요는 전혀 없다.
그렇다면 checkpoint에서 cmdlog_file_close를 호출했던 이유는 prev_fd를 정리하기 위한 목적 뿐이었으므로,
prev_fd를 cmdlog_complete_dual_write에서 close 하도록 변경한 지금 checkpoint 모듈은 cmdlog_file_close를 호출할 필요가 없다.

cmdlog_file_close가 next_fd를 정리하는 코드가 들어간 것은 https://github.com/naver/arcus-memcached/pull/285 PR이다.
이슈에서 아래와 같은 코멘트가 있었다.

================================================
cmdlog_file_close() 함수에 대해 정리해 봅니다.

- checkpoint snapshot 성공 후에 close 하는 경우, 아래만 수행하면 됨.
   - close(prev_fd)
- checkpoint snapshot 실패 후에 close 하는 경우, 아래만 수행하면 됨.
   - close(next_fd)
   - 만약, snapshot 실패 시에 next_fd를 prev_fd로 옮겨둔다면, close(prev_fd)만 수행할 수 있음.
- 시스템 종료 시에는 항상 fd만 유효하다. 따라서, 아래만 수행하면 됨.
   - fsync(fd), close(fd)

위의 cmdlog_file_close() 함수들은 위의 경우를 만족하고,
각 close 경우를 구분하여 file_close() 함수를 만들려고 했는 데,
현재 생각으론 아래와 같이 하나의 함수로 가져가는 것이 더 나을 것 같습니다.

```
void cmdlog_file_close(bool shutdown)
{
    pthread_mutex_lock(&log_gl.log_flush_lock);
    if (logfile->prev_fd != -1) {
        (void)disk_close(logfile->prev_fd);
        logfile->prev_fd = -1;
    }
    if (logfile->next_fd != -1) {
        (void)disk_close(logfile->next_fd);
        logfile->next_fd = -1;
    }
    if (shutdown && logfile->fd != -1) {
        (void)disk_fsync(logfile->fd);
        (void)disk_close(logfile->fd);
        logfile->fd = -1;
    }
    pthread_mutex_unlock(&log_gl.log_flush_lock);

}
```
================================================

위 코멘트를 정리하면 cmdlog_file_close에서는 prev_fd만을 close 하여도 된다고 정리하였지만
실수, 내지는 범용성을 위해서 cmdlog_file_close에서 prev_fd와, next_fd를 모두 확인하여 삭제하도록 작성한 것으로 보인다.

이에, checkpoint에서 cmdlog_file_close는 호출하지 않도록 수정하고,
cmdlog_file_close는 기존 shutdown을 위해서만 사용되기 때문에 cmdlog_file_final로 변경하도록 한다.
checkpoint에서 사용하는 기존 cmdlog_file_open도 이에 따라 cmdlog_file_prepare로 함수명을 바꾼다.

**Comment by minkikim89** [comment]
@MinWooJin @jhpark816 
이 이슈 내용에 대해 리뷰 부탁드립니다.

**Comment by jhpark816** [comment]
@minkikim89 
이해하기 어렵습니다. 처음 코멘트를 다시 수정 바랍니다.

**Comment by minkikim89** [comment]
@jhpark816 
수정했습니다.

**Comment by jhpark816** [comment]
@minkikim89 
이해했습니다. 쌩큐. (앞의 불필요한 코멘트 제거합니다)

함수 목록과 호출 관계 등을 포함하여 관련 인터페이스 전체를 검토할 필요가 있습니다.
- 적절한 함수 목록과 use case가 적절한지 ?
- 현재 cmdlog_complete_dual_write() 부분이 뭔가 어색합니다.
- open & close pair 유지
- 기타 등등

이 관점에서 나은 아이디어가 있으면 주세요.
나도 살펴보고 의견 줄게요.

**Comment by MinWooJin** [comment]
cmdlog_file_close()는 그대로 유지하는게 나아보입니다.
- checkpoint 실패  처리
  - checkpoint가 항상 snapshot을 시작한다는 보장이 없기때문에, cmdlog_complete_dual_write()가 수행되지 않을 수 있습니다.
  - 실패 할 경우 next_fd file을 do_checkpoint() 에서 close 하는게 가장 적절해보입니다.
- open & close pair 유지
  - init & final pair와 별개로 open & close pair를 유지하는게 나아보입니다.

**Comment by jhpark816** [comment]
@minkikim89 

@MinWooJin 님의 의견대로 cmdlog_file_close() 함수를 그대로 유지하시죠.

To @MinWooJin 
아래 사항을 검토 바랍니다.
- 처음 file 생성한 경우이면, 그 file도 close하면 더 나을 것 같습니다.
   어떻게 처리하면 좋은가요 ?
- prev file을 early close 하도록 수정한 상태인 데, 
   이를 원래대로 cmdlog_file_close()에서 close하는 것이 나은가요 ?

**Comment by MinWooJin** [comment]
@jhpark816 
- 처음 file 생성한 경우이면, 그 file도 close
  - 어떤 의미인지 잘 모르겠네요. 추가 설명을 해주시면 좋을 것 같습니다.
- prev file을 원래대로 cmdlog_file_close()에서
  - 저는 그대로 early close 하는게 나을 것 같습니다.
  - 현재 complete_dual_write 로직에서 prev file close하는게 이상하진 않는 것 같고,
  - 이를 위해 prev_fd를 추가하여 관리할 필요가 없을 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin 

아래의 cmdlog_file_open() 코드에서 `logfile->fd == -1` 경우를 말하는 것입니다.

```
        int fd = disk_open(path, O_CREAT | O_RDWR, S_IRUSR | S_IWUSR | S_IRGRP);
        if (fd < 0) {
            logger->log(EXTENSION_LOG_WARNING, NULL,
                        "Failed to open the cmdlog file. path=%s err=%s\n",
                        logfile->path, strerror(errno));
            ret = -1;
            break;
        }
        snprintf(logfile->path, CMDLOG_MAX_FILEPATH_LENGTH, "%s", path);
        pthread_mutex_lock(&log_gl.log_fsync_lock);
        if (logfile->fd == -1) {
            logfile->fd = fd;
        } else {
            /* fd != -1 means that a new cmdlog file is created by checkpoint */
            logfile->next_fd = fd;
        }
        pthread_mutex_unlock(&log_gl.log_fsync_lock);
```

**Comment by MinWooJin** [comment]
@jhpark816 
처음 생성하고 그 file을 close 할 이유가 있나요?
close하면 command log record를 기록하기위해 다시 open 해야 합니다.
현재 file write 로직은 open된 상태임을 가정하고 설계된 상태입니다.

**Comment by jhpark816** [comment]
@MinWooJin 
처음 생성하고 나서 snapshot 실패하면, 아마 engine 구동이 중지될 것입니다.
그래서, 아래 2개 관점에서 close하는 것이 나은 것 같습니다.
- clean하게 처리한 후에 구동 중지
- open & close pair 코드 유지.

**Comment by MinWooJin** [comment]
@jhpark816 
어떤 상태인지 이해 했습니다.
snapshot 실패하면 unlink 하고 구동 중지 되지만 close 하지 않고 unlink 한거라서
정상적이지 않겠네요. 다른 issue에서 다루는게 나을 것 같은데 어떠신가요?

**Comment by jhpark816** [comment]
@MinWooJin 그렇게 하시죠.

**Comment by MinWooJin** [comment]
@minkikim89 @jhpark816 
현재 issue는 검토 후 close 해주시면 될 것 같습니다.

**Comment by minkikim89** [comment]
@MinWooJin @jhpark816 
제가 처음에 이 이슈를 만들었던 이유는 cmdlog_file_close를 checkpoint에서
콜하지 않을 경우 log_fsync_lock을 삭제할 수 있을 것으로 보였기 때문입니다.
그대로 open, close 페어를 유지한다면 이를 유지하면서도 log_fsync_lock을 삭제할 수 있는지
점검 바랍니다.
아마도 https://github.com/naver/arcus-memcached/issues/430 이 이슈에서 다루면 될 것 같네요.

**Comment by minkikim89** [comment]
@MinWooJin @jhpark816
아 착각했네요. 이 인터페이스를 삭제하기만 하면 log_fsync_lock을 삭제할 수 있는 것은 아니고
https://github.com/naver/arcus-memcached/issues/370 이 이슈와 연관하여 fsync_ongoing을 사용하면 log_fsync_lock을 삭제할 수 있습니다. 이는 추후에 https://github.com/naver/arcus-memcached/pull/398 이 PR에서 적용하도록 하겠습니다.
