### ISSUE TITLE
[persistence] log record 출력 형식 통일화

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#407]
아래 관점에서 통일화 필요
- 단일 값의 표현은 일관됨
  - "xxx=yyy" 형태
- 구조체 값의 표현은 통일화 필요
   - "xxx=(xx1=yy1,xx2=yy2)" 형태가 좋을 듯
   - 다른 의견 있으면 제시해 주세요 
- header와 body는 아래와 같이
   -  body 부분은 의미에 따라 여러 line으로 표현 가능 

```
[HEADER] body_length=%u | logtype=%s | updtype=%s
[BODY  ] keylen=%u | keystr=%.*s | fldlen=%u | fldstr=%.*s | vallen=%u |
         xxxx=yyyy | xxxx=yyyy             
```

**Comment by SuhwanJang** [comment]
다른 의견 없으니 위 이슈대로 작업하겠습니다.

**Comment by SuhwanJang** [comment]
Merged commit : https://github.com/naver/arcus-memcached/commit/1494e88f9c929cdf5a8a657976192a78a303829a
