### ISSUE TITLE
[persistence] cmdlog buffer, file 분리.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#410]
현재는 cmdlogbuf 파일에 buffer, file의 2개 기능이 들어 있음.
용도에 맞게 2개 파일로 구분하는 것이 필요.
- cmdlogbuf
- cmdlogfile

**Comment by jhpark816** [comment]
@SuhwanJang @MinWooJin 
검토하고 의견 주세요.

**Comment by MinWooJin** [comment]
@jhpark816 
코드 분리, 함수명 변경 모두 진행해도 좋겠습니다.

**Comment by SuhwanJang** [comment]
동의합니다. 제가 진행하겠습니다.

**Comment by meeeejin** [comment]
현재 작업하고 계신 분이 안 계시면 제가 하겠습니다.

**Comment by meeeejin** [comment]
cmdlogbuf는 크게 아래 세가지 작업으로 이루어진 것으로 보입니다.

- log buffer 관련 작업
- log file 관련 작업
- log flusher

이에 기반해 log buffer 관련 작업 및 log flusher는 cmdlogbuf로, log file 관련 작업은 cmdlogfile로 분리하고자 합니다. 이렇게 나눠도 될까요? log flusher 분리 여부에 대해서 어떻게 생각하시는지 궁금합니다. 제가 생각하기에 log flusher는 결국 주기적으로 log buffer에 있는 log record를 디스크로 flush 요청하는거라 log file write/sync 작업만 별도 파일로 분리하려고 했습니다.

본 이슈 관련해 의도하신 바가 있다면 참고하고 싶습니다.

**Comment by jhpark816** [comment]
@meeeejin 
안녕하세요. 먼저 컨트리뷰션 노력에 감사 드립니다.

persistence 작업이 기본 설계 및 구현까지 진행되고 나서,
리팩토링, 최적화 등의 작업이 아주 천천히 진행되고 있어서, 기억이 조금 희미합니다.

따라서, 구체적인 사항보단, 개념적 관점에서 답변을 드리면,
@meeeejin 님이 생각하신 대로 진행하는 것이 맞습니다.
- work threads에 의한 log buffer 기록 작업과 log flusher에 의한 log buffer flush 작업이
  모두 log buffer 기반으로 동작하므로, cmdlogbuf 모듈에 위치해야 합니다.
- cmd log file에 관한 write/sync 연산들이 cmdlogfile 모듈로 분리하면 됩니다.
- 각 모듈 간의 interface와 모듈 간의 호출 관계 등도 검토해 보시고,
  어색하거나 문제가 있어 수정이 필요하다면, 작은 단위의 commit으로 PR 주시면 됩니다.

추가 질문이 있다면, 언제라도 주세요.

**Comment by meeeejin** [comment]
@jhpark816 
안녕하세요. 답변 감사드립니다.

현재 cmdlogbuf/cmdlogfile 분리 구현은 한 상태이고 make test는 통과한 상태입니다.
혹시 persistence를 실질적으로 테스트할 수 있는 방법이 있을까요?
Persistence는 별도의 테스트 방법이 있을 것 같아 질문 드립니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
위의 질문 확인하시고,
아래 내용을 포함하는 간단한 markdown 문서를 만들어 github wiki에 넣어두고 공유해 주세요.
- persistence 기능 포함한 compile
- memcached 구동 (간단한 engine config 예시 포함)
- persistence 테스트 방법
   - telnet 사용한 방법
   - acp-java 사용한 방법 (유용하다면)
   - 그 외, 간단한 응용 예가 있다면 그 에를 기술
- memcached 종료 및 재구동

**Comment by SuhwanJang** [comment]
@jhpark816 persistence 사용법 (https://github.com/naver/arcus-memcached/wiki/Persistence-Guide) 작성하였습니다.
@meeeejin 
위 문서에 간단하게 telnet 으로 테스트하는 방법을 설명해두었는데, 추가적으로 궁금한 사항이 있으시면 코멘트 남겨주세요.

**Comment by jhpark816** [comment]
수고 많았습니다.
