### ISSUE TITLE
[persistence] LogSN 정의 및 매크로 관리.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#411]
아래와 같이 변경하는 것에 대해 검토하고, 결정되면 수정합시다.
- 현재: cmdlogmgr에서 관리
- 변경: cmdlogbuf or cmdlogrec에서 관리 (검토 필요)

**Comment by MinWooJin** [comment]
@jhpark816 
변경하려는 이유는 무엇인가요?
cmdlogmgr에 있는 waiter module에서의 사용이 더 많아서
그대로 cmdlogmgr에서 관리하는게 괜찮지 않나 싶습니다.

**Comment by jhpark816** [comment]
@MinWooJin 
LogSN 개념은 log manager 내부의 개념이라
log manager 외부에 노출하지 않는 것이 맞다고 생각했는 데,
log buffer, log file, log waiter 등을 먼저 정리해 보고, 다시 검토해 봅시다.

**Comment by jhpark816** [comment]
아래와 같이 정리합니다.
- LogSN 정의와 매크로는 cmdlogrec.h 옮깁니다.
- update type 또한 log record에 관한 사항이라 cmdlogrec.h로 옮깁니다.

**Comment by jhpark816** [comment]
위 코멘트 사항을 아래 commit에서 반영하였습니다.
- commit link: https://github.com/naver/arcus-memcached/commit/3ac433d3b723f8d9c505ee7a7eb37bdaabb11265
