### ISSUE TITLE
[persistence] cmdlog_buff_flush의 log_flush_lock 사용 관련 검토

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#426]
현재 cmdlog_buff_flush() 내부 로직은 아래와 같다.
```
void cmdlog_buff_flush(LogSN *upto_lsn)
{
    assert(upto_lsn);
    uint32_t nflush;

    do {
        pthread_mutex_lock(&log_gl.log_flush_lock);
        if (LOGSN_IS_LE(&log_gl.nxt_flush_lsn, upto_lsn)) {
            nflush = do_log_buff_flush(true);
            assert(nflush > 0);
            if (LOGSN_IS_GT(&log_gl.nxt_flush_lsn, upto_lsn)) {
                nflush = 0;
            }
        } else {
            nflush = 0;
        }
        pthread_mutex_unlock(&log_gl.log_flush_lock);
    } while (nflush > 0);
}
```
위 로직을 보면
  - log_gl.nxt_flush_lsn을 log_flush_lock을 잡은 상태에서 upto_lsn과 비교하고 buff_flush 이후에도 log_flush_lock을 잡은 상태에서 비교하도록 되어있다.
  - nxt_flush_lsn은 cmdlog_get_flush_lsn()으로 획득할 수 있으며 flush_lsn_lock을 사용한다.

따라서 상단에서 log_flush_lock을 잡고 비교하지 않아도 될 것으로 보인다.
검토 후 do_log_buff_flush() 에서만 log_flush_lock을 잡도록 변경한다.

위와같이 변경이 완료되면 log_flush_lock은 do_log_buff_flush() 내부에서 잡도록 할 수 있으며
내부에서 잡는게 로직 이해에 더 유리하다고 생각된다.

**Comment by jhpark816** [comment]
@SuhwanJang 이슈를 검토해 주세요.

**Comment by SuhwanJang** [comment]
@jhpark816 검토하였습니다. 이견은 없습니다.

**Comment by jhpark816** [comment]
@MinWooJin 중요하지 않은 이슈로 천천히 살펴볼께요.

**Comment by jhpark816** [comment]
@MinWooJin @SuhwanJang 

cmdlog_get_flush_lsn()으로 nxt_flush_lsn을 얻은 후에도
flush daemon thread에 의해 추가의 flush 작업이 진행되었을 수 있습니다.
따라서, log_flush_lock을 획득하였으면,
LSN 비교를 통해 flush 작업을 실제로 수행해야 하는 지를 판단하는 것이 필요합니다.
불필요한 flush 작업을 없을 수 있습니다.

본 이슈는 close해도 될 것 같습니다.

**Comment by MinWooJin** [comment]
@jhpark816 
확인했습니다. issue close 합니다.
