### ISSUE TITLE
[persistence] log_flush_lock vs. log_fsync_lock 사용의 점검.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#430]
lock_flush_lock vs. log_fsync_lock 사용 관점에서 최적 상태인지를 검토한다.

- 두 lock의 목적은 무엇인가 ?
- 그 목적에 충실하면서 최적의 동시성 제어를 구현한 상태인가 ?

**Comment by MinWooJin** [comment]
@jhpark816 
아래와 같이 정리 했습니다. 같이 검토해주시면 좋을 것 같습니다.
- log_flush_lock 사용 부분은 일부 refactoring 성격의 수정을 검토할 수 있겠습니다.
- log_fsync_lock 사용 부분은 수정을 검토 할 필요가 있겠습니다.

---

두 lock의 목적
  - lock_flush_lock
    - log file에 관련된 정보 전체에 대한 제어
    - 한 시점에 하나의 thread 만 file write 수행 제어를 목적으로 사용
  - lock_fsync_lock
    - log file의 fd, next_fd를 이용해 disk_fsync, disk_close가 한시점에 하나의 thread 수행 제어를 목적으로 사용

현재 코드의 검토 부분
  - fd, next_fd에 대한 disk_fsync, disk_close 작업을 정확하게 위해 fd를 변경하는 로직에서 항상 log_fsync_lock 을 사용하는 상황임
    - `cmdlog_file_open()`, `cmdlog_file_close()`, `do_log_file_complete_dual_write()`
  - 정확한 fd로 fsync, close하기 위해서 사용한다면 `cmdlog_file_sync()`에서도 log_flush_lock을 잡은 상태에서 하는게 맞는데 그렇지 않은 상태
  - 결론은 항상 정확한 fd에 대해 fsync, close 할 필요가 없어보이고
    - 중요한건 fd이고, fd가 변경되는 로직은 shutdown과 complete_dual_write 임
    - dual write가 끝나고 next_fd -> fd 변경에서도 두 file에 fsync 완료된 waiter에 대해서만 noti를 주기 때문에 문제 없다고 판단됨.
  - fd를 변경하는 로직에서 log_fsync_lock을 사용하지 않아도 될 것으로 보임

log_flush_lock은 그 목적에 충실하게 구현된 상태로 보이지만
일부 refactoring 검토가 필요한 부분이 보임
  - `cmdlog_file_open()` 에서 fd 변경 할때만 잡으면 될 것으로 보임
  - `cmdlog_buff_flush()`의 refactoring은 #426 에서 진행

**Comment by minkikim89** [comment]
@MinWooJin
https://github.com/naver/arcus-memcached/issues/370 이슈에서 언급된 fsync_ongoing을 사용하면
log_fsync_lock을 삭제할 수 있을 것으로 예측됩니다. 이에 대해서도 검토 바랍니다.

**Comment by MinWooJin** [comment]
@minkikim89 
fsync_ongoing을 사용하면 log_fsync_lock 삭제 가능할 것 같습니다.
저는 #370 issue 처리 후 lock 관점에서 검토만 진행하면
현재 issue 처리 완료 될 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin 
- 검토 내용을 좀 더 명확하게 기술해 주세요.
- fsync_ongoing 방법과의 관계도 기술해 주세요.

**Comment by MinWooJin** [comment]
@jhpark816 
검토 내용을 다시 정리하면,
  - log_flush_lock은 필요한 곳에 적절하게 사용하고 있다고 판단했고
  - log_fsync_lock은 fsync를 너무 정확하게 하기위해서
    - log_fsync_lock 을 과도하게 사용하고 있었고, 이부분을 꼭 필요한 부분 `cmdlog_file_sync()` 에서만 사용하면 될 것으로 정리 했습니다.

fsync_ongoing은 하나의 thread만 fsync 함을 보장하기 위해 log_fsync_lock을 사용하지 않고
fsync 상태를 확인하기 위해 log_flush_lock을 잠깐 획득하는 것으로 변경하는 방법입니다.
fsync_ongoing이 반영되면 log_fsync_lock이 제거됩니다.

따라서 fsync_ongoing이 반영 되면 log_flush_lock만으로 동작 가능하고
log_flush_lock에 대한 오버헤드도 더 증가하진 않을 것 같다는 판단입니다.

**Comment by jhpark816** [comment]
@MinWooJin @minkikim89 
처리 방향을 먼저 알립니다.
- fsync_ongoing은 lock에 의한 delay를 제거하기 위한 최적화 방안에서 나온 아이디어입니다.
- 현재 locking & unblocking 자체의 최적화가 가능하다고 판단하므로,
  이에 대한 정리 및 최적화를 먼저 진행하려고 합니다.
- 이러한 locking 최적화 이후에도 아래와 같이 
   fsync_ongoing 방식을 적용하는 것이 낫다고 판단되면, 그 때 적용할 예정입니다.
   - lock에 의한 delay가 여전히 존재하거나 
   - fsync_ongoing 방식이 readability에 유리

@MinWooJin
위 코멘트에서 지적한 바와 같이 불필요하게 잡는 locking을 제거하여 PR 보내 주세요.
PR 코드를 보면, 명확하게 드러날 것 같습니다.
참고로, 리팩토링 작업은 이번 PR에서 제외해 주고요.

**Comment by MinWooJin** [comment]
@jhpark816 
대략 코드로 수정을 진행했는데, 설계에서는 신경 안쓰던 부분이 걸리네요.
불필요하게 잡는 locking을 제거하기 위해선
- early cmdlog file close 하던 기존 로직에 대해 변경하거나
- fsync ongoing 개념이 필요하네요.

checkpoint 끝나고 prev_fd가 된 fd file의 close 순서 문제가 남아있네요.
`cmdlog_complete_dual_write()`의 early cmdlog file close에 의해
아래 코드에서 fd가 이미 close 되었을 수 있습니다.
```
cmdlogbuf.c
void cmdlog_file_sync()
{
...
    /* fsync the log files */
    pthread_mutex_lock(&log_gl.log_flush_lock);
    int fd      = log_gl.log_file.fd;
    int next_fd = log_gl.log_file.next_fd;
    pthread_mutex_unlock(&log_gl.log_flush_lock);

    pthread_mutex_lock(&log_gl.log_fsync_lock);
    if (1) {
        /* fsync curr fd */
        int ret = disk_fsync(fd);
...
}
```

일부 변경하고 보니 결국 fsync_ongoing 방식으로 가는게 더 낫지 않나 싶습니다.

**Comment by jhpark816** [comment]
@MinWooJin 
아래 사항을 정리해 주세요.
향후에 어떻게 방향이 결정되든, 현재 이슈를 명쾌하게 정리해 봅시다.

- 현재 이슈가 되는 fd 변경이나 클로즈 작업들을 일반화하여
  아래 경우를 정리해 주세요.
   - flush_lock 잡고 수행해야 하는 작업과 코드 예
   - fsync lock 잡고 수행해야 하는 작업과 코드 예
-  early cmdlog file close를 어떻게 변경하면 되는 가요 ?

**Comment by MinWooJin** [comment]
아래와 같이 정리하였고, 현재가 아닌 변경하려는 로직으로 설명합니다.
early cmdlog file close 변경 없이 가능한 방법을 찾아서
early cmdlog file close 변경이 필요하다는 부분은 정정 하겠습니다.
필요했던 이유는 cmdlog_file_sync() 에서 close 되지 않은 fd만 fsync() 함을 보장하기 위함인데,
- log_fsync_lock을 이용해 가장 최근에 close 된 fd를 저장해놓고
- cmdlog_file_sync()에서 fd와 next_fd가 최근에 close 된 fd가 아닐 경우만 fsync() 하면 되겠습니다.

log_flush_lock, log_fsync_lock의 역할을 재정리 하면 아래와 같습니다.
- log_flush_lock
  - fd, next_fd 정보를 변경하거나 조회하기 위해 사용
  - log buffer -> log file로 write하기 위한 thread 제어에 사용
- log_fsync_lock
  - open된 file만 fsync함을 보장하기 위해 file close 시 사용
  - log file을 fsync 하기 위한 thread 제어에 사용

---
- fd, next_fd가 변경되는 상황정리
  - file open, close, checkpoint 완료에 의해 변경
  - **log_flush_lock**을 잡고 수행
  - file open : `cmdlog_file_open()`
    - 처음 구동에서 fd 설정
    - checkpoint 에서 next_fd 설정
  - file close : `cmdlog_file_close()`
    - shutdown 에서 fd, next_fd = -1
    - checkpoint 시작 실패로 next_fd = -1
  - checkpoint 완료 : `cmdlog_complete_dual_write()`
    - checkpoint 성공으로, fd = next_fd, next_fd = -1
    - checkpoint 실패로, next_fd = -1
- file close 상황 정리
  - shutdown, checkpoint 시작 실패, checkpoint 완료에 의해 수행
  - shutdown : `cmdlog_file_close(shutdown)`
    - **log_flush_lock**을 잡고 수행
    - 이미 fd를 사용하는 thread들이 종료 된 이후로 문제 없음
  - checkpoint 시작 실패 : `cmdlog_file_close()`
    - **log_flush_lock**을 잡고 next_fd = -1
    - **log_fsync_lock**을 잡고 next_fd close
    - **rexcent_closed_fd 설정**
  - checkpoint 완료 : `cmdlog_complete_dual_write()`
    - **log_fsync_lock**을 잡고 수행
    - checkpoint 성공 시 prev_fd, 실패 시 next_fd 를 close
    - **recent_closed_fd 설정**
- fd, next_fd를 이용하는 상황 정리
  - log buffer flush, log file sync 에서 사용
  - log buffer flush : `do_log_buff_flush() : log_flush_lock 상태에서 호출`
    - **log_flush_lock** 상태에서 수행
    - fd, next_fd가 항상 vaild 하고 open 되어 있는 상태가 보장
  - log file fsync : `cmdlog_file_sync()`
    - **log_flush_lock** 상태에서 fd, next_fd 조회 후 unlock
    - **log_fsync_lock** 상태에서 fd, next_fd fsync
      - **recent_closed_fd를 확인**하고
      - complete_dual_wirte()에서 close 한 fd와 비교 후 **open되어 있는 fd를 fsync**

주요 코드 정리
- cmdlog_compelte_dual_write() 에서 prev_fd close 로직
  - log_flush_lock을 획득 한 상태에서 fd, next_fd 변경
  - log_fsync_lock을 획득 한 상태에서 더 이상 사용되지 않는 prev_fd를 close하고
  - cmdlog_file_fsync()에서 open된 fd만 fsync() 요청하기 위해 recent_closed_fd 설정

```
void cmdlog_complete_dual_write(bool success)
{
    int prev_fd = -1;

    pthread_mutex_lock(&log_gl.log_flush_lock);
    if (log_gl.log_file.next_fd != -1) {
        do_log_buff_complete_dual_write(success);
        prev_fd = do_log_file_complete_dual_write(success);
    }
    pthread_mutex_unlock(&log_gl.log_flush_lock);

    if (prev_fd != -1) {
        pthread_mutex_lock(&log_gl.log_fsync_lock);
        recent_closed_fd = prev_fd;
        (void)disk_close(prev_fd);
        pthread_mutex_unlock(&log_gl.log_fsync_lock);
    }
}
```
- cmdlog_file_fsync() 로직
  - log_flush_lock을 획득하고 fd, next_fd 정보 조회
  - log_fsync_lock을 획득하고 close 안된 fd, next_fd fsync
  - fsync가 성공 하면 nxt_fsync_lsn update
```
void cmdlog_file_sync(void)
{
...
    /* fsync the log files */
    pthread_mutex_lock(&log_gl.log_flush_lock);
    int fd      = log_gl.log_file.fd;
    int next_fd = log_gl.log_file.next_fd;
    pthread_mutex_unlock(&log_gl.log_flush_lock);

    pthread_mutex_lock(&log_gl.log_fsync_lock);
    if (1) {
        int ret = -1;

        /* fsync curr fd */
        if (fd != recent_closed_fd) {
            ret = disk_fsync(fd);
            if (ret < 0) {
                logger->log(EXTENSION_LOG_WARNING, NULL,
                            "log file fsync error (%d:%s)\n",
                            errno, strerror(errno));
                /* [FATAL] untreatable error => abnormal shutdown by assertion */
            }
            assert(ret == 0);
        }

        /* fsync next fd */
        if (next_fd != -1 && next_fd != recent_closed_fd) {
            ret = disk_fsync(next_fd);
            if (ret < 0) {
                logger->log(EXTENSION_LOG_WARNING, NULL,
                            "log file fsync error (%d:%s)\n",
                            errno, strerror(errno));
                /* [FATAL] untreatable error => abnormal shutdown by assertion */
            }
            assert(ret == 0);
        }

        /* update nxt_fsync_lsn */
        if (ret == 0) {
            pthread_mutex_lock(&log_gl.fsync_lsn_lock);
            log_gl.nxt_fsync_lsn = now_flush_lsn;
            pthread_mutex_unlock(&log_gl.fsync_lsn_lock);
        }
    }
    pthread_mutex_unlock(&log_gl.log_fsync_lock);
}
```

**Comment by jhpark816** [comment]
@MinWooJin 
쉬운 설명은 아니지만, 어떤 의미인지 이해합니다.

@minkikim89 
한번 검토해 보세요.

**Comment by jhpark816** [comment]
@MinWooJin 
질문이 하나 있어요.
- 앞서 fsync_ongoing 방안과 비교한다면, 어떤 방안이 더 나은가요 ?

**Comment by MinWooJin** [comment]
@jhpark816 
두 방법 모두 장단점이 있을 것 같습니다.
- fsync_ongoing 방안은
  - log_fsync_lock을 완전히 제거할 수 있어서 fd close 하는데 wait 할 필요가 없어지게 됩니다.
  - 대신 fd close가 chekcpoint thread, main thread 외에 gcommit thread 에서도 필요하기 때문에 거기에 따른 추가 코드들이 필요합니다.
- log_fsync_lock 방안은
  - log_fsync_lock을 획득 한 상태에서 fd를 close 해야하기 때문에 wait해야 합니다.
  - 대신 코드가  fsync_ongoing에 비해서 fd close에 대한 제어가 간결합니다.

**Comment by jhpark816** [comment]
@MinWooJin 
아. 한 가지 논의할 사항이 있네요.
- fd 변경, 조회는 flush_lock으로 보호하여야 합니다.
- close 작업 자체는 flush lock 없이도 된다고 보는 데, 어떤가요 ?

**Comment by MinWooJin** [comment]
@jhpark816 
네 저도 같은 생각입니다.
다만 close 작업은 fsync lock으로 보호하여야 합니다.

**Comment by jhpark816** [comment]
@MinWooJin
맞네요. 제안한 방식에서 close는 fsync lock을 잡은 상태에서 수행해야 하네요.
추가 질문이 있습니다.
- recent_closed_fd 값을 clear(-1로 설정)하는 코드를 두지 않을 생각인가요 ?

**Comment by MinWooJin** [comment]
@jhpark816 
recent_closed_fd 값을 clear 하는 코드가 필요 없다고 생각했었는데
fd가 재사용 될 수 있으니 cmdlog_file_sync()에서 fsync 후 `recent_closed_fd != -1`이면
clear 하도록 해야겠네요.

**Comment by jhpark816** [comment]
@MinWooJin @minkikim89 

먼저, 기존 코드에 버그가 있어, 수정이 필요합니다.
- cmdlog_complete_dual_write() 함수에 버그가 있습니다.
- 현재 구현
  - 무조건 prev_fd를 close 합니다.
- 수정 구현
   - snapshot 성공이면, prev_fd를 fsync() 후에 close()하는 것이 좋겠습니다.
      이는 sync logging을 준수하기 위함입니다.
   - snapshot 실패이면, prev_fd(즉, next_fd)를 바로 close()해도 됩니다.

그리고, 동시성 제어 관점에서 설명합니다.
설명을 쉽게 하기 위하여 sync logging을 가정합니다.
즉, cmdlog_file_sync()가 주기적으로 호출되는 환경을 가정합니다.
- 기본 방식 정리
   - fd 변경/조회는 log_flush_lock으로 보호합니다.
   - log_flush_lock은 flush 작업의 직렬화를 보장합니다.
   - log_fsync_lock은 fsync작업의 직렬화를 보장합니다.
- 동시성 제어에서 아래의 별도 변수를 사용하지 않기 위하여
   fsync()와 close() 작업을 cmdlog_file_sync()에서 수행합시다.
   - recent_closed_fd
   - fsync_ongoing/close_request
- checkpoint 동작의 수정
   - 시작 시의 cmdlog_file_open()은
      - next_fd 생성
   - snapshot 완료 시의 cmdlog_complete_dual_write()는
      - 성공 시: prev_fd = fd, fd = next_fd, next_fd = -1 (fd 변경)
      - 실패 시: fd 변경 작업 없음.
  - 종료 시의 cmdlog_file_close()는
      - next_fd가 남아 있으면 close 처리
      - snapshot 실패하는 다양한 경우에 대해 동일하게 처리하게 됨.

**Comment by MinWooJin** [comment]
@jhpark816 
먼저 prev_fd 처리에 따라 위 로직이 변경될 수 있어서 그부분부터 논의해야 할 것 같습니다.
prev_fd를 fsync()하는 이유가 잘 이해되지 않습니다.
prev_fd가 되었다는 의미는 이제 더이상 복구나 logging에서 사용되지 않을 파일이라는 건데
그 파일을 fsync() 하기 위해 위와같은 로직 수정이 필요한가요?

현재 vaild 하지 않은 파일에 대한 fsync()가 불필요한 작업을 하는게 아닌가 싶습니다.

기존에 complete_dual_write에서 prev_fd를 fsync 하지 않고 close 하는건 (fsync_lock을 잡지 않은건 버그라고 생각됩니다.) 더 이상 사용되지 않을 파일이고, dual_write로 설정되어 버퍼에 기록된 모든 로그 레코드도 prev_fd에 반영하지 않도록 최적화 했기 때문입니다.

**Comment by jhpark816** [comment]
@MinWooJin 
- 맞습니다. 버그는 아닙니다.
- 하지만, fsync()하더라도 문제는 없습니다.
   - 정상 기록된 log에 대해 sync 작업을 수행한다는 의미에서. (in sync logging)
   - 아직은 고려하지 않지만, 향후 (과거의) 특정 시점의 상태로 복구할 경우
- 오늘 살펴보니, 새로운 이슈가 하나 있네요.
   - multiple log records인 경우, 모두 하나의 log file에 기록되어야 할 것 같은 데,
     이를 보장하는 로직이 있어야 할 것 같습니다.

**Comment by MinWooJin** [comment]
@jhpark816 
- 특정 시점의 상태로 복구를 지원하기 위해선 skip dual write 로직이 제거되어야 합니다.
- multiple log records인 경우
  - 현재 cache lock을 잡은 상태로 operation에서 생성한 모든 log record를 기록하고, dual write 시작 설정도 cache lock을 잡고 설정하고 있기 때문에
  - multiple log record는 모두 dual_write 상태 이거나 아니게 됩니다.
  - vaild 한 fd에 대해선 하나의 log filed에 기록됨을 보장하고 있는 상태이고
  - prev_fd와 같이 skip 하도록 되어있는 file은 끊길 수 있습니다. 이부분도 prev_fd file을 vaild하게 보관하기 위해 skip dual write 로직이 제거되면 해결될 것으로 생각됩니다.

skip dual write 로직이 있을 경우에 fsync 하는게 의미가 없는 작업이라서,
이부분은 다른 이슈로 보고 처리하는게 맞지 않나 생각됩니다.

**Comment by jhpark816** [comment]
- skip dual write 로직은 무엇인가요 ?
- cache lock 잡은 상태에서 complete_dual_write하기 때문에 multiple log records 이슈는 없네요. OK.

**Comment by minkikim89** [comment]
현재까지 진행된 이슈 내용 검토했고 이견 없습니다.

**Comment by MinWooJin** [comment]
@jhpark816 
skip dual write 로직
  - checkpoint 완료 후 old cmdlog file에만 write 하는 lrec는 이미 new snapshot file에 기록되었기 때문에
  - do_log_buff_flush()에서 그러한 lrec는 skip 하고 new cmdlog file에 wirte 하는 로직입니다.

code.
```
static uint32_t do_log_buff_flush(bool flush_all)
{
...
        if (cleanup_process) {
            /* Cleanup process. (fd was set to next_fd in the previous step)
             * Skip if requested by old cmdlog file only.
             */
            if (dual_write_flag) {
                do_log_file_write(&logbuff->data[logbuff->head], nflush, false);
            }
        } else {
            do_log_file_write(&logbuff->data[logbuff->head], nflush, dual_write_flag);
        }
...
}
```

**Comment by MinWooJin** [comment]
@jhpark816 
메인이 되는 로직들을 먼저 검토했고, sync logging 일때는 괜찮은 것 같습니다.
기존에 고려되었던 `recent_closed_fd, fsync_ongoing/close_request` 대신 log file에 prev_fd를 두는것도 괜찮을 것 같습니다.
async logging과 같이 고려하면 prev_fd close 담당이 좀 애매해질 것 같습니다. log flush thread나 checkpoint thread가 해야하는데, sync mode 일 때는 gcommit thread가 담당 하고 async mode 일 때는 다른 thread가 담당하는 부분이 잘 맞지 않아보입니다.
향후에 sync / async mode 변경을 command로 제공하는 부분까지 고려하면 이부분에 대해 고민이 필요해 보입니다.

**Comment by MinWooJin** [comment]
@jhpark816 
prev_fd close를 기존과 동일하게 checkpoint thread가 하는게 낫지 않나 싶습니다.
- gcommit thread의 file_sync()에서 close 하더라도 `prev_fd` 변수 추가가 되어야 하기 때문에,
별도 변수를 사용하지 않기는 힘들 것 같습니다.
- fd는 checkpoint thread에 의해 open, 교체가 발생하기 때문에 close도 checkpoint thread가 담당하는게 의미상 괜찮을 것 같습니다.
- sync / async mode 변경을 command로 제공하는 부분을 고려하면 sync mode에서만 동작하는 gcommit thread 보다는 checkpoint thread가 나아보입니다.

**Comment by jhpark816** [comment]
@MinWooJin 
log_flush_thread가 close 작업을 담당하는 것이 좋겠어요.
log_flush_thread가 짧은 주기로 flush 작업을 맡고 있어서,
해당 log file에 더 이상 기록할 데이터가 없으면, close 하면 됩니다.
단, sync logging에서는 fsync_lsn 값을 확인하여
fsync가 완료된 file을 close하면 될 것 같습니다.

**Comment by MinWooJin** [comment]
@jhpark816 
기존 로직에서 skip dual write 로직은 제거 하고,
prev_fd에 대해 기록이 필요한 데이터를 모두 기록하고
fsync 까지 완료한 다음 close 하는 것 까지 포함한 의견으로 보입니다.

prev_fd에 남은 데이터까지 모두 기록하고 close 한다면 log_flush_thread가
하는게 나을 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin 
그렇게 처리하는 것이 가장 자연스러운 형태가 될 것 같고,
향후 특정 시점의 복구 기능이 요구될 때 쉽게 수정할 수 있을 것 같습니다.

**Comment by MinWooJin** [comment]
skip dual write 로직을 제거하고, flush thread에서 prev_fd 를 close 하기위한 로직 설계
- `do_log_buff_complete_dual_write()`
  - log file write 동작에서 checkpoint 성공, 실패에 따라 daul_write가 아닌 lrec를 prev_fd에 기록하거나, fd에 기록해야 함
  - complete_dual_write에서 log_write_lock 상태에서 이를 판별하고 보관하고 있어야 함
  - **(freq list에 lrec의 lsn을 확인하는 방법에 대한 고민이 필요)**
  - checkpoint 성공
    - fque list를 확인하면서 dual_write가 아닌 마지막 lrec를 찾고 index, lsn을 보관
  - checkpoint 실패
    - fque list를 확인하면서 daul_write인 마지막 lrec를 찾고 index, lsn을 보관
- `do_log_file_write()`
  - prev_fd != -1 인 상황에서는 보관된 index, lsn을 이용해 prev_fd, fd 에 대한 write를 구분
  - prev_fd != -1 (assert `next_fd == -1`)
    - dual write
      - prev_fd, fd에 모두 write
    - not dual write & checkpoint 성공
      - prev_fd에만 write
    - not dual write & checkpoint 실패
      - fd에만 write
    - sync mode 에서는 fsync_lsn을 조회하여 보관한 lsn보다 크거나 같은지 확인하고 prev_fd close
    - async mode 에서는 write 하고 직접 fsync 호출 후 prev_fd close
  - prev_fd == -1 인 상황에서는 기존과 동일

**Comment by MinWooJin** [comment]
cleanup dual write 로직 제거와,
prev_fd close를 flush thread가 수행하기 위한 설계 정리

- 기본 방식 정리
  - fd 변경/조회는 log_flush_lock으로 보호합니다.
  - prev_fd, next_fd에 대한 file close는 log_fsync_lock 상태에서 수행합니다.
  - log_flush_lock은 flush 작업의 직렬화를 보장합니다.
  - log_fsync_lock은 fsync작업의 직렬화를 보장합니다.
- checkpoint 동작의 수정
  - 시작 시의 cmdlog_file_open()은
    - next_fd 생성
  - snapshot 완료 시의 cmdlog_complete_dual_write()는 [flush lock]
    - 성공 시: prev_fd = fd, fd = next_fd, next_fd = -1 (fd 변경), [write lock] last_write_lsn 저장
    - 실패 시: fd 변경작업 없음, last_write_lsn 저장 x
  - 종료 시의 cmdlog_file_close()는
    - [fsync lock] next_fd가 남아 있으면 close 처리, closed_fd_event = true 세팅
    - 이는 snapshot 실패하는 다양한 경우에서 동일하게 처리하기 위함.
- cmdlog_buff_flush()에서 [flush lock]
  - prev_fd != -1 이면
    - sync mode : log_fsync_lsn과 last_write_lsn 을 비교하고 반영이 완료됨을 판별
    - async mode : log_flush_lsn과 last_write_lsn 을 비교하여 반영이 완료됨을 판별
    - 반영 완료 되었으면 : [fsync lock] fsync(prev_fd); close(prev_fd); closed_fd_event = true; prev_fd = -1; LOG_SET_NULL(last_write_lsn)
    - 반영 완료 안되었으면 : 다음에 flush loop에 재검사
- cmdlog_file_sync()에서
  - [flush lock] prev_fd, fd, next_fd를 조회
  - [fsync lock]
    - closed_fd_event == true 이면 : prev_fd, next_fd가 != -1 이면 조회부터 재수행
      - 이미 closed 된 fd에 대해 fsync() 작업을 수행하지 않기 위함
    - prev_fd, fd, next_fd에 대해 fsync 수행
- do_log_file_write()에서 [flush lock]
  - prev_fd != -1 이면
    - dual_write가 아닌 freq : prev_fd 에만 기록
    - dual_write인 freq : prev_fd, fd에 기록
  - prev_fd == -1 이면
    - dual_write가 아닌 freq : fd 에만 기록
    - dual_write인 freq : fd, next_fd에 기록

**Comment by MinWooJin** [comment]
#462 PR로 반영 완료 되었습니다.
issue close 합니다.
