### ISSUE TITLE
BUG: collection element 조회 실패에서 ENOMEM 응답 처리가 빠진 상태.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#437]
최근의 collection element 조회 방식에서
element 주소를 담을 메모리 공간 크기를 정확히 계산하기 위하여
memcached가 아닌 engine 내부에서 그 메모리 공간을 할당하는 것으로 변경하였고,
메모리 공간 할당이 실패하면 ENGINE_ENOMEM 오류가 발생한다.

이에 관련하여 확인 및 수정할 사항은 다음과 같다.
- 현재 ENGINE_ENOMEM 오류에 대한 응답을 보내는 코드가 없다.
  ENGINE_ENOMEM 오류 처리 코드를 추가하여야 한다.
- Java/C client에서 ENOMEM 응답을 받을 수 있는 상태인지도 확인한다.
  참고 사항으로, 예전 구현은 memcached 단에서 메모리 공간을 할당받았고,
  할당이 실패하면 ENOMEM 오류를 발생시켰기 때문에,
  Client 단에서 ENOMEM 응답 처리 코드는 존재할 것으로 예상한다.

**Comment by MinWooJin** [comment]
확인 결과 ENGINE_ENOMEM 오류에 대한 응답은 현재
unexpected_errorcode로 분류되어 `SERVER_ERROR internal`로 처리되는 상태이다.
ENOMEM 의 string 통일성을 위해 `SERVER_ERROR out of memory`로 response를 보내도록
처리하면 될 것으로 보인다.

Java/C client에서 "SERVER_ERROR" string 만으로 오류를 처리하기 때문에
응답을 받을 수 있는 상태이다.

**Comment by MinWooJin** [comment]
#440 PR로 반영 완료 되었습니다.
issue close 합니다.
