### ISSUE TITLE
[persistence] log waiter 생성 시, 현재 수행하는 연산 등록 (리팩토링)

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#441]
log waiter 엔트리에 현재 수행하는 연산(upd_type)을 등록하자.
이로 인한 장점은 clog 모듈에서
- element insert 연산에서 collection create 한다면, create if absent 상태를 알 수 있다.
- element delete 연산에서 collection drop한다면, drop if emtpy 상태를 알 수 있다.

따라서, 기존 구현에서
- log waiter 엔트리의 elem_insert_with_create, elem_delete_with_drop 필드를 제거할 수 있다.
- items 모듈과 loosely coupled 형태로 구현이 가능하다.

그 외에도, 현재의 log waiter가 어떤 update 연산을 수행 중인지를 알 수 있어서
다른 구현에서도 활용될 수 있다.

**Comment by MinWooJin** [comment]
#450 과 같은 이슈이므로 #450 에서 처리하는게 더 나을 것 같습니다.
현재 issue는 close 합니다.

**Comment by jhpark816** [comment]
동일 이슈인지 확인하지 않고 올렸네요.
