### ISSUE TITLE
[Docs] config command 관련 문서 보강 

### ISSUE THREAD

**Issue by computerphilosopher** [naver/arcus-memcached#444]
현재 arcus-memcached의 문서에서는 config 명령을 통해 변경할 수 있는 설정은 다음의 5개 밖에 없다고 명시되어 있다. ([링크](https://github.com/computerphilosopher/arcus-memcached/blob/develop/doc/command-administration.md))

- verbosity
- memlimit
- zkfailstop
- maxconns
- max_element_bytes

하지만 실제로는 sticky_limit, scrub_count 등의 수치도 config 명령을 통해 변경할 수 있는 것으로 확인되었다.

config 명령으로 변경할 수 있으나, 문서에 누락된 사항을 파악해 관련 부분을 다시 작성한다.

**Comment by computerphilosopher** [comment]
https://github.com/naver/arcus-memcached/pull/456 

PR한 상태입니다.

**Comment by jhpark816** [comment]
- sticky_limit은 향후 deprecated 시킬 가능성이 있어, 우선 빼 두시죠.
- @minkikim89 나머지에 대해 리뷰 바랍니다

**Comment by computerphilosopher** [comment]
[PR #456](https://github.com/naver/arcus-memcached/pull/456)이 머지 되었으므로 폐쇄합니다.
