### ISSUE TITLE
[persistence] LogSN의 roffset type 변경 검토

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#460]
현재 LogSN 의 구조는 아래와 같으며, uint32_t type의 filenum과 roffset 으로 구성되어 있다.
```
typedef struct logsn {
    uint32_t filenum;  /* cmdlog file number : 1, 2, ... */
    uint32_t roffset;  /* cmdlog record offset */
} LogSN;
```

filenum은 표현 범위를 초과 할 만큼 증가할 가능성이 없어 보이지만,
roffset의 경우 표현 범위를 초과할 가능성이 높다. (4GB)

- roffset의 type을 변경하여 4GB 이상 offset을 표현할 수 있게 하거나,
- file size가 4GB를 초과하면 checkpoint와 관계 없이 filenum을 증가
- checkpoint 조건에 cmdlog file size가 4GB에 가까워지면 checkpoint를 수행하도록 한다.
  - 이 방법 또한 checkpoint 수행 실패로 timed retry 하게 된다면 4GB가 넘어갈 가능성이 있는 문제가 있다.

**Comment by MinWooJin** [comment]
@jhpark816 
저는 checkpoint가 항상 성공한다는 보장이 없기 때문에
roffset의 type을 변경하는게 나은 방법이라고 생각되는데,
같이 검토 해주시면 좋을 것 같습니다.

**Comment by jhpark816** [comment]
단기적으로, roffset의 type을 64비트로 변경하는 것이 나은 것 같습니다.
type 변경 시에 변경 이유에 대한 주석을 달아 두기 바랍니다.

장기적으로, log file 관리 방식이 변경된다면,
그 시점에 LSN 관련하여 함께 변경하면 될 것 같습니다.

**Comment by MinWooJin** [comment]
#465 PR로 반영 완료 되었습니다.
issue close 합니다.
