### ISSUE TITLE
[persistence] fsync 실패에 대한 handling 세분화

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-memcached#473]
persistence sync thread(현재 gcommit thread)의
fsync() system call 실패에 대한 handling을 세분화 한다.

현재는 fd에 대해선 sync mode일 경우 shutdown 하는 방식으로 처리하고,
async mode일 경우엔 로그만 출력하고 있다.
next_fd에 대해선 sync, async mode 둘 다에서 로그만 출력하도록 처리한 상태이다.

향후 write() 실패와 같이 다양한 configuration으로 설정할 수 있도록 제공할 필요가 있다.

**Comment by jhpark816** [comment]
@MinWooJin 
다양한 configuration으로 설정한다는 것이 무슨 의미인가요 ?
구체적인 설명을 제공해 주면 좋겠습니다.

**Comment by MinWooJin** [comment]
@jhpark816 
향후 write() 실패에 대한 처리와 마찬가지로 다양한 실패 처리가 필요하고,
그 실패 처리를 선택할 수 있도록 제공해서 각 서비스에 맞는 처리를 사용할 필요가 있다는 내용입니다.

예를들면 shutdown, read only, persistence off 등이 있겠습니다.

**Comment by jhpark816** [comment]
@MinWooJin 

- 현재 sync logging 모드에서만 fsync() 호출이 될 것입니다.
  따라서, async_logging 구분한 처리는 제거하도록 하겠습니다.
- fsync() 실패 시에도 assert fail 처리하겠습니다.
   - 복제되지 않았다면, async logging으로 전환시키면 되지만,
   - persistence 사용한다면 복제 기능을 사용한다고 볼 수 있어서,
     assert fail 처리로 master failover 처리하는 것이 나을 것 같습니다.

**Comment by jhpark816** [comment]
위 코멘트와 같이 처리한 commit 입니다.
commit link: https://github.com/naver/arcus-memcached/commit/66665eeba65e44424eb9b374f28b464fd8bc87f4
