### ISSUE TITLE
NULL value 추가

### ISSUE THREAD

**Issue by minkikim89** [naver/arcus-memcached#484]
value 값으로 NULL을 사용할 수 있도록 한다.

value length 이 -1 일 때, 이를 NULL value 라고 정의하며 KV type에 우선 적용하도록 한다.
value length == -1 이면 read 할 value가 없으므로, 
client connection의 state machine을 conn_parse_cmd에서 conn_nread state로
변경하지 않고, 바로 요청 결과를 전달할 수 있도록 한다.

**Comment by oliviarla** [comment]
@jhpark816 이 이슈는 close해도 되나요?

**Comment by jhpark816** [comment]
@oliviarla 
NULL 값을 어떤 방식으로 제공한다는 코멘트를 남기고, 본 이슈는 close 하시죠.

**Comment by oliviarla** [comment]
Arcus 서버에서는 NULL 값을 저장하는 기능을 추가하지 않고, 응용에서 자체 NULL 값을 정의하여 캐싱에 사용하도록 가이드합니다.
NoSQL에는 NULL 저장 및 조회에 대한 표준이 없으며 응용에서 자체 NULL 값을 정의하여 사용하여야 다른 캐시 구현체로 변경하더라도 호환성이 유지되기 때문입니다.
