### ISSUE TITLE
item allocation 관련하여 refcount 증가/감소 제거

### ISSUE THREAD

**Issue by minkikim89** [naver/arcus-memcached#489]
item을 allocate 할 때 refcount는 1로 설정되고 
이를 link한 이후에 refcount를 감소 시키게 구현되어있다.
하지만 이는 실제 link 하지 않은 상태에서의 refcount를 증가시키는 것이므로 불필요한 구현이다.

이미 Element allocation 에 관련하여서는 refcount 증가/감소의 제거 작업을 진행한 상태이다.
(참조 https://github.com/naver/arcus-memcached/pull/340)
Item allocation 관련해서도 동일하게 refcount 증가/감소를 제거하도록 한다.

**Comment by memnoth** [comment]
지금 작업하고 계신분이 안 계시면 제가 하겠습니다.

**Comment by minkikim89** [comment]
https://github.com/naver/arcus-memcached/pulls 로 merge 되어 이슈 close 합니다.
contribution 감사합니다.
