### ISSUE TITLE
daemon으로 실행 시 상대경로로 입력한 engine library를 찾지 못하는 문제

### ISSUE THREAD

**Issue by minkikim89** [naver/arcus-memcached#503]
./_run_memcached_solo.sh의 스크립트 코드는 아래와 같다.
```
./memcached -E .libs/default_engine.so -X .libs/syslog_logger.so -X .libs/ascii_scrub.so $@
```
이 스크립트 코드는 그대로 실행하면 문제가 없지만 -d 옵션을 통해 데몬으로 실행하려 하면 실행되지 않는다.
-d 옵션에 -v 옵션을 추가하여 로그를 확인해보면 아래와 같이 오류 메시지 출력된다.
```
memcached[22508]: Failed to open library ".libs/default_engine.so": dlopen(.libs/default_engine.so, 6): image not found
```
이는 memcached 프로세스가 daemon으로 실행되며 상대 경로의 engine library를 찾지 못하는 문제이다. library 위치를 절대경로로 입력하면 정상적으로 동작하는 것을 확인할 수 있다.
이를 해결하여 daemon으로 프로세스를 실행하여도 상대 경로로 engine library를 입력할 수 있도록 한다.

**Comment by jhpark816** [comment]
@JJungwoo @minkikim89 
본 이슈에서는 script에서만 상대 경로를 절대 경로로 변경하도록 합시다.

따라서, arcus-memcached 캐시 노드를 데몬으로 구동하는 경우는 절대 경로를 주어야 합니다.
참고로, 절대 경로를 사용함으로써 가지는 장점은
캐시 장비에서 여러 캐시 노드가 구동되어 있는 경우 ps 명령으로
각 캐시 노드가 어떤 memcached 실행 파일과 so 파일을 가지고 수행하였는 지를 쉽게 알 수 있습니다.

**Comment by JJungwoo** [comment]
_run_memcached_solo.sh script 수정하여 이슈 해결
pr link : #551
