### ISSUE TITLE
[persistence] checkpoint thread가 log file close 시에 대기하는 기능 제거

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#514]
checkpoint thread가 log file close 수행에서 prev log file에 대한 sync 작업까지 완료될 때까지
대기하는 작업은 전체 로직을 복합하게 주요 요인으로, 이를 개선하는 다른 방식을 고안하여 구현합시다.
참고 사항으로
- current checkpoint에서 기존 log file에 대한 fsync 작업이 완료될 때까지 기다릴 이유가 없습니다.
- next checkpoint가 prev checkpoint가 완료된 이후에 시작할 수 있게만 하면 될 것으로 보입니다.
  - log file 모듈에서 이에 관한 상태 조회 함수만 있으면 되지 않나 생각합니다.

**Comment by SuhwanJang** [comment]
아래와 같이 변경하면 될 것 같습니다.

**current checkpoint 에서 log file fsync 작업을 기다리지 않음.** 
file close wait logic 이 필요 없어져 아래 정보들이 제거됨.
  - logfile->close_wait
  - logfile->log_flush_cond
  - do_log_file_close_waiter_wakeup(void)

**next checkpoint 는 prev checkpoint 의 fsync 작업 완료 후 진행**
 - logfile->fsync_remain 필드 추가
 - checkpoint 는 fsync_remain == false 이면 수행
 - cmdlog_file_open() 에서 next_fd 설정 시 fsync_remain = true
 - 기존 file_close_waiter_wakeup 호출하는 부분에서 fsync_remain = false
```
 void cmdlog_file_complete_dual_write(void)
 {
     log_FILE *logfile = &log_file_gl.log_file;

     if (logfile->next_fd != -1) {
         logfile->prev_fd   = logfile->fd;
         logfile->fd        = logfile->next_fd;
         logfile->size      = logfile->next_size;
         logfile->next_fd   = -1;
         logfile->next_size = 0;

         if (log_file_gl.async_mode) {
             (void)disk_close(logfile->prev_fd);
             logfile->prev_fd = -1;
 #ifdef JSH
             logfile->fsync_remain = false;
 #else
             do_log_file_close_waiter_wakeup();
 #endif
         }
     }
 }
```
```
 void cmdlog_file_sync(void)
 {
...
     if (prev_fd != -1) {
         /* If prev_fd is set, the prev file access only the log sync thread,
          * so log_fsync_lock is not needed to close the prev file.
          */
         ret = disk_fsync(prev_fd);
         (void)disk_close(prev_fd);

 #ifdef JSH
         pthread_mutex_lock(&log_flush_lock);
         logfile->prev_fd = -1;
         logfile->fsync_remain = false;
         pthread_mutex_unlock(&log_flush_lock);
 #else
         pthread_mutex_lock(&log_flush_lock);
         logfile->prev_fd = -1;
         do_log_file_close_waiter_wakeup();
         pthread_mutex_unlock(&log_flush_lock);
 #endif
     }
```

fsync_remain = false 되는 시점은 기존과 같이 cmdlog_file_close()에서 (next_fd != -1 || prev_fd != -1) 에 해당하는 시점이므로, 로직 상 문제 없어보임. 문제되었던, logfile 과 logbuffer 의 참조 관계도 없어지게 됨.
```
 void cmdlog_file_close(bool chkpt_success)
 {
     log_FILE *logfile = &log_file_gl.log_file;
     int remove_fd = -1;

     pthread_mutex_lock(&log_flush_lock);
     if (chkpt_success) {
 #ifndef JSH
         /* wait until the previous file is closed */
         while (logfile->next_fd != -1 || logfile->prev_fd != -1) {
             logfile->close_wait = true;
             pthread_cond_wait(&log_flush_cond, &log_flush_lock);
             logfile->close_wait = false;
         }
 #endif
     } else {
         if (logfile->next_fd != -1) {
             logfile->next_size = 0; /* prevent fsync() */
             if (log_file_gl.async_mode) {
                 remove_fd = logfile->next_fd;
                 logfile->next_fd = -1;
             }
#ifdef JSH
             logfile->fsync_remain = false;
#ifndef
         } else { /* the first checkpoint */
```

**Comment by jhpark816** [comment]
@SuhwanJang @MinWooJin 
`fsync_remain` 필드를 두지 않아도 되지 않나 생각해요.
`prev_fd == -1 && next_fd == -1` 상태로 검사할 수 있기 때문입니다.

**Comment by SuhwanJang** [comment]
@jhpark816 
그렇네요.. 코멘트 참고하여 PR 하겠습니다.

**Comment by MinWooJin** [comment]
@SuhwanJang 
cmdlog_file 내부 구현의 변경 보다는,
checkpoint thread가 어떤 방식으로 prev log file을 관리하도록 변경할지를 설명해주면 좋겠습니다.
이 부분에 따라 내부 구현도 달라질 수 있을 것으로 예상됩니다.

현재 구현처럼 설계된 이유는
- prev file을 마지막으로 접근하는 모듈(thread)가 file close를 담당하도록 하는 부분과(log_flush_lock),
- checkpoint thread가 checkpoint 진행 후 이제 더이상 사용하지 않을 prev log file을 즉시 제거하기 위한 부분도 있습니다.

제안한 로직은 checkpoint thread가 checkpoint를 진행 하고 prev file 을 어떻게 관리하는 건가요?

**Comment by jhpark816** [comment]
@MinWooJin @SuhwanJang 
checkpoint thread가 prev file을 직접 제거하는 경우도 있었나요 ? 그리고, 어떤 이유인가요 ?

**Comment by SuhwanJang** [comment]
@MinWooJin
`checkpoint thread가 checkpoint 진행 후 이제 더이상 사용하지 않을 prev log file을 즉시 제거하기 위한 부분도 있습니다.`
checkpoint thread 가 file close 이후 수행하는 remove_files 작업을 의미하는 것 맞나요?
아니라면 코멘트 해주시고, 맞다면 본 이슈와 어떤 관계가 있는지 설명 부탁드립니다.

**Comment by MinWooJin** [comment]
@SuhwanJang 
remove_files 작업을 의미하는게 맞습니다.
위 comment에 설명된 로직을 보면 checkpoint가 성공하면 checkpoint thread가 대기 없이
빠져나오게 되어있습니다.
기존 checkpoint thread가 그 다음 수행하는 로직은 prev file을 제거하는 로직인데
현재 상태는 prev file의 기록이 완료된 상태인지 아닌지 알 수 없는 상태입니다.
(기존에는 close_wait 로직을 통해 기록 완료를 대기했던 것입니다.)
변경되는 설계에서는 이런 부분을 어떻게 확인하고 관리할 것인가에 대한 부분이 정리되어야 할 것 같다는 의미입니다.

@jhpark816 
prev file은 checkpoint thread가 직접 제거하고 있습니다.
제거하는 이유는 recovery에 사용되지 않을 old checkpoint에 의해 생성된 file들을 제거해
디스크 용량을 확보하기 위함입니다.

**Comment by SuhwanJang** [comment]
@MinWooJin 
prev file 은 제거될 것인데, 기록 완료를 대기해야 하는 이유가 무엇 인가요?

**Comment by MinWooJin** [comment]
@SuhwanJang 
현재는 가장 최근에 성공한 checkpoint log 파일만 남겨두는 설정만 제공하고 있지만,
추후에 최근 N개 checkpoint log 파일을 남겨두는 설정을 제공할 수 있습니다.
특정 시점 복구 기능을 고려 하더라도, prev file remove는 해야 일정 크기의 디스크만 사용할 수 있습니다.
이때 prev file은 N개 이전의 file을 의미합니다.

만약, 가장 최근에 성공한 checkpoint log 파일만 남겨두는 현재 상태만 제공하는 것으로 최종 결정되면,
초기에 들어있었던 skip dual write 기능을 다시 추가하는게 효율적이겠습니다.

**Comment by SuhwanJang** [comment]
@MinWooJin 
`참고로, prev file은 제거될 파일이기 때문에 기록 완료를 대기하지 않더라도 prev file을 제거하기 전에 close 해야 합니다.`
unlink 이후에 close 하더라도, fd 를 갖고 있고 close 시점에 disk free 될 것 입니다. 이 작업은 next checkpoint 이전에 수행될 것이므로, 문제가 없어보입니다.

**Comment by jhpark816** [comment]
@MinWooJin @SuhwanJang 
- prev log file에 대해 close, unlik 작업은 log file 모듈이 담당하는 것이 맞지 않나 생각합니다.
   - 어떤 기간(or 크기) 까지 log를 보관할 것인지의 설정은 log file 모듈에 있는 것이 맞고,
      그 설정에 따라 log file 제거도 log file 모듈이 스스로 판단하여 진행하면 될 것 같습니다.
   - 참고로, 어떤 기간(or 크기)까지 log를 보관하는 것은 snapshot file과 연관되어져야 하는 데,
      snapshot file의 삭제는 현재 누가 담당하나요 ?
- checkpoint thread가 prev log file 제거 작업을 담당하지 않아도 될 것 같습니다.
   - role 관점에서 log file 모듈이 담당하는 것이 나은 것 같고,
   - checkpoint thread가 수행해야 할 명확한 이유는 아닌 것 같습니다.

**Comment by jhpark816** [comment]
@MinWooJin @SuhwanJang

snapshot file 삭제를 기존에 checkpoint thread가 담당하고 있었다면,
snapshot file에 연관된 log files 삭제도 checkpoint thread가 담당하는 것이 맞을 것 같습니다.
하지만, 이 경우라도 checkpoint 작업의 마지막에
prev file의 close 될 때까지 대기할 필요는 없을 것 같습니다.

**Comment by SuhwanJang** [comment]
@jhpark816 
checkpoint thread 가 snapshot file 삭제를 담당합니다. 
chkpt_files(snapshot, cmdlog) 를 create 한 주체인 checkpoint 가 삭제를 담당하는 것이 맞는 것 같습니다.

**Comment by jhpark816** [comment]
OK. 그렇다면, 내 생각엔,
- checkpoint thread가 snapshot files과 prev log files 삭제를 담당하게 하고,
   - 어떤 기간(or 크기)까지 보관할 것인지의 설정에 맞게 동작
   - checkpoint main loop 내에 이를 수행하는 로직(or 함수)이 있으면 됨.
- 하지만, checkpoint thread가 prev log file이 close될 때까지 대기하는 것은 불필요.
   - 즉, 현재의 checkpoint 작업과 old files 제거 작업은 서로 의존성이 없어도 됨.

**Comment by MinWooJin** [comment]
@jhpark816 @SuhwanJang  
동의합니다.
현재 상태로는 prev log file을 어떻게 제거할지 명확하게 알기 힘들어 추가 설명을 요청했었습니다.
주기적으로 제거해야 하는지 검사하고, 제거하는 로직을 추가하면 좋을 것 같습니다.
결국 현재 checkpoint 의 주기 검사와 파일 삭제 부분의 코드를 어떻게 정리할 것인지가 중요할 것 같습니다.

**Comment by SuhwanJang** [comment]
@jhpark816 @MinWooJin 
네. 아래와 같이 정리해서 PR 하겠습니다.
- next checkpoint 는 prev checkpoint 작업 끝난 이후 수행 ((prev_fd == -1 && next_fd == -1) 로 확인)
- log file close wait 제거
- checkpoint 파일 제거 부분 변경
  - 기존 file_close 후 remove_files 작업 제거
  - main loop 내에서 5초 주기로 do_chkpt_sweep_files() 수행 
    - 함수 역할은 last chkpt files 제외하고, 전부 제거
    - 수행 조건은 (prev_fd == -1 && next_fd == -1)인 경우

**Comment by SuhwanJang** [comment]
merged commit : https://github.com/naver/arcus-memcached/commit/69ae8b26d226e07376d6308f60488da16e68bf64

변경된 사항은 다음과 같습니다.
- cmdlog_file_close() 에서 chkpt_success 시 file_close wait 로직 제거. cmdlog_file_close() 는 chkpt_fail 시에만 호출.
- next checkpoint 는 prev checkpoint 의 logfile close 이후를 확인하고 수행
  - logfile close 확인 함수 정의 : cmdlog_file_dual_write_finished() (prev_fd == -1 && next_fd == -1)
  - checkpoint main thread logic 에서 이를 확인
- do_checkpoint()에서 cmdlog_file_close() 이후 수행하는 remove_chkpt_files 조건 변경
  - 스냅샷 실패 시에만 수행. 
  - 스냅샷 성공한 경우 prev_time 만 설정해두고, previous checkpoint file 제거는 checkpoint thread loop 에서 수행.
    - checkpoint 주기에서 (prev_time != -1  && cmdlog_file_dual_write_finished=true) 인 경우 remove_chkpt_files(prev_time) 수행
