### ISSUE TITLE
[persistence] cmdlog_complete_dual_write() 함수 재검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#521]
아래 함수에서 log file 모듈의 next_fd를 참조하지 않고 buffer 상의 정보를 참조하여 
dual write를 complete 시킬 수도 있을 것 같습니다. 검토 바랍니다.

```C
void cmdlog_complete_dual_write(bool success)
{
    if (cmdlog_get_next_fd() != -1) {
        do_log_buff_complete_dual_write(success);
    }
}
```

**Comment by SuhwanJang** [comment]
merged commit : https://github.com/naver/arcus-memcached/commit/e0a1688cf123c3bcd10d71297f1b9094d0de427d

complete_dual_write 는 checkpoint lasttime 값이 -1 이 아닐 때 (checkpoint 스레드에 의한 checkpoint 일 때) 수행하도록 다음과 같이 변경하였습니다.
- chkpt_scanp는 checkpoint lasttime 값이 -1 이 아니면 set.
- chkpt_scanp가 set 되지 않았다면, chkpt_scanp_close() 호출되지 않으므로 complete_dual_write() 수행하지 않음.
- next_fd 참조 코드는 제거
