### ISSUE TITLE
[persistence] cmdlog_get_file_size() 함수 재검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#522]
아래 함수에서 buffer의 dw_end 값을 참조하지 않고,
log file 모듈의 fd를 참조하여 current file size를 구할 수 있을 것 같습니다.
가능하다면, log buffer에서 이 함수는 제거하고,
log file 모듈에 cmdlog_get_file_size() 함수로 구현하면 좋을 것 같습니다.
검토 바랍니다.

```C
size_t cmdlog_get_file_size(void)
{
    size_t file_size = 0;

    pthread_mutex_lock(&log_buff_gl.log_write_lock);
    if (log_buff_gl.log_buffer.dw_end == -1) {
        file_size = cmdlog_get_current_file_size();
    }
    pthread_mutex_unlock(&log_buff_gl.log_write_lock);

    return file_size;
}
```

**Comment by SuhwanJang** [comment]
merged commit : https://github.com/naver/arcus-memcached/commit/62704bb64cf8c83272e3d16f11d8755a7dacd3e7

- logbuffer 모듈의 cmdlog_get_file_size() 함수를 제거하였습니다.
  - cmdlog_file_dual_write_finished()==true 이후에 해당 함수가 호출되므로, dw_end == -1 인 상태이어서 해당 값을 확인할 필요가 없음.
- logfile 모듈의 cmdlog_get_current_file_size() 함수명을 cmdlog_file_getsize() 로 변경하였습니다.
