### ISSUE TITLE
특정 prefix의 키 목록 조회.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#535]
특정 prefix에 속하는 모든 키 목록을 조회하는 기능이 요구되고 있습니다.

현재 dump 명령으로 키 목록을 얻을 수 있으나, 보다 효율적인 방안을 강구할 필요가 잇습니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
현재 key scan 기능으로 prefix에 속한 키 목록 조회가 가능하다고 봅니다.
맞다면, key scan 기능을 어떻게 활용하여 조회하는 지를 정리한 후에 본 이슈는 cloes 하죠.

**Comment by SuhwanJang** [comment]
keyscan 기능의 match matching 을 활용하여 prefix 에 속한 키 목록 조회
`keyscan <cursor> [count <count>] [type <type>] [match <pattern>]\r\n`

match 옵션 값에 `$prefix:*` 지정 
예시 )
- "shopping" prefix 조회 : `keyscan $cursor match shopping:*\r\n`

**Comment by jhpark816** [comment]
@SuhwanJang 
더 효율적인 방안이 필요한 지 검토해 보겠습니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
prefix 마다 별도의 hash table를 두어 키들을 저장하고 prefix의 hash table을 스캔하는 방안이
더 효율적인 방안이지만,
이에 대한 필수 요구 사항이 있지 않는 한, 현재로는 구현하지 않을 생각입니다.

현재 key scan 기능으로 prefix에 속한 키 목록 조회가 충분히 가능합니다.
이 정도의 기능으로 정리하고자 하며, 본 이슈는 close 합니다.
