### ISSUE TITLE
[persistence] checkpoint snapshot과 변경 연산의 cmdlog 생성 순서의 재검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-memcached#542]
checkpoint snapshot은
- cache lock을 잡고 어떤 item을 reference한 다음.
- cache lock을 해제한 후에 cmdlog를 생성합니다.

다른 worker thread가 해당 item을 변경하고 cmdlog를 생성한다면,
- 앞서 snapshot 작업에 의해 그 item에 대한 cmdlog가 먼저 기록된 후에
- 변경 연산에 의한 cmdlog가 기록되어야 합니다.

이러한 cmdlog 기록 순서가 보장되는 지를 검토합니다.

**Comment by SuhwanJang** [comment]
checkpoint thread 가 생성하는 cmdlog 는 new 스냅샷 파일에
다른 worker thread 가 생성하는 cmdlog 는 명령 로그 파일에 기록할 것입니다.
cmdlog 기록 순서는 코멘트대로 보장되지 않지만, 
복구 시에 스냅샷 파일을 먼저 이용하여 복구하기 때문에 변경 연산에 의한 cmdlog 는 스냅샷 cmdlog 이후에 replay 됩니다.
따라서 cmdlog 기록 순서는 보장할 필요가 없다고 생각합니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
OK. 충분히 이해됩니다.
