### ISSUE TITLE
[persistence] Persistence 설정 및 상태 정보를 조회하는 stats persistence 명령 개발

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-memcached#555]
Persistence 설정 및 상태 정보를 조회하는 stats persistence 명령을 개발하여 persistence 사용 및 운영에 도움을 줄 수 있도록 합니다.
`stats persistence` 명령 결과에 아래 정보들을 포함하도록 합니다.

- use_persistence
- data_path
- logs_path
- async_logging
- chkpt_interval_pct_snapshot
- chkpt_interval_min_logsize
- 복구하는데 걸린 시간(unit : seconds)
- 현재 명령 로그 파일 크기(unit : bytes)
- 현재 체크포인트 수행 여부
- 이전 체크포인트 수행 성공 여부
- 이전 체크포인트 시작 시간(unit : absolute timestamp)
- 이전 체크포인트 수행하는데 걸린 시간(unit : seconds)
- 이전 체크포인트 스냅샷 파일 크기(unit : bytes) // 사용자는 이 정보와 chkpt_interval_pct_snapshot 를 통해서 다음 체크포인트 수행 조건을 알 수 있음.

**Comment by Johyeyoung** [comment]
assign

**Comment by jhpark816** [comment]
@SuhwanJang 
`stats persistence` 명령의 response string을 정의해 주기 바랍니다.

**Comment by SuhwanJang** [comment]
@Johyeyoung  
`stats persistence` 명령의 response string이 아래와 같이 나오도록 하면 됩니다.
```
stats persistence
STAT use_persistence on
STAT data_path /home/test/arcus/data/ARCUS-DB
STAT logs_path /home/test/arcus/data/ARCUS-DB
STAT async_logging false
STAT chkpt_interval_pct_snapshot 100
STAT chkpt_interval_min_logsize 256
STAT recovery_elapsed_time_sec 5
STAT current_logfile_size_bytes 65555
STAT chkpt_in_progress true
STAT last_chkpt_is_success true
STAT last_chkpt_start_time 20201222182102
STAT last_chkpt_elapsed_time_sec 8
STAT last_chkpt_snapshot_size_bytes 423333
```

@jhpark816 용어가 적절한지 한번 검토 부탁드립니다.

**Comment by jhpark816** [comment]
@SuhwanJang 
아래와 같이 일부 수정하였습니다.
참고, chkpt 성공 여부는 의미가 없을 것 같아 last_chkpt_failure_count로 변경하였습니다.
이 값이 0 보다 크면, 뭔가 문제가 있다는 의미이고,
모니터링에서 이 값에 대해 alert 걸 수도 있을 것 같습니다.
확인 바랍니다.

----------------

`stats persistence` 명령은 `--enable-persistence` configure 옵션을 컴파일한 경우만 정상 동작합니다.

`stats persistence` 명령의 수행 결과는 use_persistence 값(on or off)에 따라 달라집니다.

use_persistence on 이면, 응답은 다음과 같습니다.
```
STAT use_persistence on
STAT data_path /home/test/arcus/data/ARCUS-DB
STAT logs_path /home/test/arcus/data/ARCUS-DB
STAT async_logging false
STAT chkpt_interval_pct_snapshot 100
STAT chkpt_interval_min_logsize 256
STAT recovery_elapsed_time_sec 5
STAT last_chkpt_in_progress true
STAT last_chkpt_failure_count 0
STAT last_chkpt_start_time 20201222182102
STAT last_chkpt_elapsed_time_sec 8
STAT last_chkpt_snapshot_filesize_bytes 423333
STAT current_command_log_filesize_bytes 65555
END
```
use_persistence off 이면, 응답은 다음과 같습니다.
```
STAT use_persistence off
END
```

**Comment by SuhwanJang** [comment]
@jhpark816 PR 리뷰하다보니 추가 검토가 필요한 부분이 있어 코멘트 답니다.
- last_chkpt_start_time 
  - 리뷰를 보니 체크포인트 성공 여부와 관계없이 체크포인트 조건이 충족되어 시작한 시간으로 생각하시는 것이 맞나요?
  - 처음에는 체크포인트 성공했을 때의 시작시간으로 생각했는데 위와 같이 체크포인트 조건이 충족되어 시작한 시간으로 설정하는 것이 상태 파악에 더 도움될 것 같습니다. 
- last_chkpt_failure_count
  - last_chkpt_start_time 은 계속 갱신될 것이므로 last_chkpt_start_time=T, last_chkpt_failure_count=3 정보를 봤을 떄 운영자가 T 시점에 3번 실패가 발생한 것으로 생각할 수 있습니다.
  - 체크포인트가 성공한 시간(last_chkpt_completion_start_time) 정보를 추가하면 last_chkpt_completion_start_time 이후부터 last_chkpt_failure_count 만큼 실패가 발생하였고 마지막에 체크포인트를 시작한 시간은 T였다 로 파악할 수 있을 것 같습니다.
- last_chkpt_in_progress
  - 현재 체크포인트를 수행하고 있는 지에 대한 정보이므로 last 가 붙는 것이 조금 어색하다는 생각이 듭니다.  chkpt_in_progress가 좀 더 자연스러운 것 같습니다.

**Comment by jhpark816** [comment]
@SuhwanJang
- last_chkpt_start_time
   - 체크포인트 조건이 충족되어 시작한 시간이 좋은 것 같습니다.
- last_chkpt_failure_count
   - 마지막 체크포인트가 수행되거나 성공될 떄까지 몇 번 실패한 것인지를 나타내면 됩니다.
   - 마지막 체크포인트 성공 이후에 다시 체크포인트 시작할 경우 0으로 reset하면 됩니다.
   -  last_chkpt_completion_start_time은 없어도 됩니다.
- last_chkpt_in_progress
   - 현재 수행하는 체크포인트가 마지막 체크포인트이므로, 이름은 그대로 사용하시죠.

**Comment by jhpark816** [comment]
@Johyeyoung @SuhwanJang 
ascii protocol 문서에 stats persistence 설명을 추가하시죠.

**Comment by SuhwanJang** [comment]
@Johyeyoung 
https://github.com/naver/arcus-memcached/blob/master/doc/ch11-command-administration.md 문서에 Stats 명령 쪽에 persistence 관한 설명을 추가해주세요.

**Comment by SuhwanJang** [comment]
@Johyeyoung 
본 이슈와 관련하여 merged 된 commit 링크를 달아주고 처리된 결과를 요약한 후 issue close 해주세요.

**Comment by Johyeyoung** [comment]
commit link : a37a066, 7e97f91 

추가된 내용은 다음과 같습니다. 
Persistence 설정 및 상태 정보를 조회하는 stats persistence 명령을 개발하여 persistence 사용에 도움을 줄 수 있도록 합니다.
포함하는 내용으로는 설정된 persistence 정보와 가장 마지막으로 수행된 체크포인트의 정보를 조회할 수 있도록 하였습니다. 
아래는 stats persistence 명령 결과에 포함된 정보입니다.
```
STAT use_persistence on
STAT data_path /home/test/arcus/data/ARCUS-DB
STAT logs_path /home/test/arcus/data/ARCUS-DB
STAT async_logging false
STAT chkpt_interval_pct_snapshot 100
STAT chkpt_interval_min_logsize 256
STAT recovery_elapsed_time_sec 5
STAT last_chkpt_in_progress true
STAT last_chkpt_failure_count 0
STAT last_chkpt_start_time 20201222182102
STAT last_chkpt_elapsed_time_sec 8
STAT last_chkpt_snapshot_filesize_bytes 423333
STAT current_command_log_filesize_bytes 65555
END
```
