### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by janghoy100** [naver/arcus-memcached#82]
run 에서
$ <arcus_install_path>/bin/memcached -m 4000 -p 11211 -E <arcus_install_path>/lib/default_egine.so
뒷쪽에 egine을 engine으로 고쳐야 할 것 같습니다.

**Comment by jhpark816** [comment]
@janghoy100 
제보 감사합니다.
오타는 이미 `develop` 브랜치에 수정된 상태이며, 향후 release 시에 `master` 브랜치로 포함될 것입니다.
